### ISSUE TITLE
Scheduler: read commands have no corresponding self.release_lock() for self.acquire_lock()

### ISSUE THREAD

**Issue by weidagang** [pingcap/tikv#1015]
What did you expect to see?

[/storage/txn/scheduler.rs](https://github.com/pingcap/tikv/blob/master/src/storage/txn/scheduler.rs):
Even though no latches are required for read commands, release_lock() and acquire_lock() should always match, otherwise the code is not generic and error-prone. Prefer calling self.release_lock() in on_read_finished() explicitly to mark the completion of command.

**Comment by zhangjinpeng1987** [comment]
@weidagang you are well come to solve it.
