### ISSUE TITLE
calculate the used space correctlly

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1025]
When calculate the used space , we use get_property_int("rocksdb.total-sst-files-size"), but this function just get the size of the default cf, we need calculate the others column families' size too.

**Comment by siddontang** [comment]
we can travel the store path and calculate the size, or use `get_property_int_cf` to get other CF size.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/1026 fixed this issue
