### ISSUE TITLE
capture signal to stop tikv gracefully

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1053]
Now, we don't capture the signal and handle it. 
If we use `pkill tikv-server`, the `tikv-server` will be terminated directly without any cleanup. This may cause data corruption. 

We should capture the signal, and handle it, like:

+ For SIGINT, SIGTERM, close tikv gracefully. 
+ For SIGUSER1 or SIGUSER2, dump the metrics.

**Comment by siddontang** [comment]
rocksdb doesn't close successfully, may be the risk.

**Comment by hhkbp2** [comment]
related to #947
