### ISSUE TITLE
Improve tikv-dump to support mvcc decoding.

### ISSUE THREAD

**Issue by disksing** [pingcap/tikv#1077]
In short, I propose to add a new flag 'mvcc' to dump mvcc encoded key-value pairs. All cf's key-values are encoded as following:

|  | default | lock | write |
| --- | --- | --- | --- |
| **key** | z{encoded_key}{start_ts(desc)} | z{encoded_key} | z{encoded_key}{commit_ts(desc)} |
| **value** | {value} | {flag}{primary_key}{start_ts(varint)} | {flag}{start_ts(varint)} |
- Leading _z_ is created by raftstore.
- _encoded_key_ is a key received from client after been encoded by `encodeBytes`.  https://github.com/pingcap/tikv/blob/master/src/util/codec/bytes.rs#L31
- _value_ is the value received from client.
- _ts(desc)_ is a txn's ts after been encoded by `encode_u64_desc`.  https://github.com/pingcap/tikv/blob/master/src/util/codec/number.rs#L76
- _flag_ a byte could be either P(PUT), D(DELETE), L(LOCK), or R(Rollback).
- _primary_ is a txn's primary key after been encoded by `encode_compact_bytes`. https://github.com/pingcap/tikv/blob/master/src/util/codec/bytes.rs#L56
- _ts(varint)_ is a txn's ts after been encoded by `encode_var_u64`. https://github.com/pingcap/tikv/blob/master/src/util/codec/number.rs#L92

Usage example (dump a key's write cf):

```
./tikv-dump --store "foo/db" -mvcc -k "t\\200\\000\\000\\000\\000\\000\\000\\377R_r\\200\\000\\000\\000\\000\\377\\004\\251\\322\\000\\000\\000\\000\\000\\372" -c write
```

Output (2 PUT records found):

```
key: zt\\200\\000\\000\\000\\000\\000\\000\\377R_r\\200\\000\\000\\000\\000\\377\\004`B\\000\\000\\000\\000\\000\\372\\372\\243\'W\\350{\\377\\355
value: P\\227\\200\\220\\212\\201\\225\\266\\256\\005
type: PUT
commit_ts: 386421884507652114 
start_ts: 386421884402794519

key: zt\\200\\000\\000\\000\\000\\000\\000\\377R_r\\200\\000\\000\\000\\000\\377\\004`B\\000\\000\\000\\000\\000\\372\\372\\243\'\\303\\n\\323\\377\\351
value: P\\212\\200\\260\\367\\316\\207\\266\\256\\005
type: PUT
commit_ts: 386421424369958934
start_ts: 386421424265101322
```

**Comment by BusyJay** [comment]
I think subcommand is better in this case.

**Comment by siddontang** [comment]
yes, may we should use subcommand to distinguish mvcc and raft.

**Comment by mrmiywj** [comment]
Thx! I'll take a look at it.
