### ISSUE TITLE
add metrics for raft

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1081]

**Comment by siddontang** [comment]
@xiang90 
seem that etcd has no metrics in raft library, any plan to add?

**Comment by xiang90** [comment]
We do not plan to add. You can do that outside raft lib I believe.

**Comment by siddontang** [comment]
Now the metric PEER_RAFT_READY_COUNTER_VEC contains sending message count, we should also distinguish different message types.
E.g, if there are many Vote raft messages, some thing may happen to disturb the cluster.

**Comment by siddontang** [comment]
Now we only statistic Vote message, I think we should support all message types. 
@hhkbp2
