### ISSUE TITLE
tikv start error: LZ4 is not linked with the binary

### ISSUE THREAD

**Issue by zhnew** [pingcap/tikv#1101]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

rustc 1.13.0-nightly 

2. What operating system and processor architecture are you using?

Debian 3.16.36-1
x86_64 GNU/Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

After build tikv, I try to start tikv with a standalone cluster, my command is

"tikv-server -I 1 \
            -S raftkv \
            --pd 127.0.0.1:2379 \
            -s tikv"

4. What did you expect to see?

tikv to run

5. What did you see instead?

some error info, as follows:
...................
2016-09-22 20:46:07,965 tikv-server.rs:121 - INFO  - rocksdb.writecf.max-bytes-for-level-base, use default Some(67108864)
2016-09-22 20:46:07,965 tikv-server.rs:121 - INFO  - rocksdb.writecf.target-file-size-base, use default Some(16777216)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument: Compression type LZ4 is not linked with the binary."', ../src/libcore/result.rs:799

It looks that LZ4 lib is not linked with tikv, so I install liblz4-dev, but it does no help. Can anybody help me ?

**Comment by siddontang** [comment]
Hi @zhnew

Seem that you compiled RocksDB without lz4.
You may re-compile the RocksDB first, then re-compile the TiKV.

**Comment by siddontang** [comment]
Hi @zhnew 
Maybe you only need to re-compile RocksDB.

**Comment by zhnew** [comment]
@siddontang Thank you for your attention. I have compiled RocksDB with "make shared_lib". and linked the generated 'librocksdb.so' to /usr/local/lib, but the error was still showed.

**Comment by siddontang** [comment]
do you use `ldconfig` to let system find the library?

**Comment by siddontang** [comment]
Or can you show me what is the output for the RocksDB building?

**Comment by zhnew** [comment]
thank you again,  I will try one more time.

**Comment by zhnew** [comment]
@siddontang thank you very much for your quick response and help. the problem is fixed, it turns out that I make wrong use of "ln -sf src dst" command, I am so stupid. It works now.
