### ISSUE TITLE
pd: mock pd-server to test pd mod

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1102]
Now we start a real PD server to test pd mod, but it is not convenient, and most of times, we may ignore this test in local machine. 
Maybe we can mock a pd server to test HTTP handshake + network RPC communication.

**Comment by overvenus** [comment]
Yet another mockup https://github.com/overvenus/rust-pd

**Comment by siddontang** [comment]
embed this in tikv test directly.

**Comment by overvenus** [comment]
FYI, #1591 includes a rust PD mockup.
