### ISSUE TITLE
log panic info when we meet panic

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1129]
Now we hook panic in `set_exit_hook`, maybe we can log the panic info when we meet panic.

**Comment by BusyJay** [comment]
Currently there is no convenient way to implement it. Maybe we should capture stderr instead when starting TiKV.

**Comment by siddontang** [comment]
We can refer https://github.com/sfackler/rust-log-panics/blob/master/src/lib.rs

Capture stderr is not easy too if we use log file.

**Comment by BusyJay** [comment]
Why? Using `nohup` or just redirect Stderr to the log file should do the work perfectly.

**Comment by siddontang** [comment]
Here is to avoid not using `nohup`.

If we redirect Stderr to the log file, but how do we do if we rotate the log?
