### ISSUE TITLE
use FnvHashMap instead of origin SipHashMap with integer key. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1131]
We have may HashMap with integer key, maybe we can use FnvHashMap instead of origin SipHashMap, because it is more fast, see https://blog.rust-lang.org/2016/03/02/Rust-1.7.html

We should also do some benchmark.

**Comment by BusyJay** [comment]
Should bench BTreeMap too.

There are two common use cases in our project:

1. querying a small Map (normally 3 or 5 entries) and with little inserts/remove;
2. updating and querying a large map (may contains 10000+ entries) very frequently.

**Comment by overvenus** [comment]
Env:
 - CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
 - Memory: 16GB, DDR3, 1600 MHz

Case 1:

```
test bench_btreemap_small_set    ... bench:          79 ns/iter (+/- 1)
test bench_fnv_hashmap_small_set ... bench:         144 ns/iter (+/- 9)
test bench_sip_hashmap_small_set ... bench:         172 ns/iter (+/- 3)
```

Case 2:

```
test bench_btreemap_large_set    ... bench:     942,272 ns/iter (+/- 28,646)
test bench_fnv_hashmap_large_set ... bench:     696,743 ns/iter (+/- 21,032)
test bench_sip_hashmap_large_set ... bench:     678,117 ns/iter (+/- 18,968)
```

[Benchmarks Files](https://github.com/overvenus/bench-set/blob/master/benches/map.rs)

**Comment by siddontang** [comment]
what's the insert performance for large set? e,g, remove a key and then add a new one.

**Comment by siddontang** [comment]
@overvenus 

Seem that we can use FNV now.
