### ISSUE TITLE
log time is incorrect in docker

### ISSUE THREAD

**Issue by nolouch** [pingcap/tikv#1135]
In  docker container, the log time is wrong. and i have used `-v/etc/localtim:/etc/localtime`

1. What version of Rust are you using (`rustc --version`)?
   rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)

2. What did you expect to see?
the  log should print  the time same as the date show  in container 
3. What did you see instead?
```
docker  run -ti --rm --entrypoint="/bin/sh" -v/etc/localtime:/etc/localtime pingcap/tikv

/ # date
Wed Oct  5 11:38:52 CST 2016

/ # ./tikv-server
2016-10-05 03:39:03,687 mod.rs:390 - INFO  - Welcome to the TiKV.
2016-10-05 03:39:03,687 mod.rs:391 - INFO  - Version:
2016-10-05 03:39:03,687 mod.rs:392 - INFO  - Git Commit Hash: ba65f44eef0ce13f7c4f2f647d5c59955f691cce
2016-10-05 03:39:03,687 mod.rs:393 - INFO  - UTC Build Time:  2016-10-01 03:37:28
2016-10-05 03:39:03,687 tikv-server.rs:84 - INFO  - server.addr, use default Some("127.0.0.1:20160")
2016-10-05 03:39:03,687 tikv-server.rs:866 - INFO  - Start listening on 127.0.0.1:20160...
2016-10-05 03:39:03,687 tikv-server.rs:84 - INFO  - server.dsn, use default Some("rocksdb")
```

**Comment by siddontang** [comment]
what does the `date` output in docker?

**Comment by nolouch** [comment]
you also can see it in question 3
```
/ # date
Wed Oct  5 11:38:52 CST 2016
```

**Comment by siddontang** [comment]
oh, sorry, I did't note this before, maybe we can leave a blank so we can see `date` and `tikv-server` more clearly.

**Comment by BusyJay** [comment]
`pingcap/tikv` is built upon alpine, which use musl's libc implementation. This implementation only supports specifying timezone in the POSIX way, which configures it via `TZ` environment. So you need to set `TZ` to `/etc/localtime` explicitly.

**Comment by siddontang** [comment]
See https://github.com/docker/docker/issues/12084#issuecomment-89726892
It seems that we can't mount `/etc/localtime` only, for tikv, we must mount `/etc/timezone` too. 
@iamxy

**Comment by siddontang** [comment]
@BusyJay 
Setting `TZ` or `/etc/timezone` can't work.

**Comment by BusyJay** [comment]
What command do you use to start the container? It should be something like

```
docker run -e "TZ=/etc/localtime" -v/etc/localtime:/etc/localtime pingcap/tikv
```

or 
```
docker run -e "TZ=/path/to/tzfile" pingcap/tikv
```

Please note that, it may not work if you start linux container on OS X host. Maybe we should include tzdata in the image. @iamxy

**Comment by siddontang** [comment]
Above two ways can't work.
Btw, we even tried tzdata, and it can't work too.

**Comment by siddontang** [comment]
My fault, `docker run -e "TZ=/etc/localtime" -v/etc/localtime:/etc/localtime pingcap/tikv` can work.

**Comment by iamxy** [comment]
I've added `ENV TZ=/etc/localtime` into Dockerfile, thx for @siddontang and @BusyJay.
