### ISSUE TITLE
close the store connection if receives message with wrong store id.

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/tikv#1153]
1. Receiver: close the connection if receives message with wrong store id.
2. Sender: update store address from PD periodically.

**Comment by BusyJay** [comment]
I think first check should solve the problem. It should be checked in `RaftStoreResolver`. Do we need to check cluster_id too?

**Comment by huachaohuang** [comment]
Where is `RaftStoreResolver`?

**Comment by BusyJay** [comment]
https://github.com/pingcap/tikv/blob/master/src/server/transport.rs#L79
