### ISSUE TITLE
Report region size to PD

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1177]
sub-issue of issue #1005 

Currently there is no enough info for PD to implement the region merge policy.
A simple idea is that PD could trigger region merge basing on the region size. It's expensive to scan the whole region to get its size. An approximate way to get the region size is: 
1. add a `size_hint` variable for region state, as `size_diff_hint` for region split
2. update this `size_hint` for every put/delete, and make it persistent to hard driver
3. report this `size_hint` to PD on every region heartbeat

**Comment by siddontang** [comment]
I think it is better for TiKV itself knows how to do Merge, not PD triggers.

**Comment by siddontang** [comment]
/cc @disksing 
Only GC can really delete the data, maybe it is better to check whether the region should be merged or not after GC.

**Comment by disksing** [comment]
@siddontang Do you mean that do not add `size_hint` to track it, but scan all key-values after GC complete?

**Comment by siddontang** [comment]
I don't know how to set `size_hint` properly. 
If we do GC for a region, we can use `get_approximate_size` instead, of course this function is not accurate, but if we get a very small value size, we can think the region has little data and then do the `scan` check later.
