### ISSUE TITLE
TiKV memory usage

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1203]
When execute  a query like `select count(*) from (select * from sbtest1 order by pad) as a;`, the TiKV takes a lot of memory, and never give back.
When I config block-cache=1GB, and execute the query several times, the memory usage is as follows and last to now.
```
PR  NI    VIRT    RES
20   0 11.068g 7.559g 
```

**Comment by siddontang** [comment]
The memory is occupied by RocksDB or our program? Can we know it?

**Comment by zhangjinpeng1987** [comment]
The send buffer of `Conn` should shrink to a reasonable size when big query finished.

**Comment by siddontang** [comment]
@BusyJay
