### ISSUE TITLE
Necessary to use as part of TiDB?

### ISSUE THREAD

**Issue by alexreg** [pingcap/tikv#1212]
Some people, myself included, are keener just to use a key-value store, and build other sorts of databases on top of it, rather than using SQL. Will this ever be possible?

**Comment by mrmiywj** [comment]
Yes. You can just use TiKV as a distributed key-value database.

**Comment by siddontang** [comment]
Hi @alexreg

Now we only have a go client, you can see how to use it here https://github.com/pingcap/tidb/blob/master/benchkv/main.go

**Comment by alexreg** [comment]
Oh right. In that case, the line in the README about needing to build and run as part of TiDB is rather misleading, I think…

**Comment by siddontang** [comment]
Hi @alexreg 
You can't use TiKV alone, must with PD if you only want to use it as a distributed Key-Value store. Btw, the go client now belongs to TiDB and has not been separated from TiDB.  

The **TiDB project** contains PD, TiKV, and TiDB, and in production, now we only support using them together, have not provided an independent KV outside. So I think the README is ok now. 

It is not difficult to add clients for TiKV (The RPC protocol is easy and may be more easier if we support gRPC later), so you can use TiKV + PD as a distributed KV alone, no need to depend TiDB. 

It is very appreciated that you can help us do this and if you have any problem, please tell us.

**Comment by alexreg** [comment]
Thanks for the info, @siddontang. That's fair enough. PD seems essential, though I wonder if you will be removing the dependency on etc in time? It's interesting that TiKV is written in Rust, but TiBD/PD are in Go... do you plan to make everything all Rust or all Go in time?

I'll let you know how I get on, and if there any problems I run into (and solutions), I will post them.

**Comment by siddontang** [comment]
Hi @alexreg 

>  though I wonder if you will be removing the dependency on etc in time
What is "the dependency on etc"?  I don't know, sorry :-)

> do you plan to make everything all Rust or all Go in time?
We have no plan and will not do it later too. Go and Rust have their own advantages and shortcomings. 
We use Go for TiDB and PD because we want to develop them fast, and don't care the GC problem too much. But For TiKV, we must ensure that it has a very high performance and can't be effected by GC, so we use Rust.

**Comment by alexreg** [comment]
Hi @siddontang. Sorry, typo – I meant etcd. In the PD README file, it states "PD supports distribution and fault-tolerance by embedding etcd."

Regarding the use of Go/Rust, I quite understand. Of course, it's nice to have all technology unified under one language, but perhaps a Rust port/equivalent of PD will pop up at some point. :-)

**Comment by ngaut** [comment]
@alexreg It's ready to use TiKV as a distributed key-value database. We just provide the raw API which can be used if you don't need transaction and MVCC. And it's fast, demo is here: https://github.com/pingcap/tidb/blob/master/cmd/benchraw/main.go#L38

Currently we have a few very simple raw API: get/put/delete/
Happy hacking.
