### ISSUE TITLE
raft: Implement the PreVote RPC described in thesis section 9.6 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1213]
Refer https://github.com/coreos/etcd/pull/6624

For PreVote, see https://github.com/ongardie/dissertation/blob/master/leaderelection/prevote.tex

**Comment by mrmiywj** [comment]
I may want to take this issue if it is not so urgent to be implemented.

**Comment by siddontang** [comment]
Hi @mrmiywj 
Etcd has already merged the PR. You can do it next week.

**Comment by mrmiywj** [comment]
@siddontang 
I'll go on this.

**Comment by siddontang** [comment]
Ping @mrmiywj
