### ISSUE TITLE
Open RocksDB too slow

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1214]
When there are a large number of data, recover from manifest takes a long time.
```
➜  [115] db du -sh ./
878G	./

2016/10/23-13:09:32.172179 7f97193f8a40                Options.report_bg_io_stats: 0
2016/10/23-13:13:32.557831 7f97193f8a40 Recovered from manifest file:/data/var/store/db/MANIFEST-101922 succeeded,manifest_file_number is 101922, next_file_number is 142492, last
_sequence is 1935075444, log_number is 0,prev_log_number is 0,max_column_family is 3
```

**Comment by siddontang** [comment]
@hhkbp2 handled this before https://github.com/pingcap/tikv/pull/1079
Can it not work?

**Comment by hhkbp2** [comment]
@zhangjinpeng1987 
What is the actual size of the manifest file, and the corresponding start time?

**Comment by zhangjinpeng1987** [comment]
12MB

**Comment by hhkbp2** [comment]
@zhangjinpeng1987 If it takes a number of minutes for the db to re-open, it seems all right to me.
If a short re-open time is needed, please modify the max size of the manifest file to a smaller value.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/1222 fix this issue
