### ISSUE TITLE
Use region range to check whether a new region should be created

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tikv#1217]
If a store receives a valid message which target a missing region, the missing region will be created immediately. This strategy is good for moving region around. But if the new region is supposed to be split from existing region, then the creation is unnecessary. And it may cause too much IO load too (generate and apply snapshot).

We can use region range to detect whether a new region should be created. If the target region is overlapped with existing region on the store, then the message should be ignored.

To reduce the message size, we may only allow MsgRequestVote and MsgHeartbeat to trigger creating a new region.

**Comment by siddontang** [comment]
We have lots of Heartbeat messages, and must consider the network pressure too.

**Comment by hhkbp2** [comment]
1. Will it cause a network pressure, when these keys have a long size? E.g. an user specifies a long key, such as 1M. 
2. Only a short time after the region split or config change(specially speaking, add member), the heartbeats act as the triggers to create new peers. When a leader knows that all peers are active for its region, the start_key and end_key could be avoided.
