### ISSUE TITLE
dead lock in txn::scheduler

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1223]
If the `RaftKV` forget to send message to `txn::scheduler` after the asynchronous write has finished, this may cause dead lock in the `txn::scheduler`. This problem has only occurred once in our bench test.

**Comment by ngaut** [comment]
Is it possible we can track those dead locks ? Any reliable way to do that ?

**Comment by zhangjinpeng1987** [comment]
We can add more metrics in `raftstore`.

**Comment by ngaut** [comment]
Can we re-produce the issue ?

**Comment by zhangjinpeng1987** [comment]
`Can we re-produce the issue ?`
No, it occurs randomly with a low probability.

**Comment by zhangjinpeng1987** [comment]
What we can do is add more metrics, and if the problem happens again, we can track which stage the message has lost.
