### ISSUE TITLE
scan operation don't fill block cache

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1244]
Scan operation will flush block cache, this may cause a lot of block cache miss. So when we scan a range don't fill the block cache.

**Comment by zhangjinpeng1987** [comment]
Fill cache just depend on operation type is a very rough, when two query need scan the same range, if we don't fill cache, the second query will execute slowly.

**Comment by zhangjinpeng1987** [comment]
MyRocks make it configurable and fill cache for scan operation by default.

**Comment by siddontang** [comment]
can we close it now? @zhangjinpeng1987
