### ISSUE TITLE
perf: improve loading data performance 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1261]
1. [ ] Prepare data (15GB, 100GB and 500GB)
2. [ ] Use `myloader` to load the data into MySQL, we will use the time as the baseline time.
3. [ ] Use `myloader` to load the data into TiDB, and profile to see where we can improve.

**Comment by zhangjinpeng1987** [comment]
The write amplification of random write are various when the working set is different，we should test 15GB, 100GB and 500GB.
