### ISSUE TITLE
Check max open files when starting TiKV

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1263]
If the system `ulimit -n` is small, we may meet `too many open files` error.

We can check the resource limit (maybe use C API getrlimit ) when starting TiKV, if the max open files is small (< 10000), we should log an error.

**Comment by ngaut** [comment]
10000 is too small, currently tikv's max_open_fd in rocksdb is 40000, we should using a much larger value in production, like 500000.

**Comment by ngaut** [comment]
Also we should check those configurations:
net.ipv4.tcp_syncookies=0
net.core.somaxconn = 32768

And swap space should be off.

**Comment by siddontang** [comment]
Btw, now we have a `max-open-files` in RocksDB configuration.
If current process max open files is less than the configured one, panic.
