### ISSUE TITLE
check validation for pd list format.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1274]
One user passes ":2379,127.0.0.2:2379,127.0.0.3:2379" to tikv, although tikv can work correctly, it   is still better to panic because of the wrong pd list format.

**Comment by BusyJay** [comment]
How to tell if it's an invalid address or down pd instance?

**Comment by siddontang** [comment]
We don't care it here, only format.

**Comment by BusyJay** [comment]
Then do we need to check ipv6 address here? Is `123:123` a valid hostname?

**Comment by siddontang** [comment]
yes, we will check ipv6 too.

**Comment by overvenus** [comment]
I think we should only accept a subset of URI which I'd recommend `Host:Port`.

`SocketAddrV4::from_str(addr), SocketAddrV6::from_str(addr)` is the quickest way but with little overhead.

Also, `domain.name:port` is a valid address (or not?).
