### ISSUE TITLE
server: drop message when socket is still connecting 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1325]
When we want to send message to the remote store, the flow is:

1. Resolve the store address in another thread 
2. After resolving, connect the remote the store
3. Append the message to the send buffer and register Writable in epoll. 
4. Send data when the socket is writable
5. Remove the connection when error

We drop the message in stage 1, but we should also drop it in stage 2. 
The socket is asynchronous, when we call `connect`, we can get the socket quickly but the socket is still connecting and we can't send data until the socket become connected. 

If the connect timeout is 3s, if we send data to a down store, we can get the socket directly, but after 3s later, we can know that we can't connect the remote store. During this time, we may append lots of message and let the send buffer increase hugely.

**Comment by BusyJay** [comment]
I don't think it's a good idea to detect stage 2.

First, there is no good way to detect if the connection is being built. Second it doesn't solve the problem entirely. A slow connection or a lost connection can also make the send buffer huge.

**Comment by siddontang** [comment]
Maybe we will use MaxSendBufferSize to check later.
