### ISSUE TITLE
test: QPS fails to 0 in block writer test 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1336]
```
   27s: 3209.8/sec
   28s:    0.0/sec
   29s:    0.0/sec
   30s:    0.0/sec
   31s: 1429.1/sec
   32s: 2963.0/sec
```

The error log in tidb is 

```
2016/11/22 14:55:21 backoff.go:168: [warning] stale_epoch:<> , retry later(totalSleep 100ms, maxSleep 10000ms)
2016/11/22 14:55:21 backoff.go:168: [warning] stale_epoch:<> , retry later(totalSleep 100ms, maxSleep 10000ms)
2016/11/22 15:00:26 kv.go:221: [warning] tikv reports `NotLeader`: region_id:16 leader:<id:18 store_id:5 > , ctx: region_id:16 region_epoch:<conf_ver:3 version:3 > peer:<id:17 store_id:1 > , retry later
2016/11/22 15:00:26 kv.go:221: [warning] tikv reports `NotLeader`: region_id:20 leader:<id:23 store_id:4 > , ctx: region_id:20 region_epoch:<conf_ver:3 version:5 > peer:<id:21 store_id:1 > , retry later
```

**Comment by disksing** [comment]
Update:
Have it tested on my machine, QPS never drop down to 0, but sometimes it drops from ~6000/s to less than 1000/s.
As I can observe, when QPS drops down, tikv thread 'rocksdb:bg*' consumes a lot of CPU, so the rocksdb compaction may be related.

**Comment by siddontang** [comment]
Update:

The IO load in PD test machine is very busy, this may cause getting TSO too slow. I guess this is the reason for QPS 0. I change TSO save interval to 3m, and don't meet 0 QPS again. 

But:

+ We still need to improve the QPS when spitting. @disksing 
+ If the PD load is high, how can we improve the TSO performance, @huachaohuang ?
