### ISSUE TITLE
raft: raft cf size becomes huge when a store is down. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1337]
Assume we start 3 stores for loading data, but 1 is down. The raft cf size will become huge and the raft log can't be compacted until applied index - first index >= RAFT_LOG_GC_LIMIT.  
Now the RAFT_LOG_GC_LIMIT is 100000, for loading data, the average log size is 32KB, so the total raft log size will become very huge before compaction.  

Like etcd, we can reduce RAFT_LOG_GC_LIMIT to 5000, see https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L44. 
But we may still meet https://github.com/pingcap/tikv/issues/424.

**Comment by BusyJay** [comment]
It will be more practical to gc raft log according to their size rather than their count. If the pending raft log exceed haft the region size, sending all the pending raft log may perform worse than just sending a snapshot. Especially when issue #1250 is resolved.
