### ISSUE TITLE
raft: The new added peer with ConfChange is replicated after 1s later. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1342]
Let's assume the peer 1 is leader, and then:

1. 1 adds 2 with ConfChange command.
2. 1 applies the command, then sends raft Append entry to 2.
3. 2 will consider this message is stale and ignore it
4. 1 resends heartbeat after 1s later
5. 2 receives the heartbeat and the associated peer is replicated 
6. 1 sends snapshot to 2

Although the snapshot flow may be long (> 1s), it is still strange for us that we can't send snapshot immediately but must wait some time (1s) until next heartbeat. 

We can see the above case when we start 3 TiKVs at first. 

```
2016-11-23 17:40:50,323 store.rs:530 - INFO  - target peer id: 6 store_id: 4 doesn't exist, stale message MsgAppend.
2016-11-23 17:40:51,914 peer.rs:222 - INFO  - [region 2] replicate peer with id 6
2016-11-23 17:40:51,915 raft.rs:606 - INFO  - [region 2] 6 became follower at term 0
2016-11-23 17:40:51,915 raft.rs:280 - INFO  - [region 2] 6 newRaft [peers: [], term: 0, commit: 0, applied: 0, last_index: 0, last_term: 0]
```

It is better to distinguish this case with other stale message case, but if it is hard to do, we can keep the way now. 

@ngaut @BusyJay @hhkbp2

**Comment by BusyJay** [comment]
The second part of step 2 is not true. 1 applies the command and won't send the raft Append entry to 2. Because new peer's progress will be initialized to the `last_index + 1`, so peer 2 won't get a raft Append entry.

**Comment by BusyJay** [comment]
This case will be concerned only when

1. The heartbeat's interval is large;
2. The cluster just set up.

If the region has enough replicas (>= 3), a slow peer should not hurt performance.

**Comment by siddontang** [comment]
> The second part of step 2 is not true. 1 applies the command and won't send the raft Append entry to 2. Because new peer's progress will be initialized to the last_index + 1, so peer 2 won't get a raft Append entry.

Why 2 is not true? The log `target peer id: 6 store_id: 4 doesn't exist, stale message MsgAppend.` shows the message is raft Append.

> The cluster just set up.

I think this can happen in any ConfChange Add, not only in cluster set up. 

As I said before, it is better to handle this case, but I know it is not easy to do.

**Comment by BusyJay** [comment]
That's because there is additional raft entries being proposed. If the leader doesn't propose anything in 2s after adding a new peer, there should be no MsgAppend.

If it happens in the cluster setup already, this is not a problem that needs to be concerned because it won't hurt performance.

**Comment by siddontang** [comment]
Got it. 
I know this is not a bug, but the log here may confuse user sometimes. So if we can solve this, it is better, if not, we can keep it now.
