### ISSUE TITLE
feature request: configuration about rocksdb log file

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1360]
Currently rocksdb log is stored in ``data/db/LOG`` by default. 

Better add a configuration entry:

``--rocksdb-log-file``

All data & log should be stored separately, for best practise.

**Comment by siddontang** [comment]
1. we have a `--log-file` command flag for tikv, if set, we can use the same directory for rocksdb log. 
2. If `--log-file` is not set, we can use a `log-dir` for rocksdb in toml file (Btw, RocksDB needs a directory not file to create the info log).
3. If both are not set, we will let RocksDB use its default directory for info log.

**Comment by andelf** [comment]
Explicit is better than implicit.

**Comment by siddontang** [comment]
Yes, but we don't want to add another command flag like `--rocksdb-log-file`, so we can only support this in toml file.

**Comment by siddontang** [comment]
@overvenus 

We can first support `log-dir` for rocksdb in toml file.
