### ISSUE TITLE
raft: check region can work well after adding new peers

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1366]
E,g. tow peers, 1, 2 and 1 is leader. Then we add 3 and 4. But badly, 3 and 4 may have some problems like network partition, too slow. So before 3 or 4 applying the snapshot, the region can't work (proposing Write command) for this region. 

When PD adds a peer to the region, PD must ensure the peer has already added (applying the snapshot and catching up the leader's log) then it can add another new peer to the region.

**Comment by BusyJay** [comment]
You mean check whether the region can work well before adding/removing a peer?

**Comment by BusyJay** [comment]
All the peer's progress can be included in region heartbeat, so pd can make smarter choices.

**Comment by ngaut** [comment]
PD is stateless, i think a better way is to let the leader refuse the command if leader is not ready.

**Comment by BusyJay** [comment]
Leader will refuse the command of course. But pd can make smarter choices too. For example, region 1 has three peers A, B and C. And C is isolated. If pd wants to add a peer D, but leader figures out adding peer D may cause the region down for a while then it refuses to do so. Without the progress pd has no idea what's going on and just keep sending the conf change command. But if it knows that C is not in a good state, it can remove C first then add D.

**Comment by BusyJay** [comment]
Despite the fact that pd is not stateless, it doesn't require to store a state on PD. It just adds more information to pd when pd schedule conf change via heartbeat response.

**Comment by siddontang** [comment]
Btw, we must also consider removing. E,g. peer 1, 2, 3, 4, 1 is leader, and 4 is far enough behind other peers, we may not remove any peer in [1, 2, 3].
