### ISSUE TITLE
question: TiKV standalone possible

### ISSUE THREAD

**Issue by stephanbuys** [pingcap/tikv#1396]
Hi, just a quick question, is it possible to use TiKV without TiDB/PD as a drop-in etcd/consul replacement? (any plans to do something like it?)

**Comment by ngaut** [comment]
You may use TiKV and PD together, and use the RAW API(something like get/set/delete) without pay  overhead for MVCC and transaction. But it's not a replacement of etcd or consul, because there is no watch(and some others) API which etcd/consul have.

**Comment by rohitjoshi** [comment]
are these API documented? Any client example ? I am looking for distributed consistent Key-Value pair DB and like to evaluate TiKV.

**Comment by ngaut** [comment]
Hi, @rohitjoshi 
Not fully documented yet. Currently there are just three API, get/set/delete. There is a go client example. See https://github.com/pingcap/tidb/blob/master/cmd/benchraw/main.go#L39 and https://github.com/pingcap/tidb/blob/master/cmd/benchraw/main.go#L54

Hope it helps and feel free to ask any questions.

**Comment by siddontang** [comment]
We have only go client now, see https://github.com/pingcap/tidb/blob/master/store/tikv/rawkv.go

**Comment by spitfire2** [comment]
@siddontang Is go client only for tikv or it have already integrated with pd?

**Comment by Hoverbear** [comment]
@spitfire2 Currently the only client is the Go client, however you're welcome to implement or work on your own. I'm going to close this issue for now as this is an answered question. Feel free to re-open it if you think this was not addressed.
