### ISSUE TITLE
Use prefix seek API to speed up the write column family 

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#1412]
Currently we always use the raw Seek API to seek any key in the "write cf", it's quite expensive if the key doesn't exist. The prefix seek API can avoid the cost of missing keys.

**Comment by ngaut** [comment]
Maybe there will be something like prefix bloom filter, and it would be better for us to check if all of the versions of the key exists or not.

**Comment by siddontang** [comment]
+1

I think we should implement our own SliceTransform for `write cf`.

**Comment by ngaut** [comment]
Done.
