### ISSUE TITLE
raft: cache raft log to avoid getting from rocksdb 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1418]
When we append log, we can also add this raft log entries to a cache, so for following applying log, we can get the entries from cache directly, no need to get from rocksdb again. 

We should do benchmark to see whether this can improve the performance or not.

**Comment by hhkbp2** [comment]
The raft log cache is added in the branch https://github.com/pingcap/tikv/tree/hhkbp2/add-raft-log-cache.
The bench tests in a 5 cncf servers cluster (1 pd, 1 tidb, 3 tikvs) present results as

| binary | sysbench type | thread | read/write requests per second | response time average (ms) | response time min (ms) | response time max (ms) | response time 99% (ms) | cache hit rate |
| ------ | -------------- | ------ | ---------- | -------------- | ---------- | -------- | ---- | --- |
| master | insert | 128 | 4310.70 | 29.69 | 3.61 | 450.50 | 53.54 | no cache |
| master | insert | 128 | 4461.36 | 28.69 | 3.35 | 476.82 | 54.24 | no cache |
| log cache | insert | 128 | 4346.03 | 29.45 | 3.29 | 484.62 | 57.83 | ~100% |
| log cache  | insert | 128 | 4286.21 | 29.86 | 3.37 | 366.01 | 54.06 | ~ 100% |

There is no obvious difference comparing the results of master version and the log cache version.
It shows that adding a raft log cache didn't help on the performance.
