### ISSUE TITLE
refactor `single thread raftstore`

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#1427]
Currently the `raftstore` is `single thread model`, the single thread handle a lots of jobs, in some cases the single thread will be the bottle neck of whole system. So the `one coordinator thread + a worker pool model` is more reasonable, coordinator thread handle jobs like synchronous states and schedule, and the worker pool handle the actual jobs.

**Comment by siddontang** [comment]
Multi thread may introduce complexity (especially for `merge` later), and it is not easy to do it with our current architecture. 

We can first using batch for append and apply, then consider using asynchronous apply. This may be more easy to do now. (Of course, maybe the asynchronous apply is also complex and has no big performance improvement. :sob: )
