### ISSUE TITLE
question: mind sharing the reason of using TiKV to replace HBase for TiDB?

### ISSUE THREAD

**Issue by carp84** [pingcap/tikv#1448]
Didn't find any mailing list so post the question here, sorry if not the proper place (smile)

From history of TiDB we could tell that once it was built on top of HBase, but later on moving to TiKV, a newly-implemented storage based on raft and rocksdb. I tried to search for the reason on internet but failed, and it would be highly appreciated if you could share the main reason here. Thanks.

**Comment by ngaut** [comment]
There are some reasons:
We want to use raft to replicate data which HDFS can't provide the feature currently.
We don't want to depend on HDFS, it's kind of pain to deploy HDFS.
We want to avoid the overhead of GC.

**Comment by carp84** [comment]
I see, thanks for the quick reply sir! @ngaut
