### ISSUE TITLE
Another way to specify labels in tikv.toml?

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1452]
Currently we have:

```
[server]
labels = "zone=us-west-1,disk=ssd"
```

But TOML has its builtin support for table-like variables:

```
[[server.label]]
zone = "us-west-1"
[[server.label]]
disk = "ssd"
```

No need to parse_store_labels.

**Comment by huachaohuang** [comment]
Yep, but we still need to parse the labels string from the command line :(

**Comment by andelf** [comment]
For Java: ``-Dzone=us-west-1 -Ddisk=ssd``

So maybe we can:
``-Lzone=us-west-1`` or ``--label "zone=us-west-1" --label "disk=ssd"``

**Comment by c4pt0r** [comment]
Or just use $ENV?

ZONE=us-west-1 tikv-server ...

**Comment by iamxy** [comment]
Agree with @andelf, the seperated-label way is also convenient for k8s propagating labels from nodes. In a sense, it is necessary. $ENV is also a good posture.
