### ISSUE TITLE
Coprocessor is much slower when select range is not point range.

### ISSUE THREAD

**Issue by coocood** [pingcap/tikv#1467]
I ran a benchmark on a 10000 records table.
query like
```
select * from t where id = 1 or id = 2
```
takes 800us, but query like
```
select * from t where id > 0 and id <=2
```
takes 2ms.

Both return 2 records, the difference is that first select ranges are point range, but the second select is not.

**Comment by zhangjinpeng1987** [comment]
The overhead for seek a key in lock cf is not trivial, because there are a lot of tombstones in lock cf.
