### ISSUE TITLE
Need a version upgrade of rocksdb

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1474]
Hi,

The CI build fails due to the incompatible versions between rust-rocksdb and rocksdb.

The dependency of rust-rocksdb has been updated to https://github.com/pingcap/tikv/blob/master/Cargo.lock#L528, which contains the codes for sst file ingestion.
But the rocksdb 4.13.5 version which is used in CI build doesn't have these codes.

**Comment by siddontang** [comment]
Hi @hhkbp2 

Can you fix it? Now we can use https://github.com/facebook/rocksdb/releases/tag/v5.0.1 directly.
