### ISSUE TITLE
Log format is inconsistent with tidb/pd

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1475]
If using a different log format is OK.
The issue is:

https://github.com/pingcap/tikv/blob/67c8193314e13e9291a670f52c6a300242d159ad/src/util/file_log.rs#L150

`{:5}` for log level alignment is useless because we put filename & line before log level.

**Comment by siddontang** [comment]
Can we close it now @andelf ?

**Comment by andelf** [comment]
fixed by #1476
