### ISSUE TITLE
rocksdb: support compaction_readahead_size for spinning disk 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1507]
As RocksDB doc says, we should set this value to at least 2MB for spinning disk.

**Comment by andelf** [comment]
#1510  introduces first underscore splitted option in tikv.toml . 🥇

**Comment by BusyJay** [comment]
Why reopen the issue?

**Comment by siddontang** [comment]
We should use `compaction-readahead-size` in toml, not `compaction_readahead_size`.
