### ISSUE TITLE
message between TiDB and TiKV will not validate cluster ID

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/tikv#1516]
Suppose we have two cluster 1 and 2, we take a store offline from cluster 1, then cleanup data in the store and put it to cluster 2, this store will have the same address as before.
If TiDB has a region cache of the store before the store is taken offline from cluster 1, then TiDB will try to send request to that store in cluster 2 with the same address later, the request may or may not fail depends on if it can pass the validation.
For now, we validate the store id, region id and region epoch, seems not very possible that all these information are the same, but it may have some risks.

GRPC may solve this problem if we use some kind of certification.

**Comment by ngaut** [comment]
Done.
