### ISSUE TITLE
pd: support "http://127.0.0.1:2379" scheme 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1536]
Refer https://github.com/pingcap/docs/issues/86

**Comment by mrmiywj** [comment]
I will work on it.

**Comment by overvenus** [comment]
That's cool, thanks!?

Sent from my iPhone

On 19 Jan 2017, at 12:07, Ivan.Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


I will work on it.

-
