### ISSUE TITLE
tikv cannot restart and panic because pd thought it's registered

### ISSUE THREAD

**Issue by kaiwu** [pingcap/tikv#1542]
Not sure this issue belongs to `pingcap/pd` or `pingcap/tikv`, 
and this is pretty close to #1332 so here it is : 

## scenario 

1. start pd cluster
2. start kv cluster
3. stop kv cluster
4. restart kv cluster

## what happens

1. kvs are up in step 2
2. kvs are down in step 4, with panic 

## logs from pd

```
2017/01/20 11:59:32 command.go:302: [info] put store ok - id:1 address:"10.32.0.8:20160"
2017/01/20 12:00:06 command.go:302: [info] put store ok - id:4 address:"10.32.0.6:20160"
2017/01/20 12:00:07 command.go:302: [info] put store ok - id:5 address:"10.32.0.7:20160"
2017/01/20 12:00:32 operator.go:156: [info] {Name:add_peer RegionID:2 ChangePeer:change_type:AddNode peer:<id:6 store_id:5 > } {Region:id:2 start_key:"" end_key:"" region_epoch:<conf_ver:1 version:1 > peers:<id:3 store_id:1 >  Leader:id:3 store_id:1  DownPeers:[] PendingPeers:[]}
2017/01/20 12:02:17 conn.go:109: [error] handle request header:<uuid:"\264\327\226<O\213N\037\240\374\267\247@\252\317\363" cluster_id:6377526301049031220 > cmd_type:PutStore put_store:<store:<id:7 address:"10.32.0.8:20160" > >  err /home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/cluster.go:328: duplicated store address: id:7 address:"10.32.0.8:20160" , already registered by id:1 address:"10.32.0.8:20160"
/home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/command.go:299:
2017/01/20 12:02:33 conn.go:109: [error] handle request header:<uuid:"\367Z#W\215.L\252\200\310/\"\333'\322S" cluster_id:6377526301049031220 > cmd_type:PutStore put_store:<store:<id:8 address:"10.32.0.8:20160" > >  err /home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/cluster.go:328: duplicated store address: id:8 address:"10.32.0.8:20160" , already registered by id:1 address:"10.32.0.8:20160"
/home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/command.go:299:
2017/01/20 12:02:49 conn.go:109: [error] handle request header:<uuid:"\021\225\3366\335JN\230\225v\370!S?>\367" cluster_id:6377526301049031220 > cmd_type:PutStore put_store:<store:<id:9 address:"10.32.0.8:20160" > >  err /home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/cluster.go:328: duplicated store address: id:9 address:"10.32.0.8:20160" , already registered by id:1 address:"10.32.0.8:20160"
/home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/command.go:299:
2017/01/20 12:03:04 conn.go:109: [error] handle request header:<uuid:"\236\220\333\254\330qB\341\210k\023I\347_\356\211" cluster_id:6377526301049031220 > cmd_type:PutStore put_store:<store:<id:10 address:"10.32.0.8:20160" > >  err /home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/cluster.go:328: duplicated store address: id:10 address:"10.32.0.8:20160" , already registered by id:1 address:"10.32.0.8:20160"
/home/jenkins/workspace/BUILD_PD_WORKFLOW/go/src/github.com/pingcap/pd/server/command.go:299:
```

##  caveat

used in docker 1.13 environment, with following tweaks, so that tikv can be started using 
`docker service create` through multi-host

### Dockerfile
```
FROM tikv:pingcap

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
```

### docker-entrypoint.sh 

```
#!/bin/sh
set -eo pipefail

CONTAINER_IP_LINE=`cat /proc/self/cgroup | grep 'docker' | sed 's/^.*\///' | tail -n1 | cut -c -12`
CONTAINER_IP=`cat /etc/hosts | grep $CONTAINER_IP_LINE  | grep -o '[0-9]\+[.][0-9]\+[.][0-9]\+[.][0-9]\+'`

exec /tikv-server --addr="0.0.0.0:20160" --advertise-addr="$CONTAINER_IP:20160" "$@"
```

## question

docker and `docker service` makes it common for containers to come and go, looks like tikvs cannot be properly recognized by pd after they are reborn, is there any approach that tikv let known it's dying so that pd update the store info ? or what's the best procedure for this ?

## pd version
```
2017/01/20 11:38:32 util.go:49: [info] Welcome to Placement Driver (PD).
2017/01/20 11:38:32 util.go:50: [info] Version:
2017/01/20 11:38:32 util.go:51: [info] Git Commit Hash: 67fbe33b031d6d73cde81598cd675f4b852de872
2017/01/20 11:38:32 util.go:52: [info] UTC Build Time:  2016-12-29 11:35:57
```

## tikv version and trace
```
2017-01-20 12:39:44,339 mod.rs:397 - INFO  - Welcome to TiKV.
2017-01-20 12:39:44,339 mod.rs:398 - INFO  - Version:
2017-01-20 12:39:44,339 mod.rs:399 - INFO  - Git Commit Hash: 3328d6ac5470fbd2846c0a2e449855eb2cffee89
2017-01-20 12:39:44,339 mod.rs:400 - INFO  - UTC Build Time:  2016-12-29 12:24:27

..............

ERROR - thread 'main' panicked 'called `Result::unwrap()` on an `Err` value: Pd(Other(StringError("duplicated store address: id:11 address:\"10.32.0.6:20160\" , already registered by id:4 address:\"10.32.0.6:20160\" ")))' at "../src/libcore/result.rs:788"
stack backtrace:
   0:     0x7fc3dfeea94e - backtrace::backtrace::libunwind::trace
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace<closure>
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x7fc3dfeeb048 - backtrace::capture::{{impl}}::new
                        at /home/jenkins/workspace/BUILD_TIKV_WORKFLOW/go/src/github.com/pingcap/tikv/target/release/build/backtrace-3bc1ff360ebb00cb/out/capture.rs:79
   2:     0x7fc3dfa9515f - tikv::util::panic_hook::set_exit_hook::{{closure}}
                        at /home/jenkins/workspace/BUILD_TIKV_WORKFLOW/go/src/github.com/pingcap/tikv/src/util/panic_hook.rs:84
   3:     0x7fc3e003c29c - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   4:     0x7fc3e003c111 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   5:     0x7fc3e003c03a - std::panicking::begin_panic_fmt::h20f5943904e5791d
   6:     0x7fc3e003bfae - rust_begin_unwind
   7:     0x7fc3e007974f - core::panicking::panic_fmt::h19323e466869c656
   8:     0x7fc3df83497d - {{inlined-root}}::unwrap_failed<tikv::server::errors::Error>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
   9:     0x7fc3df8f2a3d - {{inlined-root}}::unwrap<(),tikv::server::errors::Error>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:726
                         - tikv_server::build_raftkv
                        at /home/jenkins/workspace/BUILD_TIKV_WORKFLOW/go/src/github.com/pingcap/tikv/src/bin/tikv-server.rs:507
  10:     0x7fc3df8f6eff - tikv_server::run_raft_server
                        at /home/jenkins/workspace/BUILD_TIKV_WORKFLOW/go/src/github.com/pingcap/tikv/src/bin/tikv-server.rs:652
  11:     0x7fc3df9033a4 - tikv_server::main
                        at /home/jenkins/workspace/BUILD_TIKV_WORKFLOW/go/src/github.com/pingcap/tikv/src/bin/tikv-server.rs:780
  12:     0x7fc3e003bf28 - std::panicking::try::call::h5df3ac2979db3c90
  13:     0x7fc3e0044666 - __rust_maybe_catch_panic
  14:     0x7fc3e003b04e - std::rt::lang_start::hfe9ab243c60ffb9b
  15:     0x7fc3deac1874 - __libc_start_main
  16:     0x7fc3df7c4960 - <unknown>
  17:                0x0 - <unknown>
```

**Comment by kaiwu** [comment]
@huachaohuang , yes you are right, as i was doing it with docker

1. when docker stops/starts the same tikv container, its volume is not removed, tikv won't be refused by pd and tikv restarts without panic
2. when docker stops/removes/restarts the tikv container, its volume is removed, tikv container starts fresh (from empty) but the container ip might be reused, so that pd refuses this tikv so that tikv panics
3. in the case of `docker service create/rm` it is essentially the same with 2

now i see that pd uses tikv's ip as unique handle of a specific store, if tikv's providing the same ip, it's data and `store id` shall be consistent.

need some time to figure how to get this around in docker

**Comment by tennix** [comment]
@kaiwu As you stated in the second case, tikv listening address`ip:port` might be changed when the container is recreated, but tikv is not stopped normally, the old `ip:port` registered in pd would not be deleted, so this `ip:port` can't be used for new tikv store. So in order to make it work, you can either use pd api to remove tikv normally or assign new `ip:port` pair to new tikv store.

**Comment by kaiwu** [comment]
may i ask 2 more questions related

1. does PD hold any TTL ? i.e. when a specific tikv is gone for a period, its store is automatically removed, as i check using pd-ctl, it seems the store info (`store id` and `kv ip`) remains in PD and cannot be `store delete` if the store has any `region` deployed 

2. pd-ctl is weak, any plan to improve pd-ctl so that some manual reallocate can be done?

**Comment by siddontang** [comment]
Thanks @kaiwu 

1. You must explicitly remove a gone TiKV. But it the TiKV is gone for a long time, PD will do balance moving the peer of the region it the TiKV to another TiKV.
2. `pd-ctl` is weak, because PD has not supplied some APIs, we will improve this. Btw, what is `manual reallocate` for?  Moving a replica of the region to another TiKV?

**Comment by kaiwu** [comment]
@tennix , i was thinking exactly as you put `tikv is not stopped **normally**`, but it seems when tikv is stopped by docker, there is no way tikv could tell pd that it is gone so its registered status remain unchanged in PD, what's exactly tikv need to do for this graceful behavior ?

**Comment by siddontang** [comment]
@kaiwu 

PD will check the TiKV is down and does balance for the regions which replica is in the down TiKV later.

**Comment by tennix** [comment]
@kaiwu yep, you cannot rely on scheduling strategy of orchestration tools like swarm and kubernetes for stateful service. We're working on tidb-operator which is inspired by [etcd-operator](https://github.com/coreos/etcd-operator) to handle such problem on kubernetes.

**Comment by kaiwu** [comment]
@siddontang , i see. thanks a lot

btw, does every tikv holds **complete** data ? or is it the case that each tikv wise, it only holds partially the entire data, and the partials is scattered with many replicas ?

i was thinking a use case that only one or a few tikv mount persistent volume, the rest could be launched using `docker service create` and they each uses its own anonymous volume, to save
some devops effort

we are serious deploying tidb/tikv/pd into docker production ...  ;-)

**Comment by siddontang** [comment]
@kaiwu 

Of course, one TiKV can't hold the full data. 

For your case, I have no idea and think it can't work now. /cc @tennix @iamxy

**Comment by kaiwu** [comment]
understood, lessons learnt, thanks all for your time, i close it for now.

**Comment by siddontang** [comment]
Thanks @kaiwu, please feel free to contact us if you have any problem.
