### ISSUE TITLE
metric efficiency may be not proper

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1555]
Now we use an efficiency histogram metric for scan, but it is not proper with `histogram_quantile`.
I think un-efficiency is better with `histogram_quantile`, and we can know the worst un-efficiency with 99.99% quantile.

**Comment by BusyJay** [comment]
I think change the φ to 0.0001 should get what you want.

**Comment by siddontang** [comment]
using 0.0001 can't work, assume we have 10000 metrics, 0.0001 only shows 1 metric, it makes no sense.

**Comment by coocood** [comment]
I think use two counters is better, one for scanned, the other for skipped.
This can better reflect overall system efficiency.

**Comment by BusyJay** [comment]
> using 0.0001 can't work, assume we have 10000 metrics, 0.0001 only shows 1 metric, it makes no sense.

If I understand it correctly, `histogram_quantile(0.0001, buckets) = 0.8` means that the count of queries whose efficiency is less than or equal to 0.8 is about 0.01% * counts of buckets. So the count of queries whose efficiency is larger than 0.8 is about 99.99% * count of buckets. So how's that different from what you are expecting?

> I think use two counters is better

I don't think so. You can't tell if the skipped keys are just from a few queries or from all the queries.

**Comment by siddontang** [comment]
E.g, simple for 1% quantile, 1 metric is 0.1, and 99 metrics are 0.2, so histogram_quantile 1% here is 0.1, and other 99% is 0.2, but 0.2 is also not efficiency, how can we know this? Use another 2% quantile to check?

If we have two scans, one scans 10 but skips 9, and the other scans 10000 but skips 9999, the efficiencies here are all 0.1, how can we distinguish them? Maybe two counter is better here. 

For the too frequent query, we can use hot regions, log, and memory statistics to know it later.
