### ISSUE TITLE
tune raft cf with Rocksdb memtable_insert_with_hint_prefix_extractor

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1603]
Although we may have many regions in one store, the alive region number at same time may be small. The raft log key format for the region looks `prefix|region_id|log_index`, the log index is increased monotonically. For raft region meta key, it will be updated every time. 

The scenario is suitable as memtable_insert_with_hint_prefix_extractor says, we can do a benchmark .

**Comment by zhangjinpeng1987** [comment]
Since the alive region number at same time is small, the hint will not efficient.

**Comment by siddontang** [comment]
Although small, the write speed is high, we should do some benchmark to check whether this can improve performance or not.

**Comment by zhangjinpeng1987** [comment]
`Although small, the write speed is high`
What is this means? 
In normal cases memtable(skip-list) inserting will use binary search to find the position key should insert into, if `memtable_insert_with_hint_prefix_extractor` is used, first step is to find a hint position for the same prefix(in our case the prefix is `region_id`), and then walk the list step by step to find the final position key should insert into. If the number of hint positions is too small, use `memtable_insert_with_hint_prefix_extractor` may even worse than the normal insert.

**Comment by siddontang** [comment]
Assume the write speed is high for a region, if a region appends more logs like 50 at same time, I guess the following 49 insertion may be more fast.

> walk the list step by step to find the final position key should insert into

I see the comment here:

```
// The option is best suited for workloads where keys will likely to insert
// to a location close the the last inserted key with the same prefix.
```

Seem that the hint is for the laster inserted key?
