### ISSUE TITLE
Does TiKV support multi disks?

### ISSUE THREAD

**Issue by gejigeji** [pingcap/tikv#1612]
In help info :
./bin/tikv-server -h
    -s, --store /tmp/tikv/store

If I have multi disks, how can I use them all ?
/dev/sdb1             1.8T  851M  1.7T   1% /data1
/dev/sdc1             1.8T  196M  1.7T   1% /data2
/dev/sdd1             1.8T  196M  1.7T   1% /data3
/dev/sde1             1.8T  196M  1.7T   1% /data4
/dev/sdf1             1.8T  196M  1.7T   1% /data5
/dev/sdg1             1.8T  196M  1.7T   1% /data6
/dev/sdh1             1.8T  196M  1.7T   1% /data7
/dev/sdi1             1.8T  196M  1.7T   1% /data8
/dev/sdj1             1.8T  196M  1.7T   1% /data9
/dev/sdk1             1.8T  196M  1.7T   1% /data10
/dev/sdl1             1.8T  196M  1.7T   1% /data11
/dev/sdm1             1.8T  237M  1.7T   1% /data12

**Comment by siddontang** [comment]
Hi @gejigeji 

TiKV doesn't support multi disks, you can start one TiKV on one disk instead.
