### ISSUE TITLE
separate local lease read from raftstore thread 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1617]
Now for local lease read, we will send a command to the raftstore thread and then get the snapshot,  this may be delayed by previous write command. We can get the snapshot in scheduler directly if we can make sure the current leader is still leader and is still in lease. 

I think we can move the current leader lease logic from Peer in raftstore to scheduler, and update the lease lease in the callback when the raft log applied. We should also send other infos like region range, epoch in the callback from raftstore to scheduler too. 

We may need to add a new Handler to the raftstore, if the peer state changes (leader steps down, follower becomes leader) or a leader transfer happens, raftstore should also use the handler to notify scheduler. 

Of course, we should consider any corner case too.

**Comment by zhangjinpeng1987** [comment]
We need use a separate thread to service get snapshot, not just move to scheduler, because corprocessors just know `Engine` and know nothing about scheduler.
