### ISSUE TITLE
Improve tick acceleration for campaign right after split

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1639]
Currently the impl will accelerate ticks for the leader right after it applies a region split action to let campaign fast. A follower use randomized election timeout, whose value is of the range [election_timeout, 2 * election_timeout - 1), to trigger a new campaign. However the config of tick acceleration above if election_timeout - 1. So a leader which did spliting may have to wait election_timeout to start a new campaign in the worst case. This could be improved further.

**Comment by ngaut** [comment]
I think we should reduce [election_timeout, 2 * election_timeout - 1) to [election_timeout, election_timeout + 3 seconds ), so we can elect leader faster.

**Comment by hhkbp2** [comment]
@ngaut I am not sure whether it's a good idea to modify the randomization of this range for triggering a new campaign. This timeout value is designed and measured in the current range for the best activity and performance, although I do remember where these details are recorded.

We would achieve this improvement simply by adjusting the ticks acceleration number to `randomized_election_timeout - 1`, or just `2 * election_timeout - 1`.

**Comment by hhkbp2** [comment]
This improvement will fix this issue https://github.com/pingcap/tidb/issues/2695
