### ISSUE TITLE
metrics: rocksdb statistics should update at metric-interval

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1641]
https://github.com/pingcap/tikv/pull/1638

https://github.com/pingcap/tikv/commit/4a1582396f9b804f12d066cd23d371b0888534ca

Should get_and_reset_statistics_ticker_count() just before pushing metrics to pushgateway( or during a /metrics request in the near future ).

**Comment by siddontang** [comment]
any update? /cc @zhangjinpeng1987 @andelf
