### ISSUE TITLE
#[feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by biolee** [pingcap/tikv#1671]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.15.1 (021bd294c 2017-02-08)

2. What operating system and processor architecture are you using?
mac 10.12.3 (16D32)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```bash
wget https://github.com/pingcap/tikv/archive/rc2.zip
unzip rc2.zip
#install prerequests
cd tikv-rc2
make
```

4. What did you expect to see?
compiled file in bin

5. What did you see instead?

error[E0554]: #[feature] may not be used on the stable release channel
  --> /Users/liyanan/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/321b907/src/lib.rs:16:32
   |
16 | #![cfg_attr(feature="nightly", feature(integer_atomics))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `prometheus`.

**Comment by siddontang** [comment]
@overvenus 

Seem that we can't compile prometheus with stable now. Please fix it.

**Comment by siddontang** [comment]
Hi @biolee 

TiKV can only be compiled with rust nightly version, we use nightly-2017-02-12.

**Comment by overvenus** [comment]
Rust-prometheus can be compiled with stable rust. However, TiKV uses rust-prometheus's `nightly` feature, which will enable `feature(integer_atomics)` and that causes error[E0554].

## How to fix?

```
# Install RocksDB v5.1.2
# Install [rustup.rs](https://github.com/rust-lang-nursery/rustup.rs).
cd tikv
rustup override set nightly-2017-02-12
make
```

-------------

```
➜  rust-prometheus git:(master) rustc --version
rustc 1.15.1 (021bd294c 2017-02-08)
➜  rust-prometheus git:(master) cargo build
   Compiling protobuf v1.2.2
   Compiling quick-error v0.2.2
   Compiling lazy_static v0.2.4
   Compiling cfg-if v0.1.0
   Compiling fnv v1.0.5
   Compiling prometheus v0.2.9 (file:///home/neil/repo/rust-prometheus)
    Finished debug [unoptimized + debuginfo] target(s) in 50.15 secs
```

**Comment by huafengw** [comment]
Can this issue be fixed without additional `rustup override`?

**Comment by siddontang** [comment]
@huafengw 

You can install nightly rust version with rustup by default, so you can ignore override.

**Comment by PHILO-HE** [comment]
For someone who cannot use rustup to install rust, please try to use a installation package of Nightly version at https://www.rust-lang.org/en-US/other-installers.html.

**Comment by tomasen** [comment]
README should add this information(`rustup override set nightly`) under the "Configuring your Rust toolchain" section
