### ISSUE TITLE
I can't find performance test result in home page. 

### ISSUE THREAD

**Issue by wangxingge** [pingcap/tikv#1681]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
N/A

2. What operating system and processor architecture are you using?
Centos7, 5200

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

I can't find performance test result in home page
4. What did you expect to see?
I need performance test result.

5. What did you see instead?
N/A

**Comment by siddontang** [comment]
Hi @wangxingge 

We will release the performance report after releasing GA.
