### ISSUE TITLE
unify how to get integer config with/without unit

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1687]
For #1679

Now for a integer, the get_toml_int function can handle common integer and human readable string. This can cause confused sometimes. E.g, if we name a config `wal_ttl_secs` and set 3600 to it, but later we want to use "1h" instead, sadly, the unit for "1h" is milliseconds, so we will get 3600000 for the config. 

To prohibit this chaos, we should separate the integer retrieving with/without uint strictly. For some integer configs like counter, we can't use human readable string, only integer is supported, for other integers which have unit like time(ms), size (byte), we must use human readable string. 

/cc @BusyJay

**Comment by aya** [comment]
What about adding an optional parameter to the get_toml_int function that would define the unit expected in the configuration ?
- 'int' would accept only integer without conversion and throw an error on human readable strings
- 'time' would accept only time related human readable strings and throw an error on strings without unit
- 'size' would accept only size related human readable strings and throw an error on strings without unit
- 's' would convert integer to seconds instead of milliseconds and accept only time related human readable strings
- 'mb' would convert integer to mbytes instead of bytes and accept only size related human readable strings
- '' would keep same behaviour as today

**Comment by siddontang** [comment]
Thanks @aya 

I think:

1. If the configuration is for time (ms, s, m, h, d, m, y), size (b, kb, mb, gb, tp, pb), we must use human readable parsing. (Do we need to support parsing 0 here?)
2. We can make unit more simple, one unit for one type, so time is "ms", and size is "b". 
3. Supply get_toml_int, get_toml_duration, get_toml_size 
4. Check every configurations and use corresponding parsing function.

This may be a huge refactor. 

/cc @BusyJay

**Comment by siddontang** [comment]
We should take care of `stats-dump-period-sec` and `wal-ttl-seconds`, do we need to rename them and use human readable parsing, or just allow using int parsing for them.

**Comment by aya** [comment]
1. I agree and 0 should be a valid value indeed. What about minutes (m) and months (m) ?
2. Yes, but we are not used to speak in milliseconds and bytes, more in seconds and mbytes, so what about configurable default ? Or we should finally reject values without unit ? 
3. I agree.
4. Adding an optional parameter to the get_toml_int function would allow us to do it in two steps, keeping compatibility with the existing behaviour, then updating configurations to use strict checking. get_toml_int could call get_toml_duration or get_toml_size following the value of this parameter. Once all configurations updated, we could remove this option is not needed anymore.

I think we should rename `stats-dump-period-sec` and `wal-ttl-seconds` and use human readable strings as for all other time related configurations.

**Comment by siddontang** [comment]
Hi @aya

> Yes, but we are not used to speak in milliseconds and bytes, more in seconds and mbytes, so what about configurable default ? 

I prefer using one unit for one type, so for a time config, E.g "tick-interval", we can use "tick-interval=10s" or "tick-interval=10000ms", both are ok, and we will get 10000 (unit is ms) after parsing. 

> Or we should finally reject values without unit ?

I think yes.

**Comment by aya** [comment]
> What about minutes (m) and months (m) ?
Maybe m or mn for minute and mo for month ?

**Comment by siddontang** [comment]
> Maybe m or mn for minute and mo for month ?

IMO, we don't need to support month, maybe day is big enough for the time configuration. :-)

**Comment by siddontang** [comment]
> Or we should finally reject values without unit ?

I think for time we must use unit later, but for size, if no unit, we can use byte directly, so "1KB" is 1024 bytes, and 1024 is also 1024 bytes, how do you think?  /cc @aya @BusyJay

**Comment by siddontang** [comment]
Hi @aya , any update? 

I think we can first introduce `get_toml_duration` to refactor all time configuration. The function will return milliseconds (most of our time configs use milliseconds). For RocksDB, if we want to use seconds, we should divide with 1000 explicitly.
