### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by woshixiaok** [pingcap/tikv#1689]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

rustc 1.17.0-nightly
2. What operating system and processor architecture are you using?
centos 7.2

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

  Compiling regex-syntax v0.3.1
   Compiling backtrace v0.2.3
   Compiling void v1.0.2
   Compiling matches v0.1.2
   Compiling getopts v0.2.14
   Compiling unicode-width v0.1.3
   Compiling language-tags v0.2.2
   Compiling threadpool v1.3.0
   Compiling unicode-normalization v0.1.2
   Compiling libc v0.2.16
   Compiling rand v0.3.14
   Compiling log v0.3.6
   Compiling bitflags v0.3.3
   Compiling num-traits v0.1.32
   Compiling num-integer v0.1.32
   Compiling vec_map v0.6.0
   Compiling byteorder v0.5.1
   Compiling semver v0.1.20
   Compiling rustc_version v0.1.7
   Compiling strsim v0.5.1
   Compiling traitobject v0.0.1
   Compiling lazy_static v0.1.16
   Compiling crc v1.2.0
   Compiling num_cpus v0.2.13
   Compiling httparse v1.1.2
   Compiling protobuf v1.2.1
   Compiling utf8-ranges v0.1.3
   Compiling winapi v0.2.8
   Compiling gcc v0.3.35
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.3
   Compiling uuid v0.3.1
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling dbghelp-sys v0.2.0
   Compiling ws2_32-sys v0.2.1
   Compiling unicode-bidi v0.2.3
   Compiling idna v0.1.0
   Compiling url v1.2.0
   Compiling libc v0.1.12
   Compiling time v0.1.35
   Compiling tikv v0.0.1 (file:///root/tikv-master)
   Compiling cookie v0.2.5
   Compiling bytes v0.3.0
   Compiling cfg-if v0.1.0
   Compiling nix v0.6.0
   Compiling mime v0.2.2
   Compiling ansi_term v0.9.0
   Compiling sys-info v0.4.1
   Compiling lazy_static v0.2.1
   Compiling net2 v0.2.23
   Compiling miow v0.1.2
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#99f4edd6)
   Compiling tipb v0.0.1 (https://github.com/pingcap/tipb.git#979fbca7)
   Compiling bitflags v0.7.0
   Compiling slab v0.1.3
   Compiling rustc-demangle v0.1.2
   Compiling kernel32-sys v0.1.4
   Compiling tempdir v0.3.4
   Compiling rocksdb v0.3.0 (https://github.com/pingcap/rust-rocksdb.git#99f4edd6)
   Compiling term_size v0.2.1
   Compiling rustc-serialize v0.3.19
   Compiling num-complex v0.1.32
   Compiling toml v0.1.28
   Compiling num-bigint v0.1.32
   Compiling num-rational v0.1.32
   Compiling typeable v0.1.2
   Compiling hpack v0.2.0
   Compiling solicit v0.4.4
   Compiling unicode-segmentation v0.1.2
   Compiling clap v2.14.0
   Compiling kvproto v0.0.1 (https://github.com/pingcap/kvproto#8d40f322)
   Compiling nix v0.5.0-pre (https://github.com/carllerche/nix-rust?rev=c4257f8a76#c4257f8a)
error[E0591]: `extern "C" fn(*mut std::boxed::Box<std::ops::FnMut() -> isize>) -> i32 {sched::clone::callback}` is zero-sized and can't be transmuted to `*const extern "C" fn(*const std::boxed::Box<std::ops::FnMut() -> isize>) -> i32`
   --> /root/.cargo/git/checkouts/nix-rust-d606302ceff0dca5/c4257f8/src/sched.rs:190:20
    |
190 |         ffi::clone(mem::transmute(callback), ptr as *mut c_void, flags, &mut cb)
    |                    ^^^^^^^^^^^^^^
    |
note: cast with `as` to a pointer instead
   --> /root/.cargo/git/checkouts/nix-rust-d606302ceff0dca5/c4257f8/src/sched.rs:190:20
    |
190 |         ffi::clone(mem::transmute(callback), ptr as *mut c_void, flags, &mut cb)
    |                    ^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `nix`.

**Comment by siddontang** [comment]
Hi @woshixiaok 

can you show me the full output of `rustc -V`, now we use `nightly-2017-02-12` to build TiKV.

**Comment by woshixiaok** [comment]
rustc 1.17.0-nightly (0aeb9c129 2017-03-15)

**Comment by siddontang** [comment]
Hi @woshixiaok , You can use `rustup override set nightly-2017-02-12` then compile TiKV again.

**Comment by siddontang** [comment]
We will support mio 0.6 later, at that time, we can use newer rust version, but now we can't :sob:

**Comment by woshixiaok** [comment]
thanks, when I rustup override set nightly-2017-02-12, then compile TiKV success
