### ISSUE TITLE
Make storage pluggable

### ISSUE THREAD

**Issue by theduke** [pingcap/tikv#1693]
I've only briefly scanned the code,

but would it be feasible to make the storage backend pluggable via traits?

This would allow someone to use all the Raft logic with their storage of choice, for example lmdb, or my specific use case for this, https://github.com/PumpkinDB/PumpkinDB.

**Comment by siddontang** [comment]
Hi @theduke 

Now we heavily depend on RocksDB and have no plan to support other engine. But it is worth trying later.

**Comment by theduke** [comment]
Thanks for clarifying.

I guess we can close this issue for now.

**Comment by tejasvi** [comment]
Tracked in #6402
