### ISSUE TITLE
tests:test_server_quick_election_after_split failed in CI

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tikv#1729]
Hi,all,
    ` raftstore::test_split_region::test_server_quick_election_after_split` failed some time in CI with the following details:

```
thread 'raftstore::test_split_region::test_server_quick_election_after_split' panicked at 'assertion failed: new_leader.is_some()', tests/raftstore/test_split_region.rs:576
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: tikv::util::panic_hook::track_hook::{{closure}}
   1: <std::thread::local::LocalKey<T>>::with
   2: tikv::util::panic_hook::track_hook
   3: core::ops::Fn::call
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: tests::raftstore::test_split_region::test_quick_election_after_split
   7: tests::raftstore::test_split_region::test_server_quick_election_after_split
   8: <F as test::FnBox<T>>::call_box
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: <F as alloc::boxed::FnBox<A>>::call_box
  14: std::sys::imp::thread::Thread::new::thread_start
  15: _pthread_body
  16: _pthread_start
test raftstore::test_split_region::test_server_quick_election_after_split ... FAILED
```

@BusyJay @zhangjinpeng1987 @hhkbp2 PTAL

**Comment by hhkbp2** [comment]
The logs are needed to debug. Have you recorded all the logs of this failed test case? @AndreMouche

**Comment by AndreMouche** [comment]
I copied this from CI, it seems had already involved all messages caused by this case. @hhkbp2

**Comment by hhkbp2** [comment]
@AndreMouche 
There should be a long log at the end of the CI output, where the log DEBUG level is enabled. 
Do you have this failed CI job link? Post it here so that we could take a look at it.

**Comment by siddontang** [comment]
any update? @AndreMouche @hhkbp2

**Comment by hhkbp2** [comment]
The detailed logs for the failed test is lost so that it's no way to analyze the scenario. Maybe we could get the logs and figure it out if it fails later in the future. @AndreMouche Could we close this issue?

**Comment by siddontang** [comment]
do we fix it now? @AndreMouche

**Comment by AndreMouche** [comment]
not yet @siddontang . It seems hard to  reappear, I prefer to take @hhkbp2 's advice to close this issue now and figure it out if it fails later in the future?
