### ISSUE TITLE
proposal: use unwrap crate

### ISSUE THREAD

**Issue by andelf** [pingcap/tikv#1746]
``.unwrap_or_else(|err| exit_with_err(format!("{:?}", err)))`` is ugly.

ref: https://crates.io/crates/unwrap

**Comment by BusyJay** [comment]
They are not the same. Exit_with_err wants to exit the process without printing out the stacks. A similar macro can be added to TiKV though.

/cc @ngaut @siddontang

**Comment by siddontang** [comment]
Here we want to exit directly, so the crate is not suitable here. 

Let's use `unwrap_or_else` now.
