### ISSUE TITLE
consider renaming `--store` to `--data-dir`

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1757]
Now we use `--store`to save TiKV data, but it makes more sense to use `--data-dir` for a user. Btw, TiDB use `--store` to identify which store (tikv, goleveldb, etc...) is used, if a user sees our documents like https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md#standalone-cluster-deployment, he may be confused that the two `--store` have different meanings.

**Comment by andelf** [comment]
fixed by #1803
