### ISSUE TITLE
bootstrap may leave unexpected region data in storage.

### ISSUE THREAD

**Issue by disksing** [pingcap/tikv#1761]
When bootstrap cluster, we 1) build the first region, save it, 2) send bootstrap request to PD. If server panics after step 1, invalid region data will be left. Refer https://github.com/pingcap/tikv/blob/master/src/server/node.rs#L124

**Comment by siddontang** [comment]
Maybe we can:

1. prepare the first region in RocksDB
2. Bootstrap the first region in PD
3. commit the first region in RocksDB
