### ISSUE TITLE
snapshot corruption handling

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1804]
TODO:

1. validate that a snapshot is not corrupted before it's sent (For v1, v2)
2. delete a corrupted existing snapshot when receiving (For v1, v2)

**Comment by siddontang** [comment]
any update? @hhkbp2

**Comment by hhkbp2** [comment]
@siddontang I don't think these validations are appropriate because the region max size is about to be increased. It gonna take a long time to do the CRC calculation for a big sst file.
