### ISSUE TITLE
consider using vector instead of hashmap in raft Peer

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#1843]
Now we use many HashMap in raft Peer, like peer cache,  peer heartbeats and node prs. In most of the case, the hash map is very small (we can guarantee that the size is about the max replica number 3 or a little larger 4). So we can use vector instead, for peer cache, we can move the region peer cache to the peer cache itself, no need to maintain a total peer cache in store. 

```
#[bench]
fn bench_vec_find_1(b: &mut Bencher) {
    let v = vec![(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)];
    b.iter(||v.iter().find(|&x| x.0 == 1).unwrap())
}

#[bench]
fn bench_vec_find_5(b: &mut Bencher) {
    let v = vec![(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)];
    b.iter(||v.iter().find(|&x| x.0 == 5).unwrap())
}

#[bench]
fn bench_ordermap_find_1(b :&mut Bencher) {
    let m = ordermap!{1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5};
    b.iter(||m[&1])
}

#[bench]
fn bench_ordermap_find_5(b :&mut Bencher) {
    let m = ordermap!{1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5};
    b.iter(||m[&5])
}

#[bench]
fn bench_hashmap_find_1(b :&mut Bencher) {
    let mut m = HashMap::new();
    m.insert(1, 1);
    m.insert(2, 2);
    m.insert(3, 3);
    m.insert(4, 4);
    m.insert(5, 5);    
    b.iter(||m[&1])
}

#[bench]
fn bench_hashmap_find_5(b :&mut Bencher) {
    let mut m = HashMap::new();
    m.insert(1, 1);
    m.insert(2, 2);
    m.insert(3, 3);
    m.insert(4, 4);
    m.insert(5, 5);    
    b.iter(||m[&5])
}
```
```
test tests::bench_hashmap_find_1  ... bench:          22 ns/iter (+/- 7)
test tests::bench_hashmap_find_5  ... bench:          19 ns/iter (+/- 13)
test tests::bench_ordermap_find_1 ... bench:          25 ns/iter (+/- 11)
test tests::bench_ordermap_find_5 ... bench:          30 ns/iter (+/- 17)
test tests::bench_vec_find_1      ... bench:           2 ns/iter (+/- 0)
test tests::bench_vec_find_5      ... bench:           7 ns/iter (+/- 6)
```

As we can see, for small data search, vector is very faster than hash map.

**Comment by javaforfun** [comment]
>fn vec_insert(v: &mut Vec<(i32, i32)>) {
>    for peer in v.iter_mut() {
>        if peer.0 == 5 {
>            peer.1 = 5;
>            return;
>        }
>    }
>    v.push((5, 5));
>}
>
>#[bench]
>fn bench_vec_insert(b :&mut Bencher) {
>    let mut v = vec![];
>    v.push((1, 1));
>    v.push((2, 2));
>    v.push((3, 3));
>    v.push((4, 4));
>    b.iter(|| vec_insert(&mut v));
>}
>
>#[bench]
>fn bench_hashmap_insert(b :&mut Bencher) {
>    let mut m = OrderMap::new();
>    m.insert(1, 1);
>    m.insert(2, 2);
>    m.insert(3, 3);
>    m.insert(4, 4);
>    b.iter(|| m.insert(5, 5));
>}

>test bench_hashmap_insert ... bench:          13 ns/iter (+/- 0)
>test bench_vec_insert     ... bench:           3 ns/iter (+/- 0)

for small data insert,  vector also faster than hashmap.

**Comment by BusyJay** [comment]
`FlatMap` will sort internal, it's not friendly for small groups, a similar bench result:
```
test bench_flatmap_find_1_to_5 ... bench:          14 ns/iter (+/- 14)
test bench_hashmap_find_1_to_5 ... bench:          62 ns/iter (+/- 46)
test bench_vec_find_1_to_5     ... bench:           6 ns/iter (+/- 0)
```
I change the query from only fetch one element to fetch all element in a loop to make the difference significant.

**Comment by siddontang** [comment]
maybe we can build a similar Map like FlatMap but use sequence scan. @BusyJay 

Or we can use vector directly.
