### ISSUE TITLE
It hangs to run tests

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1895]
Hi,

The command line hangs to run `make dev`. It shows 

```
test util::transport::tests::test_sendch_full ... ok
test util::worker::test::test_threaded ... ok
test util::worker::test::test_autowired_batch ... ok
test raftstore::store::worker::compact::test::test_compact_range ... ok
test server::server::tests::test_peer_resolve has been running for over 60 seconds
```

and then hangs like forever, using the code in branch master, 24726f72ad5af80e8010eee68c4be173bdf26b7d.

**Comment by siddontang** [comment]
PTAL @disksing

**Comment by hhkbp2** [comment]
It's checked that the grpc server failed to receive raft message in 

https://github.com/pingcap/tikv/blob/master/src/server/grpc_service.rs#L617

**Comment by disksing** [comment]
Test hangs due to connection failure caused by _http_proxy_ env variable.
