### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by louishust** [pingcap/tikv#1902]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.17.0 (56124baa9 2017-04-24)
cargo 0.18.0 (fe7b0cdcf 2017-04-24)

2. What operating system and processor architecture are you using?
OSX Darwin 64

3. What did you do?
make

4. What did you expect to see?
Success

5. What did you see instead?

```
   Compiling prometheus v0.2.9 (https://github.com/pingcap/rust-prometheus.git#01976228)
error[E0554]: #[feature] may not be used on the stable release channel
  --> /Users/loushuai/.cargo/git/checkouts/rust-prometheus-0afd92d0f40cf12e/0197622/src/lib.rs:16:32
   |
16 | #![cfg_attr(feature="nightly", feature(integer_atomics))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `prometheus`.                        ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by siddontang** [comment]
Hi @louishust 

Wee need nightly-2017-05-29, your rust version is out of date.

**Comment by louishust** [comment]
@siddontang i install rust from https://www.rust-lang.org/en-US/install.html,
and the main page version is 

```
Rust 1.17.0
April 27, 2017
```

**Comment by siddontang** [comment]
Hi @louishust 

We suggest using rustup(https://github.com/rust-lang-nursery/rustup.rs) to install rust.

**Comment by siddontang** [comment]
After you install rustup, you can do `rustup override set nightly-2017-05-29` in the TiKV root source directory.

**Comment by louishust** [comment]
@siddontang thanks
