### ISSUE TITLE
Snapshot truncated if leader crashes during snapshot transferring

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#1907]
Hi,

This grpc server will improperly schedule `SnapTask::Close()` to Snapshot Receiver in `server` layer, in code 

https://github.com/pingcap/tikv/blob/3050fef8565787a655e30de503b49149435fdeab/src/server/grpc_service.rs#L645

It should schedule `SnapTask::Discard()` in this case, so that the partly received snapshot could be discarded and deleted.

Because the snapshot V1 implementation reply on the completeness of the snapshot transferring stream. It doesn't check the received length when it calls `save()` on the handling of `SnapTask::Close()`. So in a cluster that runs the code in `branch master, tag 3050fef8565787a655e30de503b49149435fdeab`, which use snapshot V1 by default, if the leader crashes when it transferring the snapshot to followers, the followers would receive and apply a truncated snapshot, and then panic on applying a malformed snapshot.

**Comment by hhkbp2** [comment]
How to reproduce this issue:

1. Use the code like
    tikv hhkbp2/debug-truncated-snapshot
    pd  master
    start a single node cluster, set log level to debug.
2. Write a few GB data into the tikv. You could use rawkv binary or https://github.com/hhkbp2/yabf/tree/tikv to do that.
3. Start a second node tikv, and then wait for two tikv nodes to crashes

Check both nodes' data dir and log, ensure that a truncated snapshot is received and saved on the follower. And then confirm `SnapTask::Close()` is scheduled in the follower's log.

**Comment by hhkbp2** [comment]
PTAL @disksing

**Comment by BusyJay** [comment]
ref pingcap/grpc-rs#53
