### ISSUE TITLE
which rust version tikv support now?

### ISSUE THREAD

**Issue by biolee** [pingcap/tikv#1908]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.19.0-nightly (f062832b2 2017-06-07)

2. What operating system and processor architecture are you using?
mac 10.12.5

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

make

4. What did you expect to see?

5. What did you see instead?
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-std=c++11" "-fPIC" "-O2" "-o" "/Users/liyanan/golang/src/github.com/pingcap/tikv/target/release/build/librocksdb_sys-a40eeeb2edcbb581/out/crocksdb/c.o" "-c" "crocksdb/c.cc"
cargo:warning=crocksdb/c.cc:1780:12: error: no member named 'use_direct_io_for_flush_and_compaction' in 'rocksdb::Options'
cargo:warning=  opt->rep.use_direct_io_for_flush_and_compaction = v;
cargo:warning=  ~~~~~~~~ ^
cargo:warning=1 error generated.
ExitStatus(ExitStatus(256))

**Comment by siddontang** [comment]
Hi @biolee 

Seem your RocksDB version is old, you should upgrade your RocksDB >= 5.4.

**Comment by shenli** [comment]
@siddontang We should specify the rust-nightly version and rocksdb version in the README of tikv repo.

**Comment by siddontang** [comment]
yes

**Comment by biolee** [comment]
yes my RocksDB<5.4, Now I use static-link feature of rust-rocksdb

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
features = ["static-link"]

tks
