### ISSUE TITLE
We need a build guide when we fail to build tikv if rocksdb is not present. 

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tikv#2015]
It is kinda difficult for new user to know what tikv depends on and how to successfully build tikv. That is why I think a guide about how to build tikv is pretty urgent.

**Comment by BusyJay** [comment]
Have you check https://github.com/pingcap/tikv#build?

**Comment by zhexuany** [comment]
The "guide" is too simple. TiKV is strongly coupled with rocksdb. So it is much better if we can include a guide about how to install rocksdb. Especially, our rocksdb is not standard. It is customized. I do not see any guides about how to install rocksdb. At least to myself, I wish there is a guide can tell me how to do rather than asking people.

**Comment by BusyJay** [comment]
To be clear, we are still using the "standard" rocksdb.
