### ISSUE TITLE
How can I build out a static or shared library?

### ISSUE THREAD

**Issue by huafengw** [pingcap/tikv#2075]
Hi, I'm attempting to build out a system static (.a) or shared library (.so) that includes all Tikv code and its dependencies for a C application to call. Is it able to do that? If so, how can I achieve it?

**Comment by BusyJay** [comment]
You can build a library via `cargo rustc --lib -- --crate-type type_you_want`. Check `rustc --help` for more information.

However, I don't think it's practical or even possible to call rust related functions from c code directly. You may need to write some ffis for c in rust too. You can find more details [here](https://doc.rust-lang.org/book/first-edition/ffi.html#calling-rust-code-from-c)

**Comment by huafengw** [comment]
Thank you @BusyJay , You are right, it's not a proper way and currently I'm just doing some experimental things.
