### ISSUE TITLE
compile error on ArchLinux

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/tikv#2185]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.20.0-nightly (f590a44ce 2017-06-27)

2. What operating system and processor architecture are you using?
Arch linux 4.11.6-1-ARCH

3. What did you do?
make static_release

5. What did you see instead?
make[2]: warning: -jN forced in submake: disabling jobserver mode.
/home/dongxu/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.1.0/grpc/third_party/boringssl/crypto/asn1/a_bitstr.c: In function ‘i2c_ASN1_BIT_STRING’:
/home/dongxu/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.1.0/grpc/third_party/boringssl/crypto/asn1/a_bitstr.c:118:5: error: ‘memcpy’: specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
     memcpy(p, d, len);
     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [third_party/boringssl/crypto/asn1/CMakeFiles/asn1.dir/build.make:63: third_party/boringssl/crypto/asn1/CMakeFiles/asn1.dir/a_bitstr.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:4122: third_party/boringssl/crypto/asn1/CMakeFiles/asn1.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/Makefile2:427: CMakeFiles/grpc.dir/rule] Error 2
make[2]: *** [Makefile:281: grpc] Error 2
thread 'main' panicked at '

**Comment by c4pt0r** [comment]
I've already worked around it by downgrading gcc version.

CC=gcc-5 make static_release

**Comment by choleraehyq** [comment]
`CC=clang` also works on Fedora 26.
