### ISSUE TITLE
and 1=1 cause runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zwljava** [pingcap/tikv#2191]
1. What version of Rust are you using (`rustc --version`)?
rc4
2. What operating system and processor architecture are you using?
cenost6.7
3. What did you do?
run sql:
select  count(a.id) from shopping_goods a  join shopping_store b
where a.goods_store_id=b.id 
and 1=1 
and b.store_status=2 and a.goods_status=0  
is error!
but run sql:
select count(a.id) from shopping_goods a  join shopping_store b
where a.goods_store_id=b.id 
and b.store_status=2 and a.goods_status=0  
is ok!
so,and 1=1 error!
but ver rc3 is ok!
4. What did you expect to see?

5. What did you see instead?
2017/08/19 18:20:20 conn.go:341: [0;31m[error] lastCmd select  count(a.id) from shopping_goods a  join shopping_store b
where a.goods_store_id=b.id 
and 1=1 
and b.store_status=2 and a.goods_status=0, runtime error: invalid memory address or nil pointer dereference, goroutine 39970 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420f05a20)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd
panic(0x1022080, 0x1b9ff50)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/expression.(*Constant).Equal(0xc420cefec0, 0x189d9c0, 0xc420d28e00, 0x0, 0x0, 0xc421c092a8)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/expression/expression.go:338 +0x5d
github.com/pingcap/tidb/statistics.getMaskAndRanges(0xc420cef900, 0xc420e4a060, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0xc421c092a8, 0x1, ...)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/statistics/selectivity.go:168 +0x342
github.com/pingcap/tidb/statistics.(*Table).Selectivity(0xc42139ee80, 0x188eb60, 0xc420f05ad0, 0xc420e4a060, 0x2, 0x2, 0x6d66288a72, 0x0, 0xc421e783c0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/statistics/selectivity.go:104 +0x324
github.com/pingcap/tidb/plan.(*DataSource).getStatsProfileByFilter(0xc4218186c0, 0xc420e4a060, 0x2, 0x2, 0xc421e780d0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:82 +0x1da
github.com/pingcap/tidb/plan.(*DataSource).prepareStatsProfile(0xc4218186c0, 0x189b800)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:91 +0x53
github.com/pingcap/tidb/plan.(*LogicalJoin).prepareStatsProfile(0xc420ba1b00, 0x189c040)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:209 +0xe6
github.com/pingcap/tidb/plan.(*LogicalAggregation).prepareStatsProfile(0xc420e57b80, 0x189bec0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:183 +0x83
github.com/pingcap/tidb/plan.(*Projection).prepareStatsProfile(0xc421352a00, 0x0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:170 +0x83
github.com/pingcap/tidb/plan.dagPhysicalOptimize(0x18a1a80, 0xc421352a00, 0xc421352a01, 0x188eb60, 0xc420f05ad0, 0xc421d2f1d8)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:158 +0x4f
github.com/pingcap/tidb/plan.doOptimize(0x37, 0x18a1a80, 0xc421352a00, 0x188eb60, 0xc420f05ad0, 0xc421d2f1d8, 0x1, 0xc420c9d8c0, 0xc421c097f8, 0xd0d861)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:128 +0xdd
github.com/pingcap/tidb/plan.Optimize(0x188eb60, 0xc420f05ad0, 0x18850e0, 0xc420fa0320, 0x7f4622bdf0e8, 0xc4204abad0, 0x0, 0x0, 0x1bb5b40, 0x7f4622c7b960)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:85 +0x27f
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc421c098f0, 0x188eb60, 0xc420f05ad0, 0x7f4622bdf1a8, 0xc420fa0320, 0xc421c098f0, 0x486342, 0xc420487380, 0xc420cef900)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/executor/compiler.go:41 +0x1b7
github.com/pingcap/tidb.Compile(0x188eb60, 0xc420f05ad0, 0x7f4622bdf1a8, 0xc420fa0320, 0x4, 0x118a5ad, 0x8, 0xc421d75cb0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/tidb.go:150 +0x57
github.com/pingcap/tidb.(*session).Execute(0xc420f05ad0, 0xc420bf0ff1, 0xed, 0xc421c09bb8, 0x410aac, 0xc421c09bb8, 0x411082, 0xc420d55e98)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/session.go:641 +0x515
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc421f101e0, 0xc420bf0ff1, 0xed, 0x0, 0x0, 0xc421c09c88, 0x470548, 0xc42176bf18)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/driver_tidb.go:187 +0x62
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420f05a20, 0xc420bf0ff1, 0xed, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:681 +0x8d
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420f05a20, 0xc420bf0ff1, 0xee, 0xed, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:470 +0x42e
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420f05a20)
	/home[0m

**Comment by BusyJay** [comment]
The error is raised in TiDB, can you open an issue to TiDB project?
