### ISSUE TITLE
is this a bug in  consistency check?

### ISSUE THREAD

**Issue by coder0718** [pingcap/tikv#2192]
I am reading TIKV's consistency check mechanism, consider a situation：
Leader completes the calculation of checksum，and send a AdminCmdType::VerifyHash to follow, but in this time follow is computing checksum, so this check will be skip，I think this is not reasonable， the follow should wait until the checksum's compute finished, then start to do verify.

**Comment by BusyJay** [comment]
No, the check is not skipped, hash will be stored in memory, which will be checked once the computation is finished.

**Comment by coder0718** [comment]
ok， I understand this problem.
another question, in on_hash_computed,  will send a verify hash raft request,  is there a judgment here which  only leader can send ?

fn on_ready_verify_hash(&mut self,
                            region_id: u64,
                            expected_index: u64,
                            expected_hash: Vec<u8>) {
        let state = match self.region_peers.get_mut(&region_id) {
            None => {
                warn!("[region {}] receive stale hash at index {}",
                      region_id,
                      expected_index);
                return;
            }
            Some(p) => &mut p.consistency_state,
        };

        // hash will be stored in memory in here
        verify_and_store_hash(region_id, state, expected_index, expected_hash);
    }

    fn on_hash_computed(&mut self, region_id: u64, index: u64, hash: Vec<u8>) {
        let (state, peer) = match self.region_peers.get_mut(&region_id) {
            None => {
                warn!("[region {}] receive stale hash at index {}",
                      region_id,
                      index);
                return;
            }
            Some(p) => (&mut p.consistency_state, &p.peer),
        };

        // checked once the computation is finished.
        if !verify_and_store_hash(region_id, state, index, hash) {
            return;
        }


        // only leader send a verify hash request?
       // is there a judgment here?
        let msg = Msg::new_raft_cmd(new_verify_hash_request(region_id, peer.clone(), state),
                                    Box::new(|_| {}));
        if let Err(e) = self.sendch.send(msg) {
            error!("[region {}] failed to schedule verify command for index {}: {:?}",
                   region_id,
                   index,
                   e);
        }
    }
}

**Comment by coder0718** [comment]
thanks， I understand this problem.
