### ISSUE TITLE
about split

### ISSUE THREAD

**Issue by coder0718** [pingcap/tikv#2216]
@BusyJay 
I have a question about tikv's split mechanism:
In exec_split function, after it modify the region's info and persistence to rocksdb, then this tikv process restart，at this point the split did not  complete，because on_ready_split_region has not yet been executed，how to deal with this situation? 

    fn exec_split(&mut self,
                  ctx: &ExecContext,
                  req: &AdminRequest)
                  -> Result<(AdminResponse, Option<ExecResult>)> {
        PEER_ADMIN_CMD_COUNTER_VEC.with_label_values(&["split", "all"]).inc();

        let split_req = req.get_split();
        if !split_req.has_split_key() {
            return Err(box_err!("missing split key"));
        }

        let split_key = split_req.get_split_key();
        let mut region = self.region.clone();

        try!(util::check_key_in_region(split_key, &region));

        info!("{} split at key: {}, region: {:?}",
              self.tag,
              escape(split_key),
              region);

        // TODO: check new region id validation.
        let new_region_id = split_req.get_new_region_id();

        // After split, the origin region key range is [start_key, split_key),
        // the new split region is [split_key, end).
        let mut new_region = region.clone();
        region.set_end_key(split_key.to_vec());

        new_region.set_start_key(split_key.to_vec());
        new_region.set_id(new_region_id);

        // Update new region peer ids.
        let new_peer_ids = split_req.get_new_peer_ids();
        if new_peer_ids.len() != new_region.get_peers().len() {
            return Err(box_err!("invalid new peer id count, need {}, but got {}",
                                new_region.get_peers().len(),
                                new_peer_ids.len()));
        }

        for (peer, &peer_id) in new_region.mut_peers().iter_mut().zip(new_peer_ids) {
            peer.set_id(peer_id);
        }

        // update region version
        let region_ver = region.get_region_epoch().get_version() + 1;
        region.mut_region_epoch().set_version(region_ver);
        new_region.mut_region_epoch().set_version(region_ver);
        write_peer_state(&ctx.wb, &region, PeerState::Normal)
            .and_then(|_| write_peer_state(&ctx.wb, &new_region, PeerState::Normal))
            .and_then(|_| write_initial_state(self.engine.as_ref(), &ctx.wb, new_region.get_id()))
            .unwrap_or_else(|e| {
                panic!("{} failed to save split region {:?}: {:?}",
                       self.tag,
                       new_region,
                       e)
            });

        let mut resp = AdminResponse::new();
        resp.mut_split().set_left(region.clone());
        resp.mut_split().set_right(new_region.clone());

        PEER_ADMIN_CMD_COUNTER_VEC.with_label_values(&["split", "success"]).inc();

        Ok((resp,
            Some(ExecResult::SplitRegion {
            left: region,
            right: new_region,
        })))
    }

    fn on_ready_split_region(&mut self,
                         region_id: u64,
                         left: metapb::Region,
                         right: metapb::Region) {
    self.region_peers.get_mut(&region_id).unwrap().mut_store().region = left.clone();
    for peer in right.get_peers() {
        // Add this peer to cache.
        self.peer_cache.borrow_mut().insert(peer.get_id(), peer.clone());
    }
    let new_region_id = right.get_id();
    if let Some(peer) = self.region_peers.get(&new_region_id) {
        // Add new peers to cache.
        for meta in right.get_peers() {
            self.peer_cache.borrow_mut().insert(meta.get_id(), meta.to_owned());
        }
        // If the store received a raft msg with the new region raft group
        // before splitting, it will creates a uninitialized peer.
        // We can remove this uninitialized peer directly.
        if peer.get_store().is_initialized() {
            panic!("duplicated region {} for split region", new_region_id);
        }
    }
    let mut campaigned = false;
    let peer;
    match Peer::create(self, &right) {
        Err(e) => {
            // peer information is already written into db, can't recover.
            // there is probably a bug.
            panic!("create new split region {:?} err {:?}", right, e);
        }
        Ok(mut new_peer) => {
            peer = new_peer.peer.clone();
            if let Some(left) = self.region_peers.get(&region_id) {
                campaigned = new_peer.maybe_campaign(left, &mut self.pending_raft_groups);
                if left.is_leader() {
                    // Notify pd immediately to let it update the region meta.
                    self.report_split_pd(left, &new_peer);
                }
            }
            // Insert new regions and validation
            info!("insert new regions left: {:?}, right:{:?}", left, right);
            if self.region_ranges
                .insert(enc_end_key(&left), left.get_id())
                .is_some() {
                panic!("region should not exist, {:?}", left);
            }
            if self.region_ranges
                .insert(enc_end_key(&right), new_region_id)
                .is_none() {
                panic!("region should exist, {:?}", right);
            }
            new_peer.size_diff_hint = self.cfg.region_check_size_diff;
            self.apply_worker.schedule(ApplyTask::register(&new_peer)).unwrap();
            self.region_peers.insert(new_region_id, new_peer);
        }
    }
    if !campaigned {
        if let Some(pos) = self.pending_votes
            .iter()
            .rev()
            .position(|m| m.get_to_peer() == &peer) {
            let msg = self.pending_votes.swap_remove_front(pos).unwrap();
            let _ = self.on_raft_message(msg);
        }
    }
}

**Comment by BusyJay** [comment]
It doesn't matter. `on_ready_split_region` only deals with the meta stored in memory, hence as long as it's ensured that tikv will always build a correct meta from storage when startup, it's safe for TiKV to crash at any point.

**Comment by coder0718** [comment]
In exec_split function, after it modify the region's info and persistence to rocksdb, then this tikv process restart，when the tikv restore from rocksdb's meta, Does the split can continue do ?Because the last split was not Completed.

**Comment by coder0718** [comment]
I dont't think it's safe for TIKV to crash at any point, in exec_split's this code:
    write_peer_state(&ctx.wb, &region, PeerState::Normal)
        .and_then(|_| write_peer_state(&ctx.wb, &new_region, PeerState::Normal))
        .and_then(|_| write_initial_state(self.engine.as_ref(), &ctx.wb, new_region.get_id()))
        .unwrap_or_else(|e| {
            panic!("{} failed to save split region {:?}: {:?}",
                   self.tag,
                   new_region,
                   e)
        });
After write_peer_state success, then the tikv crash, how to deal with this situation?

**Comment by BusyJay** [comment]
Kvs are not written to rocksdb yet. What it writes to is a WriteBatch. You can also see rocksdb's documentation for what it is and how to use it.

**Comment by coder0718** [comment]
thanks. i have understand.
