### ISSUE TITLE
ansible-playbook bootstrap.yml -k

### ISSUE THREAD

**Issue by alexliu5678** [pingcap/tikv#2248]
TASK [pre-ansible : Get os_version from /etc/os-release] ******************************************************************************************************************
fatal: [192.168.4.67]: FAILED! => {"changed": true, "failed": true, "rc": 5, "stderr": "Warning: Permanently added '192.168.4.67' (ECDSA) to the list of known hosts.\r\nPermission denied, please try again.\r\n", "stdout": "", "stdout_lines": []}

**Comment by siddontang** [comment]
PTAL @LinuxGit

**Comment by LinuxGit** [comment]
@alexliu5678 Hi, what's your ansible_user in inventory.ini? If it's normal user and sudo privilege escalation need password, you should add the -K(upper case) parameter as well. `ansible-playbook bootstrap.yml -k -K`, see [Ansible Deployment](https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md). You can new issues in https://github.com/pingcap/tidb-ansible if you encounter any other deployment problems.
