### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by aliyx** [pingcap/tikv#2315]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.22.0-nightly (0701b37d9 2017-09-18)

2. What operating system and processor architecture are you using?
CentOS Linux release 7.3.1611 (Core)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

[admin@localhost tikv]$ make build
cargo build --features "default"
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#3fb9d086)
   Compiling num-iter v0.1.32
   Compiling procinfo v0.3.1
   Compiling unicase v1.4.0
   Compiling nix v0.6.0
   Compiling tokio-io v0.1.1
   Compiling url v1.2.0
error: failed to run custom build command for `librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#3fb9d086)`
process didn't exit successfully: `/home/admin/rust/github/pingcap/tikv/target/debug/build/librocksdb_sys-64d2b5788be075ed/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=rocksdb
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-Wall" "-Wextra" "-o" "/home/admin/rust/github/pingcap/tikv/target/debug/build/librocksdb_sys-46ebaa9da7440d79/out/crocksdb/c.o" "-c" "crocksdb/c.cc"
cargo:warning=crocksdb/c.cc:244:16: warning: unused parameter ‘key’ [-Wunused-parameter]
cargo:warning=   virtual void FindShortSuccessor(std::string* key) const override {}
cargo:warning=                ^
cargo:warning=crocksdb/c.cc:356:16: warning: unused parameter ‘logger’ [-Wunused-parameter]
cargo:warning=   virtual bool PartialMergeMulti(const Slice& key,
cargo:warning=                ^
cargo:warning=crocksdb/c.cc: In function ‘void crocksdb_flush_wal(crocksdb_t*, unsigned char, char**)’:
cargo:warning=crocksdb/c.cc:1116:30: error: ‘class rocksdb::DB’ has no member named ‘FlushWAL’
cargo:warning=   SaveError(errptr, db->rep->FlushWAL(sync));
cargo:warning=                              ^
cargo:warning=crocksdb/c.cc: At global scope:
cargo:warning=crocksdb/c.cc:1965:6: warning: unused parameter ‘opt’ [-Wunused-parameter]
cargo:warning= void crocksdb_options_set_max_mem_compaction_level(crocksdb_options_t* opt,
cargo:warning=      ^
cargo:warning=crocksdb/c.cc:1965:6: warning: unused parameter ‘n’ [-Wunused-parameter]
cargo:warning=crocksdb/c.cc:2076:6: warning: unused parameter ‘opt’ [-Wunused-parameter]
cargo:warning= void crocksdb_options_set_purge_redundant_kvs_while_flush(crocksdb_options_t* opt,
cargo:warning=      ^
cargo:warning=crocksdb/c.cc:2076:6: warning: unused parameter ‘v’ [-Wunused-parameter]
cargo:warning=crocksdb/c.cc: In function ‘void crocksdb_options_set_manual_wal_flush(crocksdb_options_t*, unsigned char)’:
cargo:warning=crocksdb/c.cc:2148:12: error: ‘struct rocksdb::Options’ has no member named ‘manual_wal_flush’
cargo:warning=   opt->rep.manual_wal_flush = v;
cargo:warning=            ^
cargo:warning=crocksdb/c.cc: At global scope:
cargo:warning=crocksdb/c.cc:2231:6: warning: unused parameter ‘opt’ [-Wunused-parameter]
cargo:warning= void crocksdb_options_set_table_cache_remove_scan_count_limit(
cargo:warning=      ^
cargo:warning=crocksdb/c.cc:2231:6: warning: unused parameter ‘v’ [-Wunused-parameter]
cargo:warning=crocksdb/c.cc: In function ‘void crocksdb_sstfilewriter_add(crocksdb_sstfilewriter_t*, const char*, size_t, const char*, size_t, char**)’:
cargo:warning=crocksdb/c.cc:2849:76: warning: ‘rocksdb::Status rocksdb::SstFileWriter::Add(const rocksdb::Slice&, const rocksdb::Slice&)’ is deprecated (declared at /usr/local/include/rocksdb/sst_file_writer.h:85) [-Wdeprecated-declarations]
cargo:warning=   SaveError(errptr, writer->rep->Add(Slice(key, keylen), Slice(val, vallen)));
cargo:warning=                                                                            ^
cargo:warning=crocksdb/c.cc: In function ‘uint64_t crocksdb_table_properties_get_u64(const crocksdb_table_properties_t*, crocksdb_table_property_t)’:
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kColumnFamilyName’ not handled in switch [-Wswitch]
cargo:warning=   switch (prop) {
cargo:warning=          ^
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kFilterPolicyName’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kComparatorName’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kMergeOperatorName’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kPrefixExtractorName’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kPropertyCollectorsNames’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3289:10: warning: enumeration value ‘kCompressionName’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc: In function ‘const char* crocksdb_table_properties_get_str(const crocksdb_table_properties_t*, crocksdb_table_property_t, size_t*)’:
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kDataSize’ not handled in switch [-Wswitch]
cargo:warning=   switch (prop) {
cargo:warning=          ^
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kIndexSize’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kFilterSize’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kRawKeySize’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kRawValueSize’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kNumDataBlocks’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kNumEntries’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kFormatVersion’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kFixedKeyLen’ not handled in switch [-Wswitch]
cargo:warning=crocksdb/c.cc:3318:10: warning: enumeration value ‘kColumnFamilyID’ not handled in switch [-Wswitch]
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-Wall" "-Wextra" "-o" "/home/admin/rust/github/pingcap/tikv/target/debug/build/librocksdb_sys-46ebaa9da7440d79/out/crocksdb/c.o" "-c" "crocksdb/c.cc" with args "c++" did not execute successfully(status code exit code: 1).

', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.53/src/lib.rs:1659:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] Error 101

**Comment by siddontang** [comment]
Hi @aliyx 

Now we only support using nightly-2017-08-09 to build the TiKV.

**Comment by BusyJay** [comment]
Please make sure your rocksdb version is at lease 5.7.3.

**Comment by aliyx** [comment]
@BusyJay, Tks
 
Why not do a version(rocksdb or rust) check, at compile tikv?

**Comment by BusyJay** [comment]
Sounds like a good idea! I have raise an issue to pingcap/rust-rocksdb.

**Comment by breeswish** [comment]
Closing. If you still have problems, please re-open the issue.
