### ISSUE TITLE
tikv fails to complie after deleting Cargo.lock file

### ISSUE THREAD

**Issue by seth-priya** [pingcap/tikv#2330]
1. What version of Rust are you using (`rustc --version`)?
root@25e1e6ea2672:~/tikv# rustc --version
rustc 1.21.0-nightly (215e0b10e 2017-08-08)

2. What operating system and processor architecture are you using?
root@25e1e6ea2672:~/tikv# uname -a
Linux 25e1e6ea2672 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

3. What did you do?
Deleted the Cargo.lock file and triggered "cargo build"

4. What did you expect to see?
Cargo.lock file should get regenerated and build should succeed.

5. What did you see instead?
   Compiling kvproto v0.0.1 (https://github.com/pingcap/kvproto.git#3c5b40fb)
error[E0432]: unresolved import `tipb::analyze`
  --> src/coprocessor/statistics/fmsketch.rs:20:5
   |
20 | use tipb::analyze;
   |     ^^^^^^^^^^^^^ no `analyze` in the root

error[E0046]: not all trait items implemented, missing: `split_region`
   --> src/server/service/kv.rs:91:1
    |
91  | / impl<T: RaftStoreRouter + 'static> tikvpb_grpc::Tikv for Service<T> {
92  | |     fn kv_get(&self, ctx: RpcContext, mut req: GetRequest, sink: UnarySink<GetResponse>) {
93  | |         let label = "kv_get";
94  | |         let timer = GRPC_MSG_HISTOGRAM_VEC
...   |
927 | |     }
928 | | }
    | |_^ missing `split_region` in implementation
    |
    = note: `split_region` from trait: `fn(&Self, grpc::RpcContext<'_>, kvproto::kvrpcpb::SplitRegionRequest, grpc::UnarySink<kvproto::kvrpcpb::SplitRegionResponse>)`

error: aborting due to 2 previous errors

error: Could not compile `tikv`.

To learn more, run the command again with --verbose.

This used to work till a few days back - I was trying to update the versions of some of the dependencies in cargo.toml when I ran into this issue. Later, found that it is reproducible on the mainline (clean checkout) as well, after deleting Cargo.lock. It does not occur if a direct build (without deleting Cargo.lock) is triggered. 

tipb version that gets pulled is:
 _Compiling tipb v0.0.1 (https://github.com/pingcap/tipb.git#0edd8033)_

Please let me know if I am missing something here, I will continue to debug this further from my side as well. Thanks!!

**Comment by seth-priya** [comment]
#2287 seems to have fixed the issue partially 

The only error now is 
root@25e1e6ea2672:~/tikv# cargo build
   Compiling tikv v0.9.0 (file:///root/tikv)
error[E0432]: unresolved import `tipb::analyze`
  --> src/coprocessor/statistics/fmsketch.rs:20:5
   |
20 | use tipb::analyze;
   |     ^^^^^^^^^^^^^ no `analyze` in the root

error: aborting due to previous error

error: Could not compile `tikv`.

To learn more, run the command again with --verbose

**Comment by AndreMouche** [comment]
Thanks very much, we have just fixed it, please try again@seth-priya

**Comment by seth-priya** [comment]
Thanks a lot @AndreMouche - I can confirm that this is now working for me!
