### ISSUE TITLE
link rocksdb statically when making release/ running test by default

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2365]
We meet many compilation failure cases when they link RocksDB dynamically, like:

+ Use another different RocksDB version, but we need a specified one. 
+ Forget to build some compression dependencies.

We may also meet the same problems too, so I think it is better to link RocksDB statically by default.

E.g., for `make release`, `make test`, we can pass `ROCKSDB_SYS_STATIC=1 ROCKSDB_SYS_SSE=1`. It is fine for the static build because we don't need to build the RocksDB every time, only after we use `make clean` or update rust-rocksdb. 

Maybe we can use git submodule to build RocksDB more easily. 

/cc @BusyJay @zhangjinpeng1987

**Comment by BusyJay** [comment]
To do this, we may need to enable cmake support for rocksdb on all platform, which has been almost done at v5.8.

**Comment by qqsun8819** [comment]
Hi @siddontang @BusyJay  For this problem I have a suggestion:
Now it's not so convenient to compile tikv as a whole as we have to checkout and compile/install rocksdb independently. And if our tikv really relies on a specific version of rocksdb, checkout another version of rocksdb will also cause problem.
How about we add a dep.sh in tikv repo, this script will download our specific version of rocksdb and compile. This script can deal with platform-related problem. Then our makefile can still keep its behavior for dep.sh has already setup rocksdb env, and we can update our document that if someone wants to compile tikv from strap dep.sh must be first executed, then run make
We can also integrate dep.sh into makefile, as a target as something like thirdparty.
