### ISSUE TITLE
elapsed_duration_coarse claims no panic but may overflow panic.

### ISSUE THREAD

**Issue by odeits** [pingcap/tikv#2397]
Comment claims `elapsed_duration_coarse` does not panic. This is false. In cases where max values are inputted to the function overflow panics will occur. Either enforce the 'no panic' guarantee by using saturating operations or remove the offending documentation.

https://github.com/pingcap/tikv/blob/e57a49cd13b3ebb8dd6c0f38a34e77732b219050/src/util/time.rs#L278-L300

**Comment by siddontang** [comment]
Thanks @odeits 

Here the `no panic` may refer to time jump back. 

@overvenus we can update the comment.

**Comment by overvenus** [comment]
Hello @odeits ! Nice catch, it will be fixed soon.

Sorry for my late reply! :grinning:
