### ISSUE TITLE
Use of constant (THD_NAME_LEN) does not match documentation

### ISSUE THREAD

**Issue by odeits** [pingcap/tikv#2398]
https://github.com/pingcap/tikv/blob/ac506d2dc656a9f61e38af73dc4c90f70c955a43/src/util/thread_metrics.rs#L152-L154

claims this constant represents the max thread name including null character; however, it is only used by `get_thread_name` and is not a limit but an initial allocation size for `String`

https://github.com/pingcap/tikv/blob/ac506d2dc656a9f61e38af73dc4c90f70c955a43/src/util/thread_metrics.rs#L115-L146

is the documentation incorrect or is the implementation missing a truncate?

**Comment by BusyJay** [comment]
It's guaranteed by the Linux system. But I think `String::with_capacity(end - start)` is better.

**Comment by overvenus** [comment]
Thank you @odeits ! It is misleading and it will be fixed in #2405.
