### ISSUE TITLE
Inconsistent initialization mute vs unmute

### ISSUE THREAD

**Issue by odeits** [pingcap/tikv#2399]
Either both should INIT or neither. I believe that it should be both.

https://github.com/pingcap/tikv/blob/ac506d2dc656a9f61e38af73dc4c90f70c955a43/src/util/panic_hook.rs#L42-L51

**Comment by siddontang** [comment]
Thanks @odeits 

`INIT` only registers a hook which only be needed in `mute`. Maybe we should rename the name.

@BusyJay

**Comment by BusyJay** [comment]
I think the name is fine.

**Comment by odeits** [comment]
Thanks @siddontang 

Makes sense now.
