### ISSUE TITLE
limit_size function may consume iterator

### ISSUE THREAD

**Issue by odeits** [pingcap/tikv#2400]
Potential O(N) memory and time complexity can be avoided in case of `max`

`Iterator` does not require `count` to be O(1) time or space complexity. 

[Iterator::count](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count)
> Consumes the iterator, counting the number of iterations and returning it.

If the iterator is for example over a naive linked list implementation it would require O(N) time to calculate `count`. 
If the iterator can only be consumed once the data may be destroyed by counting it.
This can be avoided by returning an `Option<usize>` and only truncating if change is needed.

https://github.com/pingcap/tikv/blob/ac506d2dc656a9f61e38af73dc4c90f70c955a43/src/util/mod.rs#L53-L82

**Comment by BusyJay** [comment]
I think `get_limit_at_size` can be merged with `limit_size` now since it's not used by other functions anymore. Can you help us to do it?

**Comment by odeits** [comment]
On a related note: Why is the head element treated differently than the tail. This seems like a bug waiting to happen.

**Comment by BusyJay** [comment]
It's intended. `limit_size` should return at lease one message if there is any, no matter what the `size_limit` is.
