### ISSUE TITLE
Use move file mode in IngestFile when applying snapshot

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2404]
We did some benchmark and found that using move file mode can improve the performance, reduce the IO load. So supporting this has a great benefit.

Now the applying snapshot flow is (Lock CF snapshot is the plain format, we ignore it here.):

1. Set raft state to applying
2. Delete all old data including default, write CFs. 
3. Verify file is correct
4. Ingest default SST
5. Ingest write SST
6. Set raft state to normal

If we meet a panic at any point between 1 and 6, when we restart TiKV and resume the applying, this mechanism can work well because all SST files still exist, but if we want to use move file mode, this can't work. We need to care:

1. For above step 2, we can't delete data directly because the SST may be already ingested
2. If an SST does not exist, we need to confirm the SST is ingested and not missing.

Maybe we should use a flag for ingesting SST, set the flag before ingestion and clear the flag with setting with normal. If the flag exists but SST file is missing, we can check the region is empty or not because we have already deleted all data before ingestion and the region can't be empty after the ingestion.

If we can know the SST is ingested, we don't need to delete the old data and verify when we restart TiKV. 

Any corner case do I miss? /cc @BusyJay @zhangjinpeng1987 

BTW, maybe another simple way is to through the recovery mode. When we restart TiKV, if we find that we need to apply the snapshot but the SST file is missing, we froze the peer and let PD remove it and add a new peer on the same store.

**Comment by BusyJay** [comment]
Another way is to support atomic injection across multiple CFs in rocksdb.

**Comment by siddontang** [comment]
seem it is hard to let RocksDB support this.

**Comment by huachaohuang** [comment]
I have already filed an [issue](https://github.com/facebook/rocksdb/issues/3044) to RocksDB. I think it is possible theoretically since all column families share the same manifest file. However, it definitely takes some effort to do it.

**Comment by zhangjinpeng1987** [comment]
If tikv stop before version change has been updated to MANIFEST, but after sst file has been moved into db, the sst file will lose.
BTW there is no indicator to tell us which sst file is the new added file after IngestExternalFile success.

**Comment by BusyJay** [comment]
I don't think the *move* here really means rename but hard link.

**Comment by zhangjinpeng1987** [comment]
Another corner case should concern, when the sst file has been `moved` to db, the `global seqno` of this file will be changed, if we retry the applying process, verify checksum will fail.

**Comment by siddontang** [comment]
using `rename and hard link` is our old design, not origin RocksDB `move` does. 

RocksDB `move` really moves the file, so the SST file doesn't exist when we restart.

**Comment by BusyJay** [comment]
Yes. What I mean is rocksdb will create a hard link first, and remove the original file after everything is done.

**Comment by siddontang** [comment]
Seem that even we use `move`, we may still meet the corner case that @zhangjinpeng1987 mentioned before.

> So we should add an api to reset global seqno

Seem we should support this.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/2600 has done it.
