### ISSUE TITLE
Does it still make sens to use TiKV directly?

### ISSUE THREAD

**Issue by amirouche** [pingcap/tikv#2406]
I hope it's the correct place to ask questions about TiKV because there is no support forums yet.

I am considering using TiKV (or TiDB (or CockroachDB)) for a **new** project.

The project needs horizontal scalability, distributed transactions, etc... but we develop the app from scratch and don't see the point in using TiDB since it seems like the only value TiDB brings is SQL (and readily available drivers).

Also:

- TiDB doesn't support geospatial indices
- TiDB doesn't have a fulltext search (FTS) indices and fuzzy search

The application I am going to build will require both geospatial indices and FTS but also an efficient data model for highly dimensional data. Otherwise said, in SQL parlance, there is a lot of tables but few rows in each tables. The plan is to use the [Entity Attribute Value pattern](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model). EAV can be implemented both in TiDB and TiKV. But I also need performance. Performance requirements are the following:

- A lot of reads, it's 90% of the workload
- 9% of writes that are can be done in batch mode (somewhat like OLAP workload)
- 1% of writes that must respond to user input

I am familiar with wiredtiger (an ordered key value store), I don't think that's really hard to understand key composition and manually building secondary indices. I'd like to trade SQL with speed and simpler architecture. Are my assumption correct that using TiKV will deliver more performance in my context?
Do you think it's the right path?

Maybe it's ok to trade some speed use TiDB right now and wait/contribute to Geospatial indices and FTS. WDYT?

Is it possible to use TiDB and directly access TiKV for performance critical queries?

Also, is there any driver for TiKV that is not written in Rust?

Thanks in advance!

**Comment by siddontang** [comment]
Hi @amirouche 

I think it is better for you to contribute Geo and FTS to TiDB directly.

> Is it possible to use TiDB and directly access TiKV for performance critical queries?

For performance critical queries, we can implement the logic in the TiKV coprocessor directly like what we do for many queries now.

> Also, is there any driver for TiKV that is not written in Rust?

We have a go driver, you can see https://github.com/pingcap/tidb/blob/master/cmd/benchkv/main.go

**Comment by amirouche** [comment]
What about the EAV pattern on top of TiDB. Is it ok to implement such a thing?

**Comment by amirouche** [comment]
Where the `.proto` file for the TKiV gRPC service?

**Comment by siddontang** [comment]
@amirouche  The gRPC proto is in https://github.com/pingcap/kvproto

**Comment by siddontang** [comment]
@amirouche 

We don't use EAV before and can't know whether we can support it or not on TiDB.
Geo is in our future plan. If you have interests, you can work with us to support this feature. :-)

**Comment by amirouche** [comment]
Thanks for the quick responses.

**Comment by ccpu** [comment]
@amirouche 

I'm looking to implement an EAV model on top of TiDB as well. Could you share your final decision regarding this approach? I'm also considering using TiKV directly, but I'm not sure if that's a good option. Would you mind sharing your final decision and any insights you gained during your implementation? I appreciate any help or advice you can provide.
