### ISSUE TITLE
Switch to maplit crate for map literal macros

### ISSUE THREAD

**Issue by odeits** [pingcap/tikv#2414]
https://github.com/pingcap/tikv/blob/716633c4c417da126b9d0ada9dd1ad6faec2d64f/src/util/macros.rs#L62-L63

According to the referenced issue it seems that the recommendation is to use the [maplit ](https://crates.io/crates/maplit) crate

**Comment by siddontang** [comment]
Thanks @odeits 

PTAL @BusyJay

**Comment by BusyJay** [comment]
We may not use HashMap from std crate, so I prefer to keep it that way.
