### ISSUE TITLE
add limitation for key size

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2438]
We limit value size to 5 MB, and we should also limit key size to a small size. 

Supporting too large key is not a good idea, this may cause huge heartbeat message, and may also reduce the write performance for RocksDB.

TiDB limits key size to 3 KB, we can limit it to 4 KB

**Comment by abourget** [comment]
Is value still capped at 5MB? is that configurable?

Bigtable has 10MB per cell limits (100MB per row), ScyllaDB has 16MB per  INSERT statement, so cells can have ~16MB.

Would be awesome to be able to push the limit of the value size, for some keys (from time to time).
