### ISSUE TITLE
error during Installing tidb using ansible

### ISSUE THREAD

**Issue by iontrap** [pingcap/tikv#2447]
I install the tidb using ansible offline. There are 24 nodes in the cluster, node2-node4 are speicfied as PD and Tidb servers, others are Tikv servers.  When i excute the command " ansible-playbook deploy.yml" , the error is below: 
    Task [tikv: create config file]
    fatal:[10.10.10.5]: failed=>{ "changed",false,"failed",true,"msg":"AttributeError: 'Unicode' objects has no attribute 'items'"}
   Other 20 tikv server nodes happened with the same error.
    What i changed is thd data-dir from the default /tmp/ to /data/.

**Comment by siddontang** [comment]
PTAL @LinuxGit

**Comment by LinuxGit** [comment]
Hi, @iontrap.  We've added  `--data-dir` parameter in tikv startup script `run_tikv.sh`. It's default value is `tikv_data_dir: "{{ deploy_dir }}/data"`.  If you want to customize, you need to set tikv_data_dir  tikv host or group variable in tidb-ansible/inventory.ini. We'll remove data-dir in later tidb-ansible release, and sorry to confuse you.

**Comment by breeswish** [comment]
Closing. If you still encounter this issue, please re-open.
