### ISSUE TITLE
configure rocksdb

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#245]
now we use the default configuration for rocksdb, but this is not suitable in production usage. We should support configuring it. 

An example: https://github.com/reborndb/qdb/blob/master/conf/config.toml

**Comment by spacejam** [comment]
let me know if you need any additional code added to rust-rocksdb to better support this, and I'd gladly add it!

**Comment by siddontang** [comment]
Thanks @spacejam 

We will send you PR too :-)

**Comment by tiancaiamao** [comment]
rocksdb c++ lib provide [load options file](https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File) API, currently rust-rocksdb don't wrap it.
I suggest wrap this API to implement later~

**Comment by BusyJay** [comment]
I don't think RocksDB has exposed this ABI yet.

**Comment by siddontang** [comment]
Should see c include file not c++ include file.
