### ISSUE TITLE
build tikv failed on unbuntu16

### ISSUE THREAD

**Issue by mccxj** [pingcap/tikv#2451]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

rustc 1.23.0 nightly

2. What operating system and processor architecture are you using?

ubuntu 16.04.3 TLS

3. What did you do?

![virtualbox_ubuntu_04_11_2017_22_29_05](https://user-images.githubusercontent.com/98360/32406274-684b7a94-c1b0-11e7-9b64-f0f87adc5074.png)

**Comment by siddontang** [comment]
Hi @mccxj 

Seem you don't install RocksDB, you can use `make static_release`.

**Comment by mccxj** [comment]
@siddontang  Thanks. But it failed when use **make test**, the error stack is the same.

**Comment by siddontang** [comment]
@mccxj 

`make test` also tries to use the shared RocksDB which you don't install on your machine. 

You can run `ROCKSDB_SYS_STATIC=1 ROCKSDB_SYS_PORTABLE=1 ROCKSDB_SYS_SSE=1 make test`. Or you can install shared RocksDB (version > 5.7.3) library by yourself and run `make test`

We will update the Makefile to make all use the static RocksDB by default, only use the shared one for development.

**Comment by mccxj** [comment]
Thanks.it is not stated explicitly in the developer guide.I was confused.

also,the build status is error on the home page(README.md)

**Comment by siddontang** [comment]
@mccxj 

We will add an INSTALL.md for developer later.

**Comment by siddontang** [comment]
We have already removed travis CI, so the status is out of date, can you help us to fix this?

**Comment by mccxj** [comment]
@siddontang Makefile shows different RocksDB version.
https://github.com/pingcap/tikv/blob/0cb7a7dedba66cfe91e47e3df68facbbeceba8d2/travis-build/Makefile#L22

**Comment by BusyJay** [comment]
Most targets are not used anymore.

**Comment by breeswish** [comment]
Closing. if you still have problems please re-open.
