### ISSUE TITLE
make dev error

### ISSUE THREAD

**Issue by aliyx** [pingcap/tikv#2461]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.23.0-nightly (02004ef78 2017-11-08)

2. What operating system and processor architecture are you using?
ubuntu 17.10

3. What did you do?
aliyx@air-pro:~/git/rust/tikv$ make dev
make[1]: Entering directory '/home/aliyx/git/rust/tikv'
Rustfmt failed at /home/aliyx/git/rust/tikv/tests/raft/test_raft.rs:636: line exceeded maximum length (maximum: 100, found: 101) (sorry)

Rustfmt failed at /home/aliyx/git/rust/tikv/tests/raft/test_raft.rs:636: line exceeded maximum length (maximum: 100, found: 101) (sorry)

Makefile:83: recipe for target 'format' failed
make[1]: *** [format] Error 3
make[1]: Leaving directory '/home/aliyx/git/rust/tikv'
Makefile:33: recipe for target 'dev' failed
make: *** [dev] Error 2

**Comment by siddontang** [comment]
@aliyx 

what is the rustfmt version do you use? We only support nightly-0.2.1 now.

**Comment by mccxj** [comment]
@aliyx here is the rustfmt install guide
https://github.com/pingcap/tikv/blob/0cb7a7dedba66cfe91e47e3df68facbbeceba8d2/travis-build/Makefile#L42

**Comment by aliyx** [comment]
@mccxj Tks

**Comment by siddontang** [comment]
can it work now? @aliyx

**Comment by aliyx** [comment]
@siddontang 

Because my rust version is nightly-2017-11-08, there was an error installing rustfmt nightly-0.2.1, so I installed nightly-0.2.5.
However, regardless of whether the version of rustfmt is 0.2.1 or 0.2.5, the limit for the width of the rustfmt line is 100, and all the formatting is successful unless 'max_width = 120' is set in the rustfmt.toml file.
