### ISSUE TITLE
bug: StoreNotMatch

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2496]
```
2017/11/21 12:23:11.374 region_cache.go:447: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/11/21 12:23:11.378 region_cache.go:447: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/11/21 12:23:11.389 region_cache.go:447: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/11/21 12:23:13.545 region_request.go:164: [warning] tikv reports `StoreNotMatch`: , ctx: &{{1009 3 4} id:1009 start_key:"t\200\000\000\000\000\000\000O_i\200\000\000\000\000\000\000\014\0012104\000\000\000\000\373\003\200\000\000\000\013\271\210]" end_key:"t\200\000\000\000\000\000\000O_r\200\000\000\000\013\2662^" region_epoch:<conf_ver:3 version:4 > peers:<id:1010 store_id:1 > peers:<id:1011 store_id:7 > peers:<id:1012 store_id:4 >  id:1011 store_id:7  10.10.9.23:20160}, retry later
```

We can ensure that TiDB connects the right PD, TiKV reports correct address and store ID to PD and PD also has correct cluster information, so meeting this error is very strange.

Btw, I find that we will output the error in scheduler but not in coprocessor, and the coprocessor error metric will use "other" for this error, this is not intuitive. /cc @BusyJay

**Comment by BusyJay** [comment]
> ... and the coprocessor error metric will use "other" for this error...

I'm not sure if I understand it correctly. You mean [this line](https://github.com/pingcap/tikv/blob/master/src/coprocessor/endpoint.rs#L593) will be encountered? But that's impossible. If coprocessor reports other error, All TiDB receives is just an error string, it has no idea what the precise error TiKV returns, hence it can't output a log about `StoreNotMatch`.

**Comment by disksing** [comment]
I believe it is caused by data race in region_cache. See https://github.com/pingcap/tidb/pull/5171

**Comment by siddontang** [comment]
@BusyJay 

I think we should add a metric for invalid propose like we do for invalid raft message.
