### ISSUE TITLE
raft as crate

### ISSUE THREAD

**Issue by stephanbuys** [pingcap/tikv#2594]
Hi there, could you provide a rough guide to use your raft implementation without the rest of tikv, it has been mentioned in the rust community that this is possible?

Would you consider spinning out the raft module as a crate? There is quite a big gap for this kind of crate in the ecosystem.

Thank you for considering...

**Comment by siddontang** [comment]
hi @stephanbuys 

We will do this after the #2491 is merged. But another problem is that the crate name "raft" is already used by @Hoverbear, so we should think another crate name.

But I think the best way is @Hoverbear allow us to use the "raft" name. :-)

**Comment by Hoverbear** [comment]
Or I can give you it! :)

**Comment by BusyJay** [comment]
We make a release after pingcap/raft-rs#1 is resolved.

**Comment by stephanbuys** [comment]
This is great, thank you!
