### ISSUE TITLE
Can't run tests or build on latest nightly

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/tikv#2603]
1. What version of Rust are you using (`rustc --version`)?

```
rustc 1.24.0-nightly (edbd7d232 2017-12-20)
```

2. What operating system and processor architecture are you using?

Mac OS X 10.13.2 x86-64

3. What did you do?

Assuming `rustup` is installed and the latest `nightly` toolchain is installed.

```bash
git clone git@github.com:pingcap/tikv.git
cargo +nightly test
```

4. What did you expect to see?

No build failure.

5. What did you see instead?

```rust
$ cargo +nightly build
   Compiling rustc-serialize v0.3.19
   Compiling tipb v0.0.1 (https://github.com/pingcap/tipb.git#4fed9b6c)
   Compiling syn v0.11.11
   Compiling idna v0.1.0
   Compiling zstd-sys v1.4.1+zstd.1.3.2 (https://github.com/gyscos/zstd-rs.git#a3b05c8a)
   Compiling sys-info v0.5.1
   Compiling dbghelp-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling solicit v0.4.4
   Compiling num-iter v0.1.32
   Compiling unicase v1.4.0
error[E0642]: patterns aren't allowed in methods without bodies
   --> /Users/hoverbear/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling grpcio-sys v0.1.2
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#20d39998)
   Compiling snappy-sys v0.1.0 (https://github.com/busyjay/rust-snappy.git?branch=static-link#be021783)
   Compiling backtrace-sys v0.1.15
   Compiling lz4-sys v1.8.0 (https://github.com/busyjay/lz4-rs.git?branch=adjust-build#41509fea)
   Compiling bzip2-sys v0.1.6 (https://github.com/alexcrichton/bzip2-rs.git#b82dee62)
   Compiling aho-corasick v0.5.3
error: aborting due to previous error

error: Could not compile `rustc-serialize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Diagnosis

This comes from a bug which was fixed in https://github.com/rust-lang-deprecated/rustc-serialize/pull/169, and released as [0.3.21](https://github.com/rust-lang-deprecated/rustc-serialize/releases/tag/0.3.21)

TiKV includes a [`Cargo.lock`](https://github.com/pingcap/tikv/blob/master/Cargo.lock) which, as a binary, [is appropriate](http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). One line in the `Cargo.lock` is this:

https://github.com/pingcap/tikv/blob/8577330ae1ddb9483068d0fae79343b88000b70a/Cargo.lock#L310-L328

The offending line is this:

https://github.com/pingcap/tikv/blob/8577330ae1ddb9483068d0fae79343b88000b70a/Cargo.lock#L321

We pull in this version of `hyper` via the `rust-prometheus` dependency:

https://github.com/pingcap/tikv/blob/8577330ae1ddb9483068d0fae79343b88000b70a/Cargo.lock#L657-L671

`rust-prometheus` does not depend on this particular version of `hyper`:

https://github.com/pingcap/rust-prometheus/blob/f24ea12943e03da7412e2e2310e6d955e2004887/Cargo.toml#L48-L53

## Resolution

We can solve this by either manually bumping the `rustc-serialize` version required via:

```bash
cargo update --package rustc-serialize
```

Or we can run `cargo update` and make a PR to update other dependencies.

According to `semver` this should be fairly safe since we're locking our dependencies to compatible versions in the `Cargo.toml`. Unfortunately, due to a git based dependencies we have failures:

<details>
  <summary>Lots of `cargo +nightly test` output</summary>
<pre><code>
$ cargo +nightly test
# ...
   Compiling rocksdb v0.3.0 (https://github.com/pingcap/rust-rocksdb.git#51a5c0c8)
error[E0432]: unresolved import `tipb::select::SelectRequest`
  --> src/coprocessor/endpoint.rs:20:38
   |
20 | use tipb::select::{self, DAGRequest, SelectRequest};
   |                                      ^^^^^^^^^^^^^ no `SelectRequest` in `select`

error[E0432]: unresolved import `tipb::select::SelectRequest`
  --> src/coprocessor/select/select.rs:16:36
   |
16 | use tipb::select::{Chunk, RowMeta, SelectRequest, SelectResponse};
   |                                    ^^^^^^^^^^^^^ no `SelectRequest` in `select`

error[E0432]: unresolved import `tipb::select::SelectRequest`
  --> src/coprocessor/endpoint.rs:20:38
   |
20 | use tipb::select::{self, DAGRequest, SelectRequest};
   |                                      ^^^^^^^^^^^^^ no `SelectRequest` in `select`

error[E0432]: unresolved import `tipb::select::SelectRequest`
   --> src/coprocessor/select/xeval/evaluator.rs:690:9
    |
690 |     use tipb::select::SelectRequest;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `SelectRequest` in `select`

error[E0432]: unresolved import `tipb::select::SelectRequest`
  --> src/coprocessor/select/select.rs:16:36
   |
16 | use tipb::select::{Chunk, RowMeta, SelectRequest, SelectResponse};
   |                                    ^^^^^^^^^^^^^ no `SelectRequest` in `select`

warning: unused import: `str`
  --> src/coprocessor/dag/expr/compare.rs:14:11
   |
14 | use std::{str, i64};
   |           ^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unused import: `str`
  --> src/coprocessor/dag/expr/compare.rs:14:11
   |
14 | use std::{str, i64};
   |           ^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:318:20
    |
318 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:329:20
    |
329 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:345:20
    |
345 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error: aborting due to 5 previous errors

error: Could not compile `tikv`.
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:318:20
    |
318 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:329:20
    |
329 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `set_recursion_limit` found for type `protobuf::CodedInputStream<'_>` in the current scope
   --> src/coprocessor/endpoint.rs:345:20
    |
345 |                 is.set_recursion_limit(recursion_limit);
    |                    ^^^^^^^^^^^^^^^^^^^

error: aborting due to 6 previous errors

error: Could not compile `tikv`.

To learn more, run the command again with --verbose.
</code></pre>
</details>

Given that we're currently locking our `rustc` version in the Rust dockerfile:

https://github.com/pingcap/tikv/blob/8577330ae1ddb9483068d0fae79343b88000b70a/docker/rust_dockerfile#L40-L42

As well as the `circle.yml`:

https://github.com/pingcap/tikv/blob/8577330ae1ddb9483068d0fae79343b88000b70a/circle.yml#L11

We can even take this chance update them.

## Acceptance Criteria

`rustup update nightly && cargo +nightly test` builds, and all CI tests pass.

**Comment by siddontang** [comment]
Thanks @Hoverbear 

Now another reason for us to use 08-09 nightly version is that we use rustfmt 0.2.1 nightly version which can't be installed with the newest rust version, and if we upgrade rustfmt, we need to change lots of codes which may introduce many conflicts with current PRs, :sob:

But upgrading has to be considered now, our rust version seems too old. 

/cc @BusyJay @overvenus

**Comment by overvenus** [comment]
+1 for upgrading Rust. 
Before upgrading I suggest test it for a while, we have encountered a problem 
that  may be casued by the "latest" rust `rustc 2016-12-19`. https://github.com/rust-lang/rust/issues/37105
