### ISSUE TITLE
gRPC server: use local metrics 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2651]
Now we have to consider the cost of using global metrics in multi-threads, a workable way is to introduce Per-Core metrics, but we may still need a lock to handle MetricVec and can't solve the lock contention problem and still need to calculate the tag HASH every time.

Another way is to use local metrics like Raftstore does, but now it is impossible for gRPC server threads because we can't find a good way to flush the local metrics to the global metrics regularly.

So I think we can let gRPC thread supports Timer directly. gRPC has Alarm which we can use directly to implement the Timer. 

Maybe we can register a TimerService or start with a TimerService. 

/cc @BusyJay @hicqu @overvenus

**Comment by BusyJay** [comment]
Why does `MetricVec` need to be handled here? I think `MetricVec` should become `MetricStruct`, and all labels are the field names of the struct. So there should be no locks.

**Comment by BusyJay** [comment]
And I think there should be a benchmark between per-core metrics and local metrics. If there are no big difference, I prefer per-core metrics for its simplicity and can be supported directly in Prometheus crate.

**Comment by siddontang** [comment]
> all labels are the field names of the struct

The tag may be dynamically changed in some cases, maybe we will still consider hash map.

**Comment by BusyJay** [comment]
Can you give some cases that requires change the label dynamically in gRPC service?

**Comment by siddontang** [comment]
Btw, It suddenly strikes me that per-core may not apply to Guage metric.

**Comment by siddontang** [comment]
> Can you give some cases that requires change the label dynamically in gRPC service

not in gRPC service, but for other cases. Prometheus is a library, so we can't assume user always uses the const tags.

**Comment by BusyJay** [comment]
One field for one gRPC API.

I think `Guage` can be just summed up together for all cores.

**Comment by siddontang** [comment]
> I think Guage can be just summed up together for all cores

Seem not. E.g, if we set max_a = 2 on core 1 and later another max_a = 1 on core 2, which value should we choose? 

Guage is the set value, not summed up.

**Comment by BusyJay** [comment]
So how can you solve it using local metrics? If it can be solved by local metrics, then it can definitely solved by per-core metrics.

**Comment by siddontang** [comment]
per-core metrics is in the prometheus library, so we can't solve it. 

But for local metrics, it depends on our logic and we can control it, E.g. for Guage, still use global metrics directly.

So per-core can only be used for counter and histogram, and seems not for guage and MetricVec.

**Comment by BusyJay** [comment]
That's not true. It depends on how the API is designed. For example, we can require user to specify how to aggregate all core metrics when publishing metrics, or defining a per-core metrics.

**Comment by siddontang** [comment]
I think for guage, we can record the time, so we can get the latest set value when we collect the metric.

**Comment by siddontang** [comment]
I wrote a simple benchmark https://gist.github.com/siddontang/9d9800f9f4981fea02145ca52f4687a9

If we need to use per-core statistics, we still need to use Atomic value. 
For the local metric, we flush to the global metric every 100 counts. 

```
test tests::bench_getcpuid  ... bench:          12 ns/iter (+/- 0)

test tests::bench_global    ... bench:          12 ns/iter (+/- 0)
test tests::bench_local     ... bench:           2 ns/iter (+/- 0)
test tests::bench_use_cpuid ... bench:          25 ns/iter (+/- 5)
```

Although per-core is fast, using local is faster with one order of magnitude. So if we can use local metrics, I prefer using it, otherwise, try to introduce per-core.  

```
test tests::bench_f64_inc   ... bench:          12 ns/iter (+/- 0)
test tests::bench_u64_inc   ... bench:           6 ns/iter (+/- 0)
```

Another thing we need to care is that now we use AtomicF64 for Counter, but we almost use the integer in our case, so maybe using an AtmoicU64 counter is better (we can see u64 is twice faster than f64), maybe we can provide an Integer Counter, Guage or Histogram. /cc @overvenus

**Comment by BusyJay** [comment]
The bench you write only use one thread. It's pointless to use per-core metrics if there is only one thread that mutates the metrics.

There is no doubt that local metrics is faster than per-core metrics. However the point is how much the difference is, if it's not significant enough, then per-core metrics is better than local metrics for its simplicity.

**Comment by siddontang** [comment]
Here I just want to see the cost of get_cpuid and the atomic operation, no matter there is one thread or many threads.

I said above that if we can use local, it is better to use it. Now for us, except gRPC server, and some metrics crossing threads, we can all use local metrics.

Using core-local still can't solve the MetricVec Hash problem, maybe we can use MetricStruct which means using one metric for one type separately, this is a solution, but we can't use the metric tag and may write many queries in Grafana.
