### ISSUE TITLE
GC: move the GC metrics to the GC row

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#2666]
![image](https://user-images.githubusercontent.com/1080370/34764459-96ae6bd2-f629-11e7-95c4-ae3145f690dd.png)

The GC in the gRPC metrics affects checking other APIs, we should move GC to the GC row and handle it separately.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tidb-ansible/pull/261 has fixed it.
