### ISSUE TITLE
tikv-server error when upgrade to last version tikv from version of 2017-8-14

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tikv#2749]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

 Rustc Version:     1.25.0-nightly (73ac5d6a8 2018-01-11)

2. What operating system and processor architecture are you using?

centos 7.2 x86_64
cat /proc/version
Linux version 3.10.0-327.13.1.el7.x86_64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

upgrade to lastest version  today (2018-2-8) 

last version is downloaded at 2017-8-14 with latest binary version

4. What did you expect to see?

tikv running ok

5. What did you see instead?

2018/02/08 09:52:35.411 mod.rs:344: [INFO] Welcome to TiKV.
2018/02/08 09:52:35.412 mod.rs:345: [INFO] Release Version:   1.1.0-dev
2018/02/08 09:52:35.412 mod.rs:346: [INFO] Git Commit Hash:   18ab0e5db93763675525e029533d8ca37f5d3eab
2018/02/08 09:52:35.412 mod.rs:347: [INFO] Git Commit Branch: master
2018/02/08 09:52:35.412 mod.rs:348: [INFO] UTC Build Time:    2018-02-07 09:01:38
2018/02/08 09:52:35.412 mod.rs:349: [INFO] Rustc Version:     1.25.0-nightly (73ac5d6a8 2018-01-11)
2018/02/08 09:52:35.412 tikv-server.rs:503: [ERROR] invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")

**Comment by siddontang** [comment]
hi @aruanruan 

Seem you use a too old TiKV version before which didn't support raft RocskDB. 

We don't support compatibility before GA version.
