### ISSUE TITLE
TiKV tuning

### ISSUE THREAD

**Issue by Borelset** [pingcap/tikv#2877]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
binary version
Release Version: v2.0.0-rc.3-2-gb1e6249
Git Commit Hash: b1e624918d5cd3a12a47ef23d7ac5eccd7db4757
Git Branch: master
UTC Build Time: 2018-03-26 08:50:31

2. What operating system and processor architecture are you using?
CentOS Linux release 7.4.1708 (Core)
Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz (32 core)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
For testing TiKV cluster, I deploy TiKVs and PDs like below.
IP\Disk   Disk1 Disk2 Disk3 Disk4
*.*.*.117 TiKV1 TiKV2 TiKV3 PD1
*.*.*.118 TiKV4 TiKV5 TiKV6 PD2
*.*.*.119 TiKV7 TiKV8 TiKV9 PD3,go-ycsb

After inserting 75,000,000 items by go-ycsb, I run a command like 
```
./go-ycsb run tikv -P workloads/workload_insert --threads 64 -p "operationcount=10000000" -p "recordcount=75000000"
```
, and get a performance report finally.

```
INFO[0000] [pd] create pd client with endpoints [200.200.172.117:2379] 
INFO[0000] [pd] leader switches to: http://200.200.172.117:2379, previous:  
INFO[0000] [pd] init cluster id 6537846749732724776     
INSERT - Count: 716877, Avg(us): 878, Min(us): 331, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 1444242, Avg(us): 872, Min(us): 318, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 2168627, Avg(us): 871, Min(us): 316, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 2893774, Avg(us): 870, Min(us): 316, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 3613522, Avg(us): 871, Min(us): 316, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 4323580, Avg(us): 874, Min(us): 316, Max(us): 98263, 95th(us): 2000, 99th(us): 4000
INSERT - Count: 4923594, Avg(us): 895, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 5642733, Avg(us): 893, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 6361985, Avg(us): 891, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 7085129, Avg(us): 889, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 7807350, Avg(us): 887, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 8519542, Avg(us): 887, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 9236557, Avg(us): 886, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
INSERT - Count: 9952172, Avg(us): 886, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
Run finished, takes 2m20.913052745s
INSERT - Count: 9999997, Avg(us): 886, Min(us): 316, Max(us): 811628, 95th(us): 2000, 99th(us): 5000
```

through iostat i could find that disk and cpu is not the bottleneck.

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          25.12    0.00   10.17    0.00    0.00   64.70
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sde               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     6.00    0.00   24.00     0.00  5916.00   493.00     0.02    0.92    0.00    0.92   0.58   1.40
sda               0.00     0.00    0.00   18.00     0.00  4608.00   512.00     0.02    1.00    0.00    1.00   0.72   1.30
sdc               0.00     6.00    0.00   24.00     0.00  5916.00   493.00     0.02    0.88    0.00    0.88   0.65   1.55
sdd               0.00     0.00    0.00    4.00     0.00    12.00     6.00     0.00    0.25    0.00    0.25   0.25   0.10
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

memory is also not

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND      
 4817 root      20   0 4535912 1.025g  24252 S 407.6  0.8 237:04.99 tikv-server
 5005 root      20   0 4197992 960920  24256 S 367.1  0.7 240:39.15 tikv-server     
 4637 root      20   0 4888412 978976  24464 S 363.8  0.7 240:11.04 tikv-server  
```

neither network

```
03:10:32 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
03:10:34 PM enp134s0f0      0.00      0.00      0.00      0.00      0.00      0.00      0.00
03:10:34 PM  enp4s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00
03:10:34 PM      eno1 133567.50 133429.50  18114.46  17652.19      0.00      0.00     61.00
03:10:34 PM enp134s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00
03:10:34 PM enp130s0f0      0.00      0.00      0.00      0.00      0.00      0.00      0.00
03:10:34 PM enp130s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00
03:10:34 PM        lo  14131.00  14131.00   1664.30   1664.30      0.00      0.00      0.00
```

so i want to know where the bottleneck would be?

4. What did you expect to see?
better performance.

5. What did you see instead?
unknown bottleneck.

**Comment by siddontang** [comment]
Hi @Borelset 

You can increase the threads to 128 or start another YCSB instance to see whether the performance is increased or not.

**Comment by Borelset** [comment]
@siddontang 
increasing thread to 128 leads to higher latency and ops.
but disks still have much idle time.

**Comment by siddontang** [comment]
oh, does the TiKV becomes bottleneck? Can you run another YCSB?

**Comment by siddontang** [comment]
Can you use `top -H` to show each thread of TiKV?

Or how about the Threads of TiKV Grafana metrics?

**Comment by Borelset** [comment]
top -H

server 1 run 3 TiKVs

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND         
31232 root      19  -1 4609848 998832  24688 R 85.1  0.8  35:29.34 raftstore-984
30812 root      19  -1 4503352 0.982g  24880 R 78.8  0.8  34:53.45 raftstore-632
31016 root      19  -1 4708152 908512  24736 R 76.5  0.7  33:55.60 raftstore-843
31227 root      20   0 4609848 998832  24688 R 72.2  0.8  26:30.21 grpc-server-0
31228 root      20   0 4609848 998832  24688 R 67.2  0.8  27:04.27 grpc-server-1
31248 root      20   0 4609848 998832  24688 R 64.6  0.8  25:59.02 apply worker     
31011 root      20   0 4708152 908512  24736 R 60.3  0.7  26:23.05 grpc-server-0
31012 root      20   0 4708152 908512  24736 R 60.3  0.7  24:28.77 grpc-server-1
30809 root      20   0 4503352 0.982g  24880 R 59.6  0.8  24:01.92 grpc-server-2
31027 root      20   0 4708152 908512  24736 S 56.3  0.7  24:39.44 apply worker
31230 root      20   0 4609848 998832  24688 R 55.3  0.8  22:09.35 grpc-server-3
30823 root      20   0 4503352 0.982g  24880 S 55.0  0.8  24:22.85 apply worker
31013 root      20   0 4708152 908512  24736 R 52.0  0.7  23:17.92 grpc-server-2
31014 root      20   0 4708152 908512  24736 S 50.3  0.7  20:40.13 grpc-server-3
30808 root      20   0 4503352 0.982g  24880 R 49.0  0.8  22:00.09 grpc-server-1
30810 root      20   0 4503352 0.982g  24880 R 47.7  0.8  23:17.02 grpc-server-3

server 2 run 3 TiKVs
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND          
19400 root      20   0 4575032 944244  24740 R 87.8  0.7  26:51.31 grpc-server-3     
19207 root      19  -1 4624184 1.023g  24832 S 83.5  0.8  40:31.61 raftstore-1        
19402 root      19  -1 4575032 944244  24740 S 72.9  0.7  34:34.78 raftstore-4      
19218 root      20   0 4624184 1.023g  24832 R 68.6  0.8  32:18.39 apply worker   
19597 root      19  -1 4720440 982072  24712 S 64.7  0.7  35:04.19 raftstore-7     
19203 root      20   0 4624184 1.023g  24832 S 62.0  0.8  27:10.03 grpc-server-1    
19413 root      20   0 4575032 944244  24740 R 59.4  0.7  25:02.82 apply worker    
19608 root      20   0 4720440 982072  24712 S 59.1  0.7  24:47.16 apply worker    
19202 root      20   0 4624184 1.023g  24832 S 57.4  0.8  30:12.29 grpc-server-0   
19205 root      20   0 4624184 1.023g  24832 S 52.8  0.8  27:57.81 grpc-server-3    
19399 root      20   0 4575032 944244  24740 S 51.5  0.7  25:46.91 grpc-server-2    
19593 root      20   0 4720440 982072  24712 R 51.5  0.7  24:44.06 grpc-server-1   
19595 root      20   0 4720440 982072  24712 S 51.5  0.7  25:12.47 grpc-server-3    
19397 root      20   0 4575032 944244  24740 S 50.8  0.7  29:17.87 grpc-server-0     
19592 root      20   0 4720440 982072  24712 R 50.8  0.7  31:06.02 grpc-server-0   
19594 root      20   0 4720440 982072  24712 S 48.8  0.7  24:25.61 grpc-server-2      
19398 root      20   0 4575032 944244  24740 S 47.9  0.7  27:23.01 grpc-server-1  
19204 root      20   0 4624184 1.023g  24832 S 43.6  0.8  27:32.22 grpc-server-2    

server 3 run 3 TiKVs  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND          
15120 root      19  -1 4650808 876772  24680 R 84.2  0.7  38:59.30 raftstore-9          
15556 root      19  -1 4663096 998392  24740 R 76.9  0.8  33:34.80 raftstore-451     
15115 root      20   0 4650808 876772  24680 R 73.9  0.7  29:32.74 grpc-server-0    
15340 root      19  -1 4579128 989.1m  24740 R 73.9  0.8  33:02.83 raftstore-130      
15553 root      20   0 4663096 998392  24740 R 73.6  0.8  29:55.15 grpc-server-2     
15117 root      20   0 4650808 876772  24680 S 70.3  0.7  29:28.68 grpc-server-2     
15116 root      20   0 4650808 876772  24680 S 66.7  0.7  26:27.65 grpc-server-1      
15336 root      20   0 4579128 989.1m  24740 R 63.7  0.8  27:43.92 grpc-server-1      
15554 root      20   0 4663096 998392  24740 R 62.7  0.8  27:31.68 grpc-server-3         
15338 root      20   0 4579128 989.1m  24740 S 62.0  0.8  28:48.66 grpc-server-3       
15337 root      20   0 4579128 989.1m  24740 S 61.4  0.8  27:33.70 grpc-server-2     
15335 root      20   0 4579128 989.1m  24740 R 60.1  0.8  26:03.89 grpc-server-0    
15551 root      20   0 4663096 998392  24740 R 57.1  0.8  27:54.64 grpc-server-0     
15131 root      20   0 4650808 876772  24680 S 52.5  0.7  28:46.17 apply worker     
15351 root      20   0 4579128 989.1m  24740 R 52.1  0.8  23:15.55 apply worker      
15552 root      20   0 4663096 998392  24740 R 50.8  0.8  28:26.60 grpc-server-1    
15118 root      20   0 4650808 876772  24680 R 48.2  0.7  24:36.76 grpc-server-3    
15567 root      20   0 4663096 998392  24740 R 47.9  0.8  23:04.54 apply worker

**Comment by siddontang** [comment]
You raftstore CPU nearly 90%.
Now, this is a single thread and can be a bottleneck.

**Comment by Borelset** [comment]
Ok, Thx.

**Comment by Borelset** [comment]
well, another question.
I found that "storage async write duration" in TiKV metrics maybe is a major part of latency.
in 64 thread latency is about 800us, and "storage async write duration" is about 550us
in 64 thread latency is about 1600us, and "storage async write duration" is about 1200us
"storage async write duration" relates to raftstore?

**Comment by siddontang** [comment]
@Borelset 

Yes, this is related to Raft, as you can see, Raftstore is now a single thread, so if you increase the pressure, the latency will increase. 

We will refactor to multi-threads later to fix this problem.

**Comment by siddontang** [comment]
can we close it now @Borelset 

If you meet any problem later, you can file a new issue.

**Comment by Borelset** [comment]
yeah,  thx
