### ISSUE TITLE
check critical config failed

### ISSUE THREAD

**Issue by tydldd** [pingcap/tikv#2880]
问题：
check critical config failed, error "check critical config failed, err StringError(\"db wal_dir have been changed, former db wal_dir is , current db wal_dir is /vpants/tidb/data/store, please guarantee all data wal log have been moved to destination directory.\")"

安装好后，更改tikv的wal-dir目录，重新启动tikv报错。

**Comment by breeswish** [comment]
As the error describes, you need to make sure that WAL logs are moved. After that, you can delete `last-config.toml` to omit this check.

**Comment by Hoverbear** [comment]
I think this is resolved so I'm closing this. Feel free to reopen!
