### ISSUE TITLE
port data of 7.4G

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tikv#2906]
使用loader还原数据 ：
2018/04/02 16:44:58.230 session.go:506: [warning] [39] retryable error: [tikv:9003]TiKV server is busy[try again later], txn: {399155835216330753 <nil> 0xc42a7d0600 map[] [] <nil>}
2018/04/02 16:44:58.285 session.go:474: [warning] [39] Retry [9] query [0]
2018/04/02 16:44:58.286 session.go:474: [warning] [39] Retry [9] query [1]
2018/04/02 16:44:58.297 session.go:474: [warning] [39] Retry [9] query [2]
2018/04/02 16:44:58.366 session.go:474: [warning] [39] Retry [9] query [3]
2018/04/02 16:44:58.372 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{28 1 14} id:28 start_key:"t\200\000\000\000\000\000\000%" end_key:"t\200\000\000\000\000\000\000)" region_epoch:<conf_ver:1 version:14 > peers:<id:29 store_id:1 >  id:29 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:44:58.606 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:44:59.027 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{28 1 14} id:28 start_key:"t\200\000\000\000\000\000\000%" end_key:"t\200\000\000\000\000\000\000)" region_epoch:<conf_ver:1 version:14 > peers:<id:29 store_id:1 >  id:29 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:45:00.040 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{28 1 14} id:28 start_key:"t\200\000\000\000\000\000\000%" end_key:"t\200\000\000\000\000\000\000)" region_epoch:<conf_ver:1 version:14 > peers:<id:29 store_id:1 >  id:29 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:45:00.111 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:01.068 backoff.go:212: [warning] backoffer.maxSleep 20000ms is exceeded, errors:
server is busy, ctx: &{{158 1 79} id:158 start_key:"t\200\000\000\000\000\000\000\251" end_key:"t\200\000\000\000\000\000\000\253" region_epoch:<conf_ver:1 version:79 > peers:<id:159 store_id:1 >  id:159 store_id:1  172.16.0.50:20160}
stale_epoch:<> 
server is busy, ctx: &{{158 1 79} id:158 start_key:"t\200\000\000\000\000\000\000\251" end_key:"t\200\000\000\000\000\000\000\253" region_epoch:<conf_ver:1 version:79 > peers:<id:159 store_id:1 >  id:159 store_id:1  172.16.0.50:20160}
2018/04/02 16:45:01.068 gc_worker.go:565: [warning] [gc worker] 58a158667b00001 failed to do gc on region(t©, t«), ignore it
2018/04/02 16:45:01.071 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{160 1 80} id:160 start_key:"t\200\000\000\000\000\000\000\253" end_key:"t\200\000\000\000\000\000\000\255" region_epoch:<conf_ver:1 version:80 > peers:<id:161 store_id:1 >  id:161 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:45:01.666 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:01.676 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{20 1 10} id:20 start_key:"t\200\000\000\000\000\000\000\023" end_key:"t\200\000\000\000\000\000\000\025" region_epoch:<conf_ver:1 version:10 > peers:<id:21 store_id:1 >  id:21 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:45:01.775 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:02.194 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:02.350 region_request.go:216: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{160 1 80} id:160 start_key:"t\200\000\000\000\000\000\000\253" end_key:"t\200\000\000\000\000\000\000\255" region_epoch:<conf_ver:1 version:80 > peers:<id:161 store_id:1 >  id:161 store_id:1  172.16.0.50:20160}, retry later
2018/04/02 16:45:02.470 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:02.751 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/04/02 16:45:03.273 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by huachaohuang** [comment]
These warnings can happen when TiKV is being written heavily, but TiDB will retry automatically, do you encounter any error on the client side?

**Comment by Hoverbear** [comment]
Hello @dbaspace!

I see there was an answer to this question, and there has been no further activity for two weeks, so I'm going to close it.

Feel free to re-open the issue if there is still a problem.
