### ISSUE TITLE
tikv compile failed on CentOS

### ISSUE THREAD

**Issue by Jacklli** [pingcap/tikv#2907]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
$ rustc --version
rustc 1.25.0-nightly (73ac5d6a8 2018-01-11)

2. What operating system and processor architecture are you using?
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

$ uname -a
Linux host 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$  cat /proc/cpuinfo |grep -E 'cpu|mod'
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-26xx v3
cpu MHz		: 2294.686
cpu cores	: 4
cpuid level	: 13
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-26xx v3
cpu MHz		: 2294.686
cpu cores	: 4
cpuid level	: 13
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-26xx v3
cpu MHz		: 2294.686
cpu cores	: 4
cpuid level	: 13
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-26xx v3
cpu MHz		: 2294.686
cpu cores	: 4
cpuid level	: 13

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

$ pwd
/data/src/github.com/pingcap/tikv
[root@root tikv]# cargo build
   Compiling rustc-serialize v0.3.19
   Compiling rustc_version v0.1.7
   Compiling num-integer v0.1.32
   Compiling kernel32-sys v0.2.2
error[E0642]: patterns aren't allowed in methods without bodies
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

   Compiling dbghelp-sys v0.2.0
   Compiling ws2_32-sys v0.2.1
   Compiling synom v0.11.3
   Compiling crc v1.2.0
   Compiling tokio-timer v0.1.1
   Compiling sys-info v0.5.1
   Compiling toml v0.4.3
   Compiling serde_json v1.0.2
   Compiling num_cpus v1.6.2
error: aborting due to previous error

error: Could not compile `rustc-serialize`.
warning: build failed, waiting for other jobs to finish...
error: build failed

4. What did you expect to see?
compile tikv success.

5. What did you see instead?
compile tikv failed as above described.

**Comment by hicqu** [comment]
TiKV use rustc-serialize with version `0.1.24`. Please run `cargo update --package=rustc-serialize` first.

**Comment by hicqu** [comment]
You can extract the dependencies versions in `Cargo.lock`.

**Comment by blacktear23** [comment]
@hicqu version should be 0.3.24

**Comment by siddontang** [comment]
As I remember, seem that you use the new rust version to build a very old TiKV. If yes, we can close this issue. @Jacklli

**Comment by Jacklli** [comment]
I rebuild the host OS environment, and git clone the source code instead of downloading release source code from github, and then compile successfullly!

**Comment by siddontang** [comment]
Cool @Jacklli 

If you have any problem, please file an issue later.
