### ISSUE TITLE
重启删除TIKV

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tikv#2908]
TIKV 停止了  ，原来数据全部删除，然后重新启动，提示
2018/04/03 09:58:28.006 util.rs:299: [ERROR] fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:5512 address:\"192.168.21.189:20160\" , already registered by id:5460 address:\"192.168.21.189:20160\" state:Offline ") }))
然后登陆pt-ctl 进行删除
    "store": {
        "id": 5460,
        "address": "192.168.21.189:20160",
        "state": 1,
        "state_name": "Offline"
      },
      "status": {
        "capacity": "10 GiB",
        "available": "9.4 GiB",
        "leader_weight": 1,
        "leader_score": 1,
        "region_count": 31,
        "region_weight": 1,
        "region_score": 1733,
        "region_size": 1733,
        "start_ts": "2018-04-03T09:44:29+08:00",
        "last_heartbeat_ts": "2018-04-03T09:46:50.52260963+08:00",
        "uptime": "2m21.52260963s"
      }
    }
  ]
}

» store delete 5460
Success!
» store 5460
{
  "store": {
    "id": 5460,
    "address": "192.168.21.189:20160",
    "state": 1,
    "state_name": "Offline"
  },
  "status": {
    "capacity": "10 GiB",
    "available": "9.4 GiB",
    "leader_weight": 1,
    "leader_score": 1,
    "region_count": 31,
    "region_weight": 1,
    "region_score": 1733,
    "region_size": 1733,
    "start_ts": "2018-04-03T09:44:29+08:00",
    "last_heartbeat_ts": "2018-04-03T09:46:50.52260963+08:00",
    "uptime": "2m21.52260963s"
  }
}
 还是存在  ，导致TIKV无法启动！

**Comment by huachaohuang** [comment]
When you delete a store, the store will be in the "Offline" state, you need to wait until its state becomes "Tombstone" before you can start a new store with the same address.
Ref: https://github.com/pingcap/docs-cn/blob/master/op-guide/horizontal-scale.md#%E5%8A%A8%E6%80%81%E5%88%A0%E9%99%A4%E8%8A%82%E7%82%B9-1

**Comment by dbaspace** [comment]
谢谢  早上没注意那，，，

**Comment by Mynameislyc** [comment]
Is there a way to make it Tombstone state? Or can we just wait?
