### ISSUE TITLE
TIKV throws "no available space" after starting

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tikv#2913]
刚启动的TIKV服务，提示这个  no available space
实际
/dev/sdd1       1.9T  107M  1.9T   1% /disk2  盘空间很大。
[root@glusterfs10 tikv]# ll data
total 4
drwxr-xr-x 2 root root 4096 Apr  3 17:50 db
drwxr-xr-x 4 root root   43 Apr  3 17:50 import
-rw-r--r-- 1 root root    0 Apr  3 17:50 LOCK
drwxr-xr-x 2 root root  148 Apr  3 17:50 raft
drwxr-xr-x 2 root root   10 Apr  3 17:50 snap
drwxr-xr-x 3 root root   49 Apr  3 17:50 wal
 都有这些数据目录 就不知道在哪里找答案

**Comment by dbaspace** [comment]
root      8737  7972  0 17:50 pts/3    00:00:00 /usr/local/tidb/bin/tikv-server --config=/usr/local/tidb/bin/tikv.toml  这个服务在线

**Comment by siddontang** [comment]
can you show the tikv log?

**Comment by dbaspace** [comment]
新启动的节点状态，没任何数据
store 3844
{
  "store": {
    "id": 3844,
    "address": "192.168.21.149:20160",
    "state_name": "Up"
  },
  "status": {
    "capacity": "12 KiB",
    "leader_weight": 1,
    "leader_score": 1,
    "region_weight": 1,
    "region_score": 1,
    "start_ts": "2018-04-04T10:17:37+08:00",
    "last_heartbeat_ts": "2018-04-04T10:25:47.305262296+08:00",
    "uptime": "8m10.305262296s"
  }
}

**Comment by dbaspace** [comment]
磁盘是SAS的 不识别？

**Comment by siddontang** [comment]
```
"capacity": "12 KiB",
```

Do you change TiKV's capacity?

**Comment by dbaspace** [comment]
[storage]
# notify capacity of scheduler's channel
scheduler-notify-capacity = 10240

[server]
# set listening address.
addr = "192.168.21.149:20160"
# if not set, use addr instead. set advertise listening address for client communication.
advertise-addr = ""
# set the path to rocksdb directory.
# notify capacity, 40960 is suitable for about 7000 regions.
notify-capacity = 40960

[raftstore]
sync-log = true
#raftdb-path = "/data/tidb/tikv/CURRENT"
capacity =12000
notify-capacity = 40960
配置文件就这么多参数跟CAPACITY关系

**Comment by siddontang** [comment]
`capacity =12000` is too small, just 12 KB, please set a bigger one, like `500 GB`

**Comment by dbaspace** [comment]
THANK YOU
