### ISSUE TITLE
cannot build tikv

### ISSUE THREAD

**Issue by xinxinsh** [pingcap/tikv#2961]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.21.0-nightly (aac223f4f 2017-07-30)

2. What operating system and processor architecture are you using?
MacOS 10.13.3

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
   1. download tikv from github
   2. make

4. What did you expect to see?
make can compile tikv successfully

5. What did you see instead?

    Updating git repository `https://github.com/stepancheg/rust-protobuf.git`
    Updating git repository `https://github.com/busyjay/jemallocator.git`
error: failed to load source for a dependency on `jemallocator`

Caused by:
  Unable to update https://github.com/busyjay/jemallocator.git?branch=dev#079e31b1

**Comment by xinxinsh** [comment]
cannot find the commit 079e31b1b9c9eccff9bb01afd2eab7f5037d9bf1 in jemallocator repo

**Comment by BusyJay** [comment]
I'm sorry it happened. I just did a quick fix, can you try again?

**Comment by xinxinsh** [comment]
the fix is in tikv repo or  jemallocator repo?

**Comment by BusyJay** [comment]
In jemallocator repo. You should be able to get it compiled by simply issue make again.

**Comment by xinxinsh** [comment]
can you show me the link of the fix, thx

**Comment by BusyJay** [comment]
I just added the missing commit back to the repo.

**Comment by Hoverbear** [comment]
@xinxinsh Did this resolve the issue?

**Comment by breeswish** [comment]
The issue should have been fixed according to the comments above. Closing. If you still face this issue please leave a comment and we will take a deeper look.
