### ISSUE TITLE
Read trait may not be sufficient enough

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tikv#2989]
When using `Read` trait, the bench result shows:
```
test bench_decode_var_u64 ... bench:           4 ns/iter (+/- 0)
```
When access slice directly with some branch optimization, it becomes:
```
test bench_decode_var_u64 ... bench:           1 ns/iter (+/- 0)
```
`deocde_var_u64` is a heavily used function, which often shows up in the flamegraph. Its performance matters a lot. We may need to rewrite all the codec functions to access slice directly.

**Comment by breeswish** [comment]
The buffer length is checked every time for a `read()`. The underlaying data is copied multiple times as well. These operations can be definitely eliminated by avoid using the reader style.
