### ISSUE TITLE
Feature to not split ranges based on size-bounded key-prefixes for nicer performance

### ISSUE THREAD

**Issue by ddorian** [pingcap/tikv#2991]
When you know that your ranges won't grow too big, you may want to be sure a given key-prefix will always be 1 one range, for nicer write transactions (single server/region) and nicer read (single server).

When you have a set with 10 values, you keep it in 1 kv serialized. A set with 100K values, you keep it in 1 range. An unbounded set that can forever grow, you allow it to split for horizontal scaling.

This way you get a benefit of consistent hashing partitioning that you'll be certain requests will hit 1 range/node.

This can be ported on mysql layer to keep some per-user rows in 1 region, or redis-layer to keep 1 set/map/zset in 1 region and have better predictable performance as long as you know the data is bounded. So 1 range can keep multiple set(), but a set() can't be split on multiple regions.

Makes sense ?

**Comment by ngaut** [comment]
Yes, that make sense, since tikv has supported plugable  coprocessor, you can do almost everything you want.

To add you own split strategy, you can build a customize coprocessor(split checker), please ref https://github.com/pingcap/tikv/blob/master/src/raftstore/coprocessor/split_check/half.rs#L78
