### ISSUE TITLE
Coverage badge outdated

### ISSUE THREAD

**Issue by codeworm96** [pingcap/tikv#3012]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
N/A

2. What operating system and processor architecture are you using?
N/A

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
Just look at the coverage badge

4. What did you expect to see?
It shows the coverage of the latest commit of the master branch.

5. What did you see instead?
The coverage was updated on 13 Aug 2017, more than half a year ago.

It seems the coverage badge has not been updated since 13 Aug 2017. (After the switch from travis-ci to circle-ci?

If needed, I would like to fix it after #2993 is merged.

**Comment by ngaut** [comment]
Thank you, please feel free to do it.

**Comment by overvenus** [comment]
Hi @codeworm96 !

We have merged #2993 in the last week, I think you can go on. We used to have a coverage report, #613, maybe it would help. Or you can try something new, the [tarpaulin](https://github.com/xd009642/tarpaulin). Let me know if there's anything I can do. :)

**Comment by codeworm96** [comment]
I have started working on [this](https://github.com/codeworm96/tikv/tree/coverage), and successfully made the kcov run. But I failed to upload the result to coveralls (TRAVIS_JOB_ID is not available any more), coveralls has little document about integration with CirclesCI. I think I need some time to solve the problem.

tarpaulin sounds like a good choice, I will have a try.

BTW, can we try some new coverage service? It seems codecov is supported by kcov and tarpaulin, too.

**Comment by overvenus** [comment]
FYI, I tested tarpaulin with codecov and circleci, they work smoothly, a simple example can be found at https://github.com/overvenus/keygraph-rs/pull/1 .

**Comment by codeworm96** [comment]
Cool. After applying some workaround (https://github.com/xd009642/tarpaulin/issues/112),
tarpaulin works fine. I also tried kcov, but it seems have more overhead and is more likely to make tests timeout and fail.

I may split the coverage calculation in a separated job in a following commit, since it takes a long time. And the badge should be replaced with codecov badge, too.
