### ISSUE TITLE
Improve performance of decoding table row

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#3032]
Currently we are heavily depends of HashSet and HashMap while decoding a row(cut_row), which do some unnecessary allocation and hash computing. Since the key is always i64/u64, and the element count is small. we can implement a highly optimize/customize a HashSet/HashMap with a internal vector.

**Comment by BusyJay** [comment]
It depends on the number of columns. After changing from fnv to fx hash, the cost of hash can be negligible.
