### ISSUE TITLE
use a fast and workaround way to relieve the problem of Dropping Table/Index, etc, temporarily

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#3034]
Now when the user drops table/index, etc, the internal DeleteRange command will block the apply worker and cause a high latency for the cluster. 

Although we have #2960 to solve the problem, this PR may still be tested for a long time. Now we have been OnCall for this problem many times and I think we need to find an easy but not perfect way to work around it. 

We know that the DeleteRange contains 1. DeleteFilesInRanges + 2. Scan region + Delete left data, the step 2 will block the apply worker, so we can remove it, but this may cause the problem that we will leave some stale data in the cluster, so we need to clear this stale data later. some ways:

1. Scan whole TiKV regions and find if there is a region contains the stale data, clean up. We can decode the region range, get the table ID and find the table still exists or not, or some other optimizations.
2. Record all DDL operations in history, find them directly and do the cleanup work. 

Of course, these ways are not perfect, but here we need to relieve the problem ASAP. 

/cc @zhangjinpeng1987 @BusyJay

**Comment by zhangjinpeng1987** [comment]
Previously i implemented a branch to use a individual thread to handle DeleteRange(Cleanup stale ranges) asynchronously.
1) Apply worker send a cleanup task to a persistent task queue after step 1. DeleteFilesInRanges.
2) Cleanup worker consume cleanup stale task, handle step 2 asynchronously.
I think this is more clear and simple, i prefer this solution.

**Comment by siddontang** [comment]
Cool, we can use this as a workaround way now.

**Comment by zhangjinpeng1987** [comment]
After discussing with @BusyJay , we came to a better solution:
1) TiKV only do DeleteFilesInRanges that mentioned above.
2) Instead of delete the key range from system table `mysql.gc_delete_range` after DeleteRange requests have been done, we mark these key ranges as `done` status.
3) After TiKV has fix the issue of applying cleanup a range will block apply worker(apply pool), resume the original logic of step 2.
