### ISSUE TITLE
tikv_engine_seek duration is too high

### ISSUE THREAD

**Issue by lerencao** [pingcap/tikv#3042]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

```
$ ~/.cargo/bin/rustup toolchain list
nightly-2018-04-10-x86_64-unknown-linux-gnu (default)
```

2. What operating system and processor architecture are you using?

```
$ cat /etc/*release
CentOS release 6.9 (Final)
CentOS release 6.9 (Final)
CentOS release 6.9 (Final)
```

```
processor	: 39
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping	: 1
microcode	: 184549409
cpu MHz		: 2194.914
cache size	: 25600 KB
physical id	: 1
siblings	: 20
core id		: 12
cpu cores	: 10
apicid		: 57
initial apicid	: 57
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx cqm_llc cqm_occup_llc
bogomips	: 4389.52
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

KV's seek duration of a tikv server goes very high, about 1 order of magnitudes, see the `Seek duration` section below:

![image](https://user-images.githubusercontent.com/1456096/39752495-37375728-52ee-11e8-9d6a-0acaab2b91df.png)

This cause the scheduler's cpu usage also goes high.
And **tidb got `ServerIsBusy` error**.

```
2018/05/08 16:00:43.010 region_request.go:220: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{375800 103 670} id:375800 start_key:"t\200\000\000\000\000\000\000\235_i\200\000\000\000\000\000\000\001\001024159b0\37760bd4c41\37788831c6c\377fe744b53\377#d6589dd\377bbd7c474\377c8f34cd2\377ec295fdc\377d\000\000\000\000\000\000\000\370" end_key:"t\200\000\000\000\000\000\000\235_i\200\000\000\000\000\000\000\001\00102d232bf\3776e49425d\3778e43ee8b\3777493f302\377#69a9194\37783f594bc\3771a15d4aa\377f846c486\3775\000\000\000\000\000\000\000\370" region_epoch:<conf_ver:103 version:670 > peers:<id:375801 store_id:11 > peers:<id:375802 store_id:13 > peers:<id:375803 store_id:10 >  id:375802 store_id:13  10.1.169.198:20175}, retry later
```

![image](https://user-images.githubusercontent.com/1456096/39752757-f924f408-52ee-11e8-8fdc-c7501493f96a.png)

Also, one strange thing is during 14:00~14:10 there is no `gc` request.

Raft's seek duration keep unchanged.

![image](https://user-images.githubusercontent.com/1456096/39752619-94e2feb8-52ee-11e8-9a8a-6e12a941d600.png)

Without any clue, I  stopped the tikv server, and restarted it about 15min later, it went well again.

4. What did you expect to see?

5. What did you see instead?

**Comment by hicqu** [comment]
Seems your TiDB has lots of old version records. Is there any `UPDATE` queries?

**Comment by lerencao** [comment]
Yes, you're right. `update` is frequency. 
After I increased the gc concurrency from default 1 to 3, the seek time recovered, and the total gc time decreased from dozens of minutes to several minutes.

Thanks very much!

**Comment by Hoverbear** [comment]
@lerencao I'm glad you resolved this! I'm going to close this issue, please feel welcome to reopen the issue if you experience more problems.
