### ISSUE TITLE
Coprocessor default read pool size may not taking effect

### ISSUE THREAD

**Issue by breeswish** [pingcap/tikv#3056]
For the following config, it works:

```toml
# intentionally leave empty.
```

For the following config, it breaks:

```toml
[readpool.coprocessor]
```

**Comment by breeswish** [comment]
Opened an issue in serde: https://github.com/serde-rs/serde/issues/1254

If serde can solve this issue it would be great. However if it is "won't fix", we need workarounds.

**Comment by BusyJay** [comment]
That's why there are three different structs for three rocksdb cfs' configuration.

**Comment by BusyJay** [comment]
Looks like some tests are missing.

**Comment by breeswish** [comment]
@busyjay Yes, I'm proposing a PR to fix this with some tests for default values.
