### ISSUE TITLE
'How to use TiKV' is now unavailable

### ISSUE THREAD

**Issue by EighteenZi** [pingcap/tikv#3065]
> Is it easy to use TiKV?
> Yes. For further information, see How to use TiKV.

The linkage under 'How to use TiKV' is unvailable now, it leads to a 404 error page.

**Comment by EighteenZi** [comment]
I am investigating the TiKV, to get it used in our applymentation to replace another KVDB.

Is there anybody who can help me? Or give me a new weblink?

Thanks a lot.

**Comment by EighteenZi** [comment]
@gregwebs @weekface @guanqun @andelf @mccxj 
May you help me on this?

**Comment by Hoverbear** [comment]
Hi @EighteenZi!

I'm sorry the link is broken. I see that the link you're speaking about is in the [FAQ](https://github.com/pingcap/tikv/wiki/TiKV-FAQ) which hasn't been updated for a few years.

@queenypingcap Do you happen to know where the document in question is?

**Comment by queenypingcap** [comment]
Hi @EighteenZi ,
I have fixed the link and now it points to [TiDB Quick Start Guide](https://github.com/pingcap/docs/blob/master/QUICKSTART.md). Sorry about the broken link. Just in case you are interested, we are now working on a separate document for TiKV as well.

**Comment by Hoverbear** [comment]
@queenypingcap Unfortunately that topic is more about how to use TiDB. :(

This ticket won't

**Comment by EighteenZi** [comment]
@Hoverbear ,yes ,i have saw the guide, it is more about TiDB.
What i need is a KVDB, not a SQLDB. I want to use TiKV seperately. :(

**Comment by queenypingcap** [comment]
@EighteenZi We are working on it. Will update this issue when it's done.

**Comment by Hoverbear** [comment]
@EighteenZi I do too! :)

**Comment by Hoverbear** [comment]
@EighteenZi I did find this example to get your started if you're feeling impatient. :)

```go
package main

import (
    "github.com/pingcap/tidb/config"
    "github.com/pingcap/tidb/store/tikv"
    "fmt"
)

func main(){
    cli, err := tikv.NewRawKVClient([]string{"localhost:2379"}, config.Security{})
    if err != nil {
        panic("Failed to create the RawKVClient")
    }
    fmt.Printf("cluster ID: %d\n", cli.ClusterID())
    key := []byte("Key")
    val := []byte("Value")
    err = cli.Put(key, val)
    if err != nil {
         panic(err)
    }
    fmt.Printf("Successfully put %s:%s to tikv\n", key, val)

    val, err = cli.Get(key)
    if err != nil {
         panic(err)
    }
    fmt.Printf("found val: %s for key: %s\n", val, key)
    cli.Close()
}
```

**Comment by EighteenZi** [comment]
@Hoverbear  
Thanks a lot.
The example above shows usage of inserts and gets of TiKV , and i can have a try.

The language is Go, Is there some Rust examples?

**Comment by gregwebs** [comment]
There are only Go and Java drivers written right now. I am hoping a Rust driver will materialize in the near future.

**Comment by siddontang** [comment]
@gregwebs 

I discussed it with @Hoverbear this morning, and he will start it soon.

**Comment by Hoverbear** [comment]
Indeed, a Rust based driver is on my roadmap now. :)

**Comment by queenypingcap** [comment]
@EighteenZi The TiKV document is finished. See https://pingcap.com/docs/tikv/tikv-overview/ for more information.

**Comment by EighteenZi** [comment]
Awesome!!  I am so excited!
I'll read it.

**Comment by EighteenZi** [comment]
@Hoverbear , Once the rust based driver is OK, pls remind me if it's convenient to you.
Thanks.

**Comment by gregwebs** [comment]
I added a that link to the FAQ. @queenypingcap I would suggest just having the wiki not have content but instead point to PingCAP docs so that everything is in one place. Perhaps some of the wiki FAQ content should be put under the TiKV documentation.

@EighteenZi should we close this issue now?

**Comment by EighteenZi** [comment]
@Hoverbear  @siddontang  @gregwebs , have the Rust Driver been finished?
I look forward to using TiKV these days :)

**Comment by gregwebs** [comment]
This issue was for a documentation fix, so lets keep it closed. The Rust driver will take some time. Generally we don't open github issues to track new features but instead maintain a public roadmap (which probably needs to be updated now). https://github.com/pingcap/docs/blob/master/ROADMAP.md

**Comment by EighteenZi** [comment]
I don't find any description of Rust Driver in 'ROUADMAP.md'. Maybe it needs to be updated as you say.

**Comment by Hoverbear** [comment]
@EighteenZi I created the repo if you'd like to watch it. :) https://github.com/Hoverbear/tikv-client, It'll be moved to @pingcap later.

**Comment by EighteenZi** [comment]
@Hoverbear  Nothing have been committed to the repo since then... -_-!

**Comment by Hoverbear** [comment]
@EighteenZi I know. :( We released a new version of TiKV with Raft Prevote and we found some issues. 

This is officially on my roadmap for this next quarter (I cemented it with the team yesterday) so it's coming!

**Comment by EighteenZi** [comment]
hello？

**Comment by gregwebs** [comment]
@EighteenZi great news: the Rust client is materializing. The RFC for the API is in final comment period here: https://github.com/tikv/rfcs/pull/7 and the Rust driver code should be available soon afterwards.

**Comment by EighteenZi** [comment]
Cool!

**Comment by Hoverbear** [comment]
Repo: https://github.com/tikv/client-rust
