### ISSUE TITLE
Use rust-toolchain file instead of RUST_VERSION

### ISSUE THREAD

**Issue by sanxiyn** [pingcap/tikv#3066]
[The toolchain file](https://github.com/rust-lang-nursery/rustup.rs#the-toolchain-file) is the standard way to specify such information supported by rustup.

This is not a pull request because I don't know how to handle Jenkins CI...

**Comment by Hoverbear** [comment]
Thanks for raising this @sanxiyn. I'll tackle this. :)

**Comment by breeswish** [comment]
Good catch! I like this solution.

**Comment by breeswish** [comment]
@Hoverbear I added HelpWanted tag so that contributions are welcome for this as well :)
