### ISSUE TITLE
Check compatibility with protobuf 1.6

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tikv#3067]
Protobuf 1.6 set unrecognized enum value to unknown field values. TiKV currently doesn't handle any unknown field values, that means when rolling upgrading tikv, it's possible that different instances can get different apply results if they are using different protocols. It's not an issue in the past (and now), because previous version will panic directly, so new command type won't be dropped as error accidentally.

This is just one compatibility issue I recall, we may need to check whether there are other issues that can be introduced by upgrading it. Before they are all resolved, we should lock to current version.

**Comment by Hoverbear** [comment]
Hi @hicqu is there any way I can help you with this? I see it's a dependency for #3133 which I'm working on. :)

**Comment by Hoverbear** [comment]
Hi @BusyJay, was https://github.com/pingcap/raft-rs/pull/75 related to this?
