### ISSUE TITLE
Unsafe recover should only drop some nodes instead of all down nodes

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tikv#3092]
For example, A region contains six nodes a, b, c, d, e and f, a is leader. If a, b and c are down forever, we need to just delete two nodes instead of all three nodes. It's possible that just a, b, c and d share the committed log. If a, b, c are deleted, d's committed log can be overridden if e or f becomes leader. Note that d may even not know that a has committed the log, so the cluster can run smoothly without knowing that committed logs are lost, which can be prevented in this case.

**Comment by BusyJay** [comment]
It's not fixed yet.

**Comment by pxps** [comment]
I don't know how your raft library solves the problem in paragraph 5.4.2. My solution is to add some restrictions on the response of the requstvote RPC.

**Comment by BusyJay** [comment]
This is not the same problem in 5.4.2. Raft itself guarantees that logs committed from last term will never get overwritten as long as majority still alive. However the problem described here is at least half of the nodes are down and ruined forever that those nodes have to be removed from the meta manually. This case can't be solved by raft itself automatically, extra effort is required.

A node can become a leader once quorum vote for it. So a candidate can never know for sure if there is a node whose log is more up to date. If it has to wait for all nodes to answer the vote request, then the implementation can't defect network partition.

**Comment by pxps** [comment]
On this issue, I think there are two solutions. First, add a coordination layer on the PD. Second, Raft guarantees that each submitted log can be saved to most of the nodes. As long as the people who have all the logs are running successfully, I can do it. Of course, further testing is needed after implementation. I am particularly interested in this question and have the opportunity to chat by phone. ^_^

**Comment by siddontang** [comment]
hi @pxps 

> if it finds that the lastlogindex and lastlogterm of some nodes are greater than their own

Seem that the node will response a reject message.

**Comment by siddontang** [comment]
hi @pxps 

> if it finds that the lastlogindex and lastlogterm of some nodes are greater than their own

Seem that the node will response a reject message.
