### ISSUE TITLE
last_tikv.toml may break

### ISSUE THREAD

**Issue by breeswish** [pingcap/tikv#3100]
when last_tikv.toml has different field types, TiKV should not panic: `thread 'main' panicked at 'invalid auto generated configuration file "/data1/bjbank/tidb_cluster/tikv2/d
ata/last_tikv.toml"`.

**Comment by BusyJay** [comment]
That means we should never change a field's type after releasing. Add a new field instead.

**Comment by breeswish** [comment]
Can we make tests? This is in fact a runtime error. We should be able to avoid it before release.

**Comment by BusyJay** [comment]
There are tests already. The error due to upgrade from an unstable experimental feature branch.

**Comment by breeswish** [comment]
Ok
