### ISSUE TITLE
Support unescape hex like keys

### ISSUE THREAD

**Issue by breeswish** [pingcap/tikv#3149]
Our pd-ctl produce keys in hex format, like `t\x80\x00\x00\x00\x00\x00\x00\xff\xdc_r\x80\x00\x00\x006\xff\x95\xb7\x86\x00\x00\x00\x00\x00\xfa`. We cannot unescape this format for now, which is inconvenient to be used in tikv-ctl.

**Comment by BusyJay** [comment]
I think they are supported already: https://github.com/pingcap/tikv/blob/master/src/bin/tikv-ctl.rs#L853.

**Comment by breeswish** [comment]
@BusyJay They are different formats in fact..

The format pd-ctl outputs:

- printable characters are not escaped (like "_r")
- non-printable characters are in hex and has a prefix "\x".

**Comment by disksing** [comment]
It is the Go format of string literals: https://golang.org/ref/spec#String_literals. And it is also the format to format a string with "%q" in Go.

**Comment by BusyJay** [comment]
Yes. But what we are talking about is the components of TiDB project. :smiley_cat: By the way, the format we are using is also used by protobuf.

**Comment by breeswish** [comment]
I think definitely we need a unified format when outputting / inputting keys across all TiDB software stacks.

**Comment by disksing** [comment]
tidb and pd can parse both '\ddd' and '\xXX' format, as they are both valid string literals in Go. If a string is inside a protobuf message, the out format will be '\ddd'. Other than this, it will generally be '\xXX', because it is the default format when print a string in Go.
I did not investigate other components.These descriptions are limited to tidb and pd.

**Comment by BusyJay** [comment]
OK, sounds like the simplest solution will be supporting such format in [unescape function](https://github.com/pingcap/tikv/blob/master/src/util/mod.rs#L213).

**Comment by breeswish** [comment]
@BusyJay Yes! And it should be pretty easy to do. We can handle it to contributors.
