### ISSUE TITLE
 Compiling tikv v2.1.0-alpha.1 errors

### ISSUE THREAD

**Issue by Pslydhh** [pingcap/tikv#3158]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.26.0-nightly (5508b2714 2018-03-18)

2. What operating system and processor architecture are you using?
Linux iZwz989756yjbwoyizlmxiZ 4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
cargo test --release

4. What did you expect to see?
just execute default test cases..

5. What did you see instead?

`root@iZwz989756yjbwoyizlmxiZ:/usr/srcfiles/RustPro/tikv-master# cargo -V
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)
drwxr-xr-x 13 root root  4096 Jun  6 12:16 ./
drwxr-xr-x  8 root root  4096 Jun  6 12:13 ../
drwxr-xr-x  7 root root  4096 Jun  6 12:13 benches/
-rw-r--r--  1 root root  2066 Jun  6 12:13 build.rs
-rw-r--r--  1 root root 79127 Jun  6 12:13 Cargo.lock
-rw-r--r--  1 root root  2665 Jun  6 12:13 Cargo.toml
-rw-r--r--  1 root root  8095 Jun  6 12:13 CHANGELOG.md
drwxr-xr-x  2 root root  4096 Jun  6 12:13 ci-build/
drwxr-xr-x  2 root root  4096 Jun  6 12:13 .circleci/
-rw-r--r--  1 root root  2373 Jun  6 12:13 CONTRIBUTING.md
drwxr-xr-x  2 root root  4096 Jun  6 12:13 docker/
-rw-r--r--  1 root root   234 Jun  6 12:13 Dockerfile
-rw-r--r--  1 root root     4 Jun  6 12:13 .dockerignore
drwxr-xr-x  2 root root  4096 Jun  6 12:13 etc/
drwxr-xr-x  3 root root  4096 Jun  6 12:13 fuzz/
drwxr-xr-x  2 root root  4096 Jun  6 12:13 .github/
-rw-r--r--  1 root root   296 Jun  6 12:13 .gitignore
drwxr-xr-x  2 root root  4096 Jun  6 12:13 images/
-rw-r--r--  1 root root   327 Jun  6 12:13 Jenkinsfile
-rw-r--r--  1 root root 11294 Jun  6 12:13 LICENSE
-rw-r--r--  1 root root  2557 Jun  6 12:13 Makefile
-rw-r--r--  1 root root  8207 Jun  6 12:13 README.md
-rw-r--r--  1 root root    25 Jun  6 12:13 rustfmt.toml
-rw-r--r--  1 root root    82 Jun  6 12:13 RUST_VERSION
drwxr-xr-x 10 root root  4096 Jun  6 12:13 src/
drwxr-xr-x  3 root root  4096 Jun  6 12:16 target/
drwxr-xr-x 13 root root  4096 Jun  6 12:13 tests/

root@iZwz989756yjbwoyizlmxiZ:/usr/srcfiles/RustPro/tikv-master# cargo test --release
   Compiling tikv v2.1.0-alpha.1 (file:///usr/srcfiles/RustPro/tikv-master)
error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/server/service/debug.rs:402:6
    |
402 | ) -> impl Future<Item = RegionDetailResponse, Error = Error> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/server/service/debug.rs:439:6
    |
439 | ) -> impl Future<Item = (), Error = Error> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/server/snap.rs:119:13
    |
119 | ) -> Result<impl Future<Item = SendStat, Error = Error>> {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/server/snap.rs:250:6
    |
250 | ) -> impl Future<Item = (), Error = Error> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
  --> src/server/mod.rs:67:45
   |
67 |     pub fn respond_stream<S>(self, s: S) -> impl Future<Item = (), Error = mpsc::SendError<T>>
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable
`

**Comment by siddontang** [comment]
Hi @Pslydhh 
Please follow https://github.com/pingcap/tikv#configuring-your-rust-toolchain and use the specified version to build TiKV.

**Comment by Pslydhh** [comment]
@siddontang Thank you, it works.
