### ISSUE TITLE
How to find out the migration of tikv’s data  is happening？

### ISSUE THREAD

**Issue by denghuancong** [pingcap/tikv#3174]
cluster info：
tikv:v2.0.1， docker deployment
base x86_64， centos 7.4
three tikv node deploy in three physical machine.
```
// one node info using :./pd-ctl store -d -u http://ip:port

      "capacity": "1.1 TiB",
        "available": "1.1 TiB",
        "leader_count": 8,
        "leader_weight": 1,
        "leader_score": 8,
        "leader_size": 8,
        "region_count": 22,
        "region_weight": 1,
        "region_score": 22,
        "region_size": 22,
        "start_ts": "2018-05-30T18:03:43+08:00",
        "last_heartbeat_ts": "2018-06-08T15:29:52.313534815+08:00",
        "uptime": "213h26m9.313534815s"

```

We want to check when add another tikv node into cluster，the cluster whether migration the region data to the new one，but look around all the doc cann't found something.
We also  want to simulate when the capacity of all the tikv node is full , and add another tikv node into, what will happen.

**Comment by breeswish** [comment]
You can take a look at our grafana metrics, mainly pd dashboard, which will indicate how many pending regions are there, and also the region balance ratio.

**Comment by denghuancong** [comment]
If we don't use grafana metrics , just using tidb/tikv/pd,  we manage the scale-out on myself, how should I know the size of one tikv node using  or the size of the tidb cluster  using?

**Comment by breeswish** [comment]
You can use pd-ctl to retrieve store (TiKV instance) sizes:

```
./pd-ctl -u xxxx -d store
```

**Comment by denghuancong** [comment]
thanks a lot, that's  very helpful

**Comment by denghuancong** [comment]
thanks a lot . very helpful !
