### ISSUE TITLE
About concurrency of ctx.on_tick

### ISSUE THREAD

**Issue by Pslydhh** [pingcap/tikv#3195]
As I explore the thread pool of tikv，I find that In the tikv's threadpool(src/util/threadpool.rs)，worker threads take ctx.on_tick() in two places，one could be concurrent，just when have done enough tasks continuely：
<pre><code>
loop {
            let task = match self.next_task() {
                None => return,
                Some(t) => t,
            };

            self.ctx.on_task_started();
            (task.task).call_box((&mut self.ctx,));
            self.ctx.on_task_finished();
            self.task_count.fetch_sub(1, AtomicOrdering::SeqCst);
            if self.task_counter == self.tasks_per_tick {
                self.task_counter = 0;
                self.ctx.on_tick();
            }
        }
</pre></code>
the other one is Serialized(Locked)，when before wait for task forever：
<pre><code>
        let &(ref lock, ref cvar) = &*self.state;
        let mut state = lock.lock().unwrap();
        ..............................
        loop {
            match state.queue.pop() {
                     .....................
                            self.task_counter = 0;
                            self.ctx.on_tick();
                            cvar.wait(state).unwrap()
                     .................
                }
            }
        }
</pre></code>
**So my question is that all on_tick's implemention is concurrency safely? or someone is not?**
I have some new approaches to the thread pool.

**Comment by breeswish** [comment]
Context is a single-worker(thread) concept, which is never shared for multiple threads. The context does not need to be `Sync`, because it is invoked from a fixed thread.

So for your answer, `on_tick` does not need to be `Sync`.
