### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zhangquan0126** [pingcap/tikv#3242]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?

rustc 1.28.0-nightly (41affd03e 2018-06-04)

2. What operating system and processor architecture are you using?

Ubuntu 16.04

3. What did you do?
If possible, provide a recipe for reproducing the error.
Make release under tikv

A complete runnable program is good.

4. What did you expect to see?

Build finishes
5. What did you see instead?

Compiling rocksdb v0.3.0 (https://github.com/pingcap/rust-rocksdb.git#2a150c32)
error[E0658]: procedural macros cannot expand to modules (see issue #38356)
  --> src/server/metrics.rs:17:1
   |
17 | / make_static_metric! {
18 | |     pub label_enum GrpcTypeKind {
19 | |         kv_get,
20 | |         kv_scan,
...  |
50 | |     }
51 | | }
   | |_^
   |
   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/server/metrics.rs:64:66
   |
64 |       pub static ref GRPC_MSG_HISTOGRAM_VEC: GrpcMsgHistogramVec = register_static_histogram_vec!(
   |  __________________________________________________________________^
65 | |         GrpcMsgHistogramVec,
66 | |         "tikv_grpc_msg_duration_seconds",
67 | |         "Bucketed histogram of grpc server messages",
68 | |         &["type"],
69 | |         exponential_buckets(0.0005, 2.0, 20).unwrap()
70 | |     ).unwrap();
   | |_____^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/server/metrics.rs:71:67
   |
71 |       pub static ref GRPC_MSG_FAIL_COUNTER: GrpcMsgFailCounterVec = register_static_int_counter_vec!(
   |  ___________________________________________________________________^
72 | |         GrpcMsgFailCounterVec,
73 | |         "tikv_grpc_msg_fail_total",
74 | |         "Total number of handle grpc message failure",
75 | |         &["type"]
76 | |     ).unwrap();
   | |_____^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error[E0658]: procedural macros cannot expand to modules (see issue #38356)
  --> src/storage/engine/metrics.rs:19:1
   |
19 | / make_static_metric! {
20 | |     pub label_enum RequestStatusKind {
21 | |         all,
22 | |         success,
...  |
53 | |     }
54 | | }
   | |_^
   |
   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/storage/engine/metrics.rs:74:9
   |
74 | /         register_static_int_counter_vec!(
75 | |             AsyncRequestsCounterVec,
76 | |             "tikv_storage_engine_async_request_total",
77 | |             "Total number of engine asynchronous requests",
78 | |             &["type", "status"]
79 | |         ).unwrap()
   | |_________^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/storage/engine/metrics.rs:82:9
   |
82 | /         register_static_histogram_vec!(
83 | |             AsyncRequestsDurationVec,
84 | |             "tikv_storage_engine_async_request_duration_seconds",
85 | |             "Bucketed histogram of processing successful asynchronous requests.",
86 | |             &["type"],
87 | |             exponential_buckets(0.0005, 2.0, 20).unwrap()
88 | |         ).unwrap()
   | |_________^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error[E0658]: procedural macros cannot expand to modules (see issue #38356)
  --> src/storage/mvcc/metrics.rs:17:1
   |
17 | / make_static_metric! {
18 | |     pub label_enum MvccConflictKind {
19 | |         prewrite_write_conflict,
20 | |         commit_lock_not_found,
...  |
36 | |     }
37 | | }
   | |_^
   |
   = help: add #![feature(proc_macro_gen)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/storage/mvcc/metrics.rs:51:9
   |
51 | /         register_static_int_counter_vec!(
52 | |             MvccConflictCounterVec,
53 | |             "tikv_storage_mvcc_conflict_counter",
54 | |             "Total number of conflict error",
55 | |             &["type"]
56 | |         ).unwrap()
   | |_________^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)
  --> src/storage/mvcc/metrics.rs:59:9
   |
59 | /         register_static_int_counter_vec!(
60 | |             MvccDuplicateCmdCounterVec,
61 | |             "tikv_storage_mvcc_duplicate_cmd_counter",
62 | |             "Total number of duplicated commands",
63 | |             &["type"]
64 | |         ).unwrap()
   | |_________^
   |
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable

error: aborting due to 9 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `tikv`.

**Comment by breeswish** [comment]
which rust version are you using?

**Comment by breeswish** [comment]
Please try with the rust version we provided in `RUST_VERSION` file (see README). We have not adapted to the latest rust nightly yet.
