### ISSUE TITLE
Show log location

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tikv#3257]
After switching to slog, log location is gone which is quite useful. Maybe a customized `FullFormat` need to be implemented.

**Comment by breeswish** [comment]
Notice that log date format (`Jun 29 20:00:43.852`) is also different from the rest of the system (`2018/06/22 22:16:24.725`) and previous ones, which will also introduce many inconvenience when tracing clients' issues. See https://github.com/pingcap/tikv/issues/3261 for samples.
