### ISSUE TITLE
Client CLI?

### ISSUE THREAD

**Issue by AkihiroSuda** [pingcap/tikv#329]
Hi,

I could not find the client CLI either in pingcap/tikv or in pingcap/ticlient.

Is there any plan for the client CLI?

I think CLI is useful when a user wants to verify whether he/she successfully deployed TiKV cluster before deploying TiDB.

It should be also useful for interactive debugging purpose.

**Comment by siddontang** [comment]
Hi @AkihiroSuda 

We will support Restful API (https://github.com/pingcap/tikv/issues/258) later for TiKV, so you can use common http tool like curl to verify it. 

We will also support a CLI later wrapping these Restful APIs.

**Comment by AkihiroSuda** [comment]
OK, thank you for quick answer!

**Comment by zitudu** [comment]
@siddontang The issue was closed and there is still no RESTFUL APIs. Is there any progress/plan for CLI or RESTFUL? Thx.
