### ISSUE TITLE
CI is not failed when there is clippy issues

### ISSUE THREAD

**Issue by breeswish** [pingcap/tikv#3300]
## Bug Report

We added back clippy in commit https://github.com/pingcap/tikv/commit/571aa662878bcafe4ad5ec0ebd63afe0baecff05 and later we have another commit https://github.com/pingcap/tikv/commit/238a2fd59430366f122d93480bcc032826107a71 causing clippy warnings. According to the CI result, the later commit passed, which is not desired.

**Comment by BusyJay** [comment]
Turns out there is a bug in clippy: https://github.com/rust-lang-nursery/rust-clippy/pull/2863, let's update to a more recent version.
