### ISSUE TITLE
how to remove logs ?

### ISSUE THREAD

**Issue by carr123** [pingcap/tikv#3326]
when i create a tikv client with tikv.NewRawKVClient( ).
it automatically prints on console the following logs:

time="2018-07-12T14:06:38+08:00" level=info msg="[pd] create pd client with endpoints [175.16.1.50:2379 175.16.1.53:2379 175.16.1.54:2379]"
time="2018-07-12T14:06:38+08:00" level=info msg="[pd] leader switches to: http://175.16.1.50:2379, previous: "
time="2018-07-12T14:06:38+08:00" level=info msg="[pd] init cluster id 8576091382420269395"

how can i switch off those logs printing ?

thanks.

**Comment by Hoverbear** [comment]
Hi! Closing this as it is a solved question. If your question remains unanswered please reopen it.
