### ISSUE TITLE
tikv storage capacity expansion

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tikv#3331]
HI:
    请问下，没有做LVM 的情况下，扩容了一块新的硬盘。原先的TIDV 部署在  /home     /dev/sda1
新扩容的盘为 /data  /dev/sda1   . TIKV 能在一台上支持多个存储目录吗？

**Comment by siddontang** [comment]
you can run another TiKV on the new storage.

**Comment by shenlijungg** [comment]
How to configure    ？

**Comment by breeswish** [comment]
Please see our "单机多 TiKV 实例集群拓扑" section in the doc: https://pingcap.com/docs-cn/op-guide/ansible-deployment/
