### ISSUE TITLE
Does TIKV support TTL?

### ISSUE THREAD

**Issue by winjeg** [pingcap/tikv#3337]
我只搜到了 tidb 的 ttl 支持相关的内容, tidb 不支持ttl可以理解
tikv 与tidb本身就是两个层面的东西, rocksdb 本身也是支持ttl的,  如果在tikv 上层构建其他协议, 如redis 协议, 对于ttl 支持的需求就比较重,  但目前来看并未发现tikv 支持ttl.
如果采取其他方法如
https://github.com/yongman/tidis/blob/master/tidis/ttl.go#L46
去实现ttl 的功能,在数据量大到一定程度的时候 估计会有问题
我觉得最好还是tikv 给出底层ttl 支持的原生实现

**Comment by winjeg** [comment]
Need translation ???

**Comment by siddontang** [comment]
TTL is not on our roadmap this year. 

For MVCC, every key has a version, so you can use a background thread to scan all keys and do it by yourself now.

**Comment by winjeg** [comment]
ok, thanks.
To scan all keys takes much time and may cause some uncertainty.
So I think I 'll  just wait for the original support from tikv.
