### ISSUE TITLE
Don't use space in the thread name

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#3347]
Now some of our threads' name contains space like "apply worker", this is not friendly for us to parse n the perf script or ftrace result, e.g.

```
perf script -F comm,pid,tid,cpu,time

time-monitor-wo 79618/79634 [007] 11994704.695317:
  grpc-server-1 79618/79954 [006] 11994704.717969:
   apply worker 79618/79969 [010] 11994704.718048:
```

We can't use `awk` to parse the result easily.

**Comment by breeswish** [comment]
Already working on this.
