### ISSUE TITLE
simulator for teasing out race conditions, fault injection

### ISSUE THREAD

**Issue by spacejam** [pingcap/tikv#341]
For building a robust distributed stateful system, it's a great idea to employ some more sophisticated distributed systems testing techniques, like running instances in a simulator that deterministically induces various interleavings of failures, and comparing resulting state to ensure various desired invariants have held.  I started down that path a bit with this: https://github.com/disasters/rasputin/blob/master/test/cluster.rs which I used for getting rasputin's consensus mechanism a bit more robust.  I would strongly recommend doing something similar by:
1. genericizing any sources of time, so that they can be passed in by the simulator (see how rasputin has a generic clock)
2. making the transport layer generic so that you can plug several instances into a test harness that simulates network failures
3. implementing quickcheck's `Arbitrary` for the simulator such that it generates sequences of failure conditions interleaved with mutation commands, delays, and creating properties that test certain recovery semantics.  If you're interested in examples of using quickcheck to generate sequences of operations that are then checked against, [check out this example from the crdts crate](https://github.com/spacejam/rust-crdt/blob/master/src/orswot.rs#L260)

**Comment by siddontang** [comment]
Hi @spacejam 

Although we have some tests for simulating cluster, it is not enough, thanks for your great advice, we will try it.  @tiancaiamao

**Comment by ngaut** [comment]
Thanks spacejam. Good idea.
We have created a Transport trait to simulator Network issues(reorder, partition, packet loss and delay, fault injection). We also have plans to do fault injection with file system.

**Comment by ngaut** [comment]
Done.
