### ISSUE TITLE
Make failed because of clipper 0.0.61 version

### ISSUE THREAD

**Issue by genedna** [pingcap/tikv#348]
I use **rustc 1.7.0 (a5d1e7a59 2016-02-29)** and **CentOS 7.1 x86_64** for`make build`.

When I ran `make` command in the repository, got errors and make failed.
```
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.61/src/booleans.rs:60:57: 60:58 error: expected one of `.`, `;`, `}`, or an operator, found `?`
/root/.cargo/registry/src/github.com-88ac128001ac3a9a/clippy-0.0.61/src/booleans.rs:60                     v = self.extract(op, &[lhs, rhs], v)?;
                                                                                                                                               ^
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `clippy`.
```

Then I tried `clippy` other version `0.0.60` and `0.0.50` and all failed.

**Comment by ngaut** [comment]
@genedna Thanks for reporting the issue. Currently, TiKV use nightly version of rustc and clippy. Please update your rustc and clippy.

**Comment by spullara** [comment]
I was able to build / test / benchmark cleanly by updating the package dependencies to the latest and using rustc nightly.

**Comment by ngaut** [comment]
Thank you. @spullara
