### ISSUE TITLE
rocksdb link err

### ISSUE THREAD

**Issue by menshibin** [pingcap/tikv#352]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.9.0-nightly (600dc3552 2016-04-04)

error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/gate/rust_obj/tikv/target/debug/bench_tikv.0.o" "-o" "/home/gate/rust_obj/tikv/target/debug/bench_tikv" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/gate/rust_obj/tikv/target/debug" "-L" "/home/gate/rust_obj/tikv/target/debug/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/gate/rust_obj/tikv/target/debug/libtikv.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libuuid-5650c0ca096e22f0.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-18402db3.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libbyteorder-79579e11a5fc0173.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/librocksdb-2cddebf65ff5868b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-18402db3.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/librustc_serialize-3bc953984ed46e7f.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libquick_error-9f95c6fba19f9325.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libbytes-c70b3e48eb9564b3.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libtempdir-2cdf7b3a831e6ac5.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/librand-c724acb3942597d1.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libmio-4dc84855cf75d5a3.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libbytes-2fbbdda5bbde5111.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libnet2-559ba40c19f23b6a.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libwinapi-42bc588a308ea664.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libkernel32-95c0b0ef43f70ab2.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libtime-71756e48b8b5b73b.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/liblibc-00ad8a4a4c184a2d.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/liblog-342ffb7444a9471d.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libnix-05000afe46152771.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/liblibc-5eb0f3d71076a4bc.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libslab-22c48cf3d25bac5c.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libmiow-ba6e9462e2153813.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libbitflags-d06009685951cc56.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libws2_32-2f1486c4a679970f.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libcfg_if-0a8d2242d60f8925.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libkvproto-c7b8aa136eedb5a0.rlib" "/home/gate/rust_obj/tikv/target/debug/deps/libprotobuf-40f78cc16fda400f.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-18402db3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-18402db3.rlib" "-l" "rocksdb" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "compiler-rt"
note: /usr/bin/ld: /usr/local/lib/librocksdb.a(c.o): relocation R_X86_64_32S against `_ZTVZ42rocksdb_slicetransform_create_fixed_prefixE7Wrapper' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/librocksdb.a: error adding symbols: 错误的值
collect2: error: ld returned 1 exit status

**Comment by ngaut** [comment]
@menshibin Thanks for reporting the issue. 
What's your rocksdb version ? Could you use https://github.com/facebook/rocksdb/archive/rocksdb-4.3.1.tar.gz ?

**Comment by menshibin** [comment]
i git clone https://github.com/facebook/rocksdb

**Comment by ngaut** [comment]
Please ref https://github.com/pingcap/tikv/blob/master/.travis.yml#L22 and https://github.com/pingcap/tikv/blob/master/.travis.yml#L34

**Comment by menshibin** [comment]
used https://github.com/facebook/rocksdb/archive/rocksdb-4.3.1.tar.gz 
tikv make
link err

**Comment by overvenus** [comment]
@menshibin Try:

```sh
$ cd rocksdb
$ sudo make install DEBUG_LEVEL=0
$ sudo make install-shared DEBUG_LEVEL=0
```
