### ISSUE TITLE
Support transfer leader feature in raft

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#363]
https://github.com/coreos/etcd/pull/4916

**Comment by xiang90** [comment]
Now this pr is merged. There is one optimization we might want to do to enable faster transfer. We will cc you guys when it is landed.

**Comment by xiang90** [comment]
https://github.com/coreos/etcd/issues/5020 for optimization discussion.

**Comment by ngaut** [comment]
Good news! Thanks you guys.

**Comment by tiancaiamao** [comment]
Done https://github.com/pingcap/tikv/pull/590
