### ISSUE TITLE
Documentation on setting up a cluster

### ISSUE THREAD

**Issue by spullara** [pingcap/tikv#400]
Is there some documentation on how to setup a cluster?

**Comment by siddontang** [comment]
Hi @spullara 

We will add a detailed document next week. 

Now, for running cluster, you should start etcd, pd, see https://github.com/pingcap/pd, then using 

```
target/debug/tikv-server -A 0.0.0.0:20161 --advertise-addr ${HostIP}:20161 -S raftkv -s /var/tikv1 --pd ${pd_advertise_addr} -I 1
target/debug/tikv-server -A 0.0.0.0:20162 --advertise-addr ${HostIP}:20162 -S raftkv -s /var/tikv2 --pd ${pd_advertise_addr} -I 1
target/debug/tikv-server -A 0.0.0.0:20162 --advertise-addr ${HostIP}:20163 -S raftkv -s /var/tikv3 --pd ${pd_advertise_addr} -I 1
```

Then you can use tidb with it
```
tidb-server --store=tikv --path=${etcd_advertise_addr}/pd?cluster=1
```

We will supply a docker-compose for easy use later.

**Comment by spullara** [comment]
That is good enough for me. Thanks.

**Comment by lavvy** [comment]
Hey can't find the documentation. And what about the compose file, could you point me to the compose file to setup a tidb cluster

**Comment by siddontang** [comment]
Hi @iamxy 

A simple one is here https://github.com/pingcap/tikv/blob/master/USAGE.md 
But now we have been embedding etcd in pd, and we will change all documents later after embedded. 
I will update whole usage document today.

**Comment by lavvy** [comment]
oh sorry for the late reply. have you been able to update the documentation
? and an inclusion of a compose file setup would be very awesome too

**Comment by siddontang** [comment]
Hi @iamxy 

I have wrote a simple one but this PR has not merged. You can check

https://github.com/pingcap/tikv/blob/siddontang/embed-etcd/USAGE.md
https://github.com/pingcap/pd/blob/siddontang/pd-etcd/README.md
https://github.com/pingcap/pd/blob/siddontang/pd-etcd/doc/clustering.md

Btw, I don't support a compose file now, because we wan't to use k8s to run this cluster directly,  but if you want, I can give a simple one too.

**Comment by lavvy** [comment]
Ok please could you make a simple one,  i just want to see how all the
components are wired

**Comment by lavvy** [comment]
Any success sir,  or you can push to the rancher community catalog,  it will get more usage and testing from users

**Comment by siddontang** [comment]
Hi @lavvy 

We have been moving all docs to https://github.com/pingcap/docs for unified management and adjusting command flags for more easily use. 

Sorry that you may change your command flags later if we finish these in this week. :-)
