### ISSUE TITLE
Add prefix/namespace support to KV

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#412]
Currently we can't run multiple tests concurrently because of isolation. We need an isolation  mechanism.
So TiDB make use it like:

   Open(DSN + prefix)

And we can reuse lots of tests.
TiDB may also use environment variable to define DSN.

**Comment by ngaut** [comment]
Call for discuss.

**Comment by siddontang** [comment]
I think first we should change tidb unit test to support a persistent engine with prefix to distinguish different tests, then we can use all tidb unit test for tikv.

**Comment by ngaut** [comment]
Yes

**Comment by spullara** [comment]
FoundationDB had a very nice system for generating keys. They had the notion of directories and subspaces which gave you a couple nice primitives for building up key spaces:

https://web.archive.org/web/20150325003904/https://foundationdb.com/key-value-store/documentation/javadoc/com/foundationdb/directory/DirectoryLayer.html

It was pretty useful and made it possible for lots of applications to use the KV store as long as they didn't write arbitrarily to the keyspace. Their Tuple class also made it easy to generate lexagraphically sorted compound keys. Might be useful to emulate it for people that use your KV store directly.

**Comment by ngaut** [comment]
@spullara Thanks for providing the links. It's helpful.  We will try to support namespace or directory api after we release beta.

**Comment by ngaut** [comment]
Done.
