### ISSUE TITLE
reject stale request vote raft message

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#417]
Let's consider following case:

3 peers in raft for 1, 2, 3.  1 is leader. 

+ stop node 3
+ ConfChange remove node 3
+ re-start node 3

After conf change, 1 and 2 have no info for 3 and won't communicate it at all, but 3 still knows 1 and 2.
So 3 will start a new election and then sends RequestVote to 1 and 2 with a bigger term, 1 and 2 will step down to follower and then start a new election again.

3 won't damage data, but will disturb raft group frequently, so we should reject this message.

In on_raft_message, we can check if the msg is RequestVote and the epoch is stale, we can discard it directly. 

@ngaut @BusyJay

**Comment by xiang90** [comment]
We keep removed node list in etcd and effectively ignore all messages from removed nodes.

**Comment by siddontang** [comment]
Maybe we can save removed peers too.

**Comment by xiang90** [comment]
@siddontang yea... you gc these list once per day or even week...

**Comment by siddontang** [comment]
We use msg epoch to check this now, see #419, but this just ignore request vote, using removed list can ignore all msgs. 

@ngaut

**Comment by ngaut** [comment]
@siddontang @xiang90 I expect by using epoch(region version and raft conf version) and current node list can be used to ignore all messages.

**Comment by siddontang** [comment]
@ngaut 

Should we add removed list later?

**Comment by siddontang** [comment]
I think we can just use epoch to check whether the message is stale.
If the message from peer ID is not in current region and the epoch ConfVer(need check Version here?) is smaller, we can reject this message no matter what the type is.

**Comment by xiang90** [comment]
@siddontang What is epoch? Configuration version?

**Comment by xiang90** [comment]
If yes, then sure that is even better.

**Comment by siddontang** [comment]
Yes, if we do a membership change, the ConfVer + 1.
