### ISSUE TITLE
disable compact log when sending snapshot.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#424]
Let's consider following case:

First add two peers in raft region a, 1, 2, 1 is leader, then add 3.
1 may send snapshot to 3, but unlucky, after 3 finishes applying snapshot, 1 has already done a compact log, so 1 and 3 have gap logs, 1 will send snapshot  again, but if 1 did compact log before 3 applying snapshot, loop again.

So we should disable compacting log when doing snapshot. After leader guarantee that all peers catch up it, we can allow compacting again.

@ngaut @BusyJay

**Comment by BusyJay** [comment]
I think it's enough to only compact the logs that have been replicated to all peers.

**Comment by xiang90** [comment]
> So we should disable compacting log when doing snapshot.

I think you want to disable snapshot when sending a snapshot. :)

>  I think it's enough to only compact the logs that have been replicated to all peers.

See above.

**Comment by siddontang** [comment]
@xiang90 

Not disable snapshot, here we want to not compact committed log when doing snapshot.

**Comment by xiang90** [comment]
@siddontang Yea... sorry for the typo...

**Comment by xiang90** [comment]
@siddontang But I think you do not have to disable compaction when doing the snapshot but when sending the snapshot.

**Comment by siddontang** [comment]
@xiang90 

I use `do` here is for whole flow: generate, send and then apply. 
We can use raft progress match to fix this, only compact logs before smallest match index, but this may cause log increased quickly if the peer is down.
