### ISSUE TITLE
fix resource temporary unavailable in ci

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#427]
Now we meet `resource temporary unavailable` frequently in ci, it seems that we set a read timeout in socket and read nothing after timeout. 
This may happen when we send to a stale leader, the stale leader can't commit the log and apply it, so it won't return the response. 

We should find a way to handle this. maybe if leader lost, calling all command Callback or checking timeout error in test and then re-try again. 

@ngaut @BusyJay

**Comment by BusyJay** [comment]
I think it will be safe to call all callback after receiving heartbeat from new leader. And it should return a special error to indicate that it's not sure whether the command is applied or not.
