### ISSUE TITLE
support pipeline and batch

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#428]
Call discussion.

@shenli @BusyJay .

**Comment by xiang90** [comment]
For raft or for your transportation layer?

**Comment by siddontang** [comment]
Transportation layer. Not raft now.

**Comment by xiang90** [comment]
We do smart batching (http://mechanical-sympathy.blogspot.com/2011/10/smart-batching.html) and pipelining in etcd transport layer. Note that etcd/raft supports pipelining and batching by default, so you should not need to do anything extra.

**Comment by shenli** [comment]
@xiang90 We need pipeline/streaming rpc between TiDB and TiKV.

**Comment by xiang90** [comment]
@shenli So sad you cannot just use gRPC...

**Comment by siddontang** [comment]
@xiang90 

Yes, we very want to use gRPC..
