### ISSUE TITLE
What does `Coprocessor support` mean?

### ISSUE THREAD

**Issue by xiang90** [pingcap/tikv#432]
I failed to understand what does this mean by reading the readme doc.

```
Coprocessor support
TiKV will be accessable and any application can develop on TiKV. 

We tend to provide a simple deployment solution soon after.
```

Can anyone explain this?

**Comment by ngaut** [comment]
The name of Coprocessor comes from HBase/Bigtable. Please ref https://blogs.apache.org/hbase/entry/coprocessor_introduction

**Comment by xiang90** [comment]
Thanks. I will try to make this more obvious in readme file.

**Comment by ngaut** [comment]
Thanks for cleaning up readme @xiang90
