### ISSUE TITLE
investigate failed test 

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#528]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/127716176/log.txt
https://travis-ci.org/pingcap/tikv/jobs/127716176

**Comment by BusyJay** [comment]
At first cluster have 2 peers labeled 1, 2. Assuming peer 1 is leader. Cluster add peer 3 first, then remove it, add it again. In the first step, peer 3 apply a snapshot, its progress in peer 1 become `Probe`, in which case it will be sent only one entry a time. In the second step, peer 1 broadcast conf remove to both peer 2 and peer 3. If peer 2 reply it first, peer 1 will broadcast all peers that confchange is committed then apply conf change. But peer 3 has not replied to proposal and it's in `Probe` mode, so it won't get notified. In step 3, peer 3 finally know that conf remove is committed, so it removes itself. But peer 1 still consider peer 3 is alive and send heartbeat to it which will lead to out of range commit panic.

In more general sense, when add peer a to group, then remove it, add it again. If in step 2, peer a is isolated and log has not been compacted yet, this may cause problem.

**Comment by BusyJay** [comment]
Currently we get around this with #547, we should fix that permanently and add stable test cases.

**Comment by siddontang** [comment]
When the follower receives a heartbeat message which log index is > current last log index, it will panic now. 
Maybe we can ignore this invalid heartbeat, and reject the following AppendLog to let leader re-send snapshot again. is it ok? /cc @xiang90

**Comment by xiang90** [comment]
>  But peer 1 still considers peer 3 is alive and sends heartbeat to it which will lead to out of range commit panic.

The panic indicates that the peer lost some entries. It is true in your case too. After peer 3 removes itself, shouldnt it ignore any incoming messages? When you add a peer again, it should have a new id, then leader will treat it as a fresh peer, not an existing one. Right?

**Comment by siddontang** [comment]
Em, now we add the peer again with the same id (using store id).

**Comment by siddontang** [comment]
The PR is https://github.com/pingcap/tikv/pull/511 here.
If we have no way to fix this, maybe we should re-add peer id again.

**Comment by xiang90** [comment]
@siddontang Why do you want to do that? Is there a hard requirement? raft expect the id to be unique. There will be tons of issues if you plan to reuse ids, at application layer and raft layer... It will just complicate the problem.

**Comment by siddontang** [comment]
We just want to simplify the code before, 😭 

maybe we should re-add it. @ngaut @BusyJay

**Comment by xiang90** [comment]
@siddontang 

If we: Add peer1, Remove peer1, Add peer1, Remove peer1, Add peer1

When peer1 comes back, it has to have the logic to ignore the 2 removals and adds itself back on the last request. Also there might be messages reorder issues, so besides checking peer ids we have to check the configuration version to ignore messages.

**Comment by siddontang** [comment]
@xiang90 
We also check conf versions when doing ConfChange, maybe we won't meet the reorder issue, but I will make a confirm.
