### ISSUE TITLE
test cases enhancement

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tikv#529]
- [ ] snapshot overlap

- [x] split brain

## snapshot overlap
Region 1 has peer A B C and A is leader.  Region 1 split became Region 1 and Region 2.
Region 2 has peer D E F and D is leader, which use the same store with A B C.
C don't know split operation is committed due to network latency yet

Suppose we have those message sequence:
D heartbeat message came to store...
F is created using D's snapshot...
peer C get the delayed split message...
C apply split operation and **overwrite** F
F lose data?

## split brain

Peer A B C, and C partition with A B. 
add Peer D E F to cluster, then remove A B
now D E F is the new cluster
C network recover and send message to A B
C A B became a cluster...
they both serve for the same region, i.e split brain

**Comment by BusyJay** [comment]
How can A and B be both removed without C's acknowledgement?
