### ISSUE TITLE
mysql-test InvalidDataType

### ISSUE THREAD

**Issue by morefreeze** [pingcap/tikv#535]
Please answer these questions before submitting your issue. Thanks!

1. What version of Rust are you using (`rustc --version`)?
rustc 1.10.0-nightly (576229fea 2016-04-15)

2. What operating system and processor architecture are you using?
Mac OS

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

  git checkout tidb/morefreeze/port-tikv
  start etcd, pd, tikv
  cd mysql_test && ./run-tests.sh
  About 10 seconds.

4. What did you expect to see?
Eliminate errors.

5. What did you see instead?
  - [x] `2016/05/05 20:19:28 main.go:478: [fatal] run test [groupby] err: run "select * from t where c1 = null group by c1;" at line 78 err other error: unknown error InvalidDataType("can\'t convert Null to bool")`
  - [x] `2016/05/05 20:28:20 main.go:478: [fatal] run test [index] err: run "select c1 from t where c1 >= "00:00:00";" at line 25 err other error: unknown error InvalidDataType("unsupported data type `7` of [7, 128, 0, 0, 0, 0, 0, 0, 0, 3, 128, 0, 0, 0, 0, 0, 0, 1]")`
 - [x] `2016/05/06 17:11:57 main.go:478: [fatal] run test [index] err: run "select c1 from t where c1 >= -0.0120;" at line 31 err other error: unknown error InvalidDataType("unsupported data type `6` of [6, 24, 128, 0, 0, 0, 0, 0, 0, 0, 49, 50, 0, 0, 0, 0, 0, 0, 249, 3, 128, 0, 0, 0, 0, 0, 0, 1]")`
  - [x] `2016/05/06 17:25:12 main.go:478: [fatal] run test [sqllogic] err: run "select * from tab1 where col1 != null;" at line 24 err other error: unknown error InvalidDataType("unsupported data type `5` of [5, 192, 22, 102, 102, 96, 0, 0, 0]")`
  - [x] `2016/05/16 20:11:22 main.go:475: [fatal] run test [sqllogic] err: run "select * from tab1 where col1 != null;" at line 24 err, we need:
select * from tab1 where col1 != null;
pk	col0	col1	col2	col3	col4	col5
select * from tab1 where co
but got:
select * from tab1 where col1 != null;
pk	col0	col1	col2	col3	col4	col5
0	6	5.6	jtqxx	9	5.19	qvgba
`
  - [x] `2016/05/16 20:01:15 main.go:475: [fatal] run test [groupby] err: run "select * from t where c1 = null group by c1;" at line 78 err, we need:
select * from t where c1 = null group by c1;
c1
select
but got:
select * from t where c1 = null group by c1;
c1
1
2
3`

**Comment by morefreeze** [comment]
First fix in #536

**Comment by BusyJay** [comment]
I will work on this after #533 merged.

**Comment by morefreeze** [comment]
First 4 items are fixed, but add 2 extra errors.
