### ISSUE TITLE
Add metrics for TiKV

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#566]
https://github.com/tshlabs/cadence seems to be a good choice.

Would you like to do that ? @overvenus

**Comment by overvenus** [comment]
Of course, but I need some time to familiar with [tshlabs/cadence](https://github.com/tshlabs/cadence) and [etsy/statsd](https://github.com/etsy/statsd).

**Comment by ngaut** [comment]
Cool!

**Comment by xiang90** [comment]
I hope you can use https://prometheus.io, which I believe will be the default metrics collecting tool in the near future. However, it does not have a rust binding.

**Comment by siddontang** [comment]
Find https://github.com/prepor/prometheus-rust but I don't know whether it can work or not.

Btw, I browser the prometheus doc and think it is not hard to support in rust, but this depends our need, if we decide to use prometheus, I think we can bind in rust, otherwise, not to do.

**Comment by ngaut** [comment]
Thanks @xiang90 
The rust implementation of prometheus is on early stage. Let's re-consider it later.
We may still use cadence right now.

**Comment by overvenus** [comment]
@ngaut Hi!

Here is my implemention plan and details:
 1. Add a new sub mod under mod utils, named **statsd**
 2. New **statsd** wraps **cadence**.
 3. Similar to crate log, **statsd** has a single static client, and may only be initialized once.

Pros:
 - It is convenient to change the underlying statsd implemention.
 - Simple API and less code, eg:
```rust
use utils::statsd;
statsd::count("foo", 1);
```

Cons:
 - Statsd's prefix is limited.
 - `unsafe` code block.

any suggestion?

**Comment by ngaut** [comment]
Please do not import any more "unsafe".
@BusyJay will help you to remove unsafe block.
Others look good to me.

**Comment by overvenus** [comment]
No `unsafe` :confused: 
OK, I will work around, or make a PLAN B.
