### ISSUE TITLE
support huge region snapshot send

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#594]
We will support huge region (>1GB) later, so sending this huge snapshot is a problem now, but luckily, we can refer etcd. 

Maybe we should do with following steps.

+ [x] Saving snapshot to file. Filename format "region_term_index.snap".
+ [x] connection supports sending snapshot file, The whole message like` [snapshot meta][huge snapshot body]`, we should hijack the connection to handle it.
+ [x] Supports snapshot worker to manage sending and applying snapshots. 
+ [x] When snapshot received, follower will first Step the snapshot meta to raft, after this, leader will send raft log to this follower again.
+ [x] Then we will delete whole region data and apply the snapshot data asynchronously, we will reject applying log and any other messages like Vote from other peers when applying snapshot.
+ [x] After applying OK, re-allow applying raft log again.
+ [ ] Limit the leader sending log speed if following is applying snapshot.
+ [x] Recover from snapshot when following crashes and restarts.

**Comment by xiang90** [comment]
Sounds good to me. Let me know if I can help on anything (except for writing rust code).

**Comment by ngaut** [comment]
What do you mean "limit leader's sending log speed" ? Why we need to do that ?

**Comment by siddontang** [comment]
Leader will send log to follower when follower is applying the snapshot, and the log size may use huge memory if the applying is slow, so as @xiang90 suggests, we should limit the log sending speed here as Etcd does.

**Comment by siddontang** [comment]
Hi @BusyJay 

Can we close this now? And we can add limit sending log in a new issue.

**Comment by BusyJay** [comment]
Sure.
