### ISSUE TITLE
Add rocksdb section to configure file.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#601]
We need to move some hard coded options to config file. We need a rocksdb section to config file right now. There is no need to build the tikv when we want to change options.

https://github.com/pingcap/tikv/blob/master/src/bin/tikv-server.rs#L143

@overvenus Would you like to take over this issue ?

**Comment by overvenus** [comment]
sure : )

**Comment by siddontang** [comment]
can we close it now?
