### ISSUE TITLE
add store id in metric

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#629]
@overvenus 

We should add store id in metric key so that we can distinguish different store statistics later. 

E,g, store 1, `tikv.raftstore.propose.success`  -> `tikv.raftstore.1.propose.success`

or putting 1 in other places?  /cc @ngaut

**Comment by overvenus** [comment]
Do you mean something like `metric_incr!(format!("raftstore.{}.propose.success", store.id));` ?

**Comment by siddontang** [comment]
yes.
