### ISSUE TITLE
UDP metric may block tikv

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#634]
Now we use UDP to send metric to statsd, but UDP may still block the process even it is very fast. See `man sendto`. 

We may send metric asynchronously, maybe the simplest way is using thread + channel. 

We should do the benchmark to make sure asynchronous sending can improve the performance.

@overvenus , can you help us to improve this?

**Comment by ngaut** [comment]
I prefer to change the send_buf size, or use just set non_block option to socket?

**Comment by BusyJay** [comment]
`util::Worker` is an abstraction of thread + channel with simple schedule policy.

**Comment by siddontang** [comment]
The socket is created in cadence, we should fire PR if we determine to using non-block socket or changing send buffer size.

**Comment by siddontang** [comment]
Btw, sendto is a system call, too frequently may cause performance reduction. So maybe thread + channel is more effective. But this is may guess,  we should do benchmark.

**Comment by overvenus** [comment]
Sure, I'd like to help, but I've been quite busy lately, you know the
final week of this semester is coming and annoying driver license, so it
is hard to say how much time it will take to finish this task.

Anyway, I will try my best :)

**Comment by ngaut** [comment]
thread + channel can't reduce syscall.

**Comment by siddontang** [comment]
yes, but  the syscall is in another thread, not origin raft thread. 
Of course, we need benchmark :-)

**Comment by overvenus** [comment]
`metric::set_metric_client()` requires `Sync + Send`, but neither `util::Worker` nor `util::Scheduler` satisfy `Sync`, because of a `Sender` inside.

BTW, I found a rejected RFC rust-lang/rfcs#1299 about `Sync` `Sender`, link to [detailed-design](https://github.com/seanmonstar/rfcs/blob/shared-sender/text/0000-shared-sender.md#detailed-design)

**Comment by ngaut** [comment]
Gotcha. Thank you  @overvenus

**Comment by siddontang** [comment]
@overvenus 

Using `Mutex<Sender>` is ok, I think you can use simple thread + channel at first now.

**Comment by ngaut** [comment]
I think the simplest way is  setting non_block option to socket. @siddontang

**Comment by overvenus** [comment]
Mutex may block tikv too. 

@ngaut I will try non_block later.

**Comment by siddontang** [comment]
Yep, the simplest way is to using non_block now, we should send cadence a PR or implement our own nonblock UDP sink.

**Comment by siddontang** [comment]
Hi @overvenus 

I do a simple benchmark and find that we can send 100 UDP in 1ms, this is very fast, so thread + channel is not needed. 

But we still need support non-block UDP socket.

Later we can cache in buffer and then send.

**Comment by overvenus** [comment]
@siddontang @ngaut @BusyJay 

The method [`set_nonblocking()`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.set_nonblocking) in `UdpSocket` moves UDP socket into nonblocking mode.
I did some benchmarks, and found out nonblock UDP can **not** enhance performance.

Result: 
```
$ cargo bench bench_single_thread
     Running target/release/bench_metric-b6de8d742c9d8b0f

running 2 tests
test tests::bench_single_thread_block_udp    ... bench:       4,427 ns/iter (+/- 182)
test tests::bench_single_thread_nonblock_udp ... bench:       4,419 ns/iter (+/- 144)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured

$ cargo bench bench_multi_thread_block_udp
     Running target/release/bench_metric-b6de8d742c9d8b0f

running 1 test
test tests::bench_multi_thread_block_udp     ... bench:  46,041,936 ns/iter (+/- 3,453,325)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured

$ cargo bench bench_multi_thread_nonblock_udp
     Running target/release/bench_metric-b6de8d742c9d8b0f

running 1 test
test tests::bench_multi_thread_nonblock_udp  ... bench:  46,017,645 ns/iter (+/- 3,835,662)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured
```

Gist: [BlockUdpMetric VS NonBlockUdpMetric](https://gist.github.com/overvenus/31b3adba8d60fbc81325a958a0e9fc9d)

Make sure you run the following command one at a time. (I use a globle `MetricSink`, so multi_thread benchmarks are not independent).
```sh
cargo bench bench_single_thread
cargo bench bench_multi_thread_block_udp
cargo bench bench_multi_thread_nonblock_udp
```

**Comment by siddontang** [comment]
Cool @overvenus 
Nonblocking is only for not blocking UDP socket when the socket buffer is full, so it can do little for improving the performance. 

Btw, seem thread benches cost much longer time?

**Comment by overvenus** [comment]
The last two emit 15000 metrics per-iter.
