### ISSUE TITLE
buffer metric and then send together for better performance

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#668]
We send metric every time to statsd when we call metric functions, although UDP is fast, we can still do some improvement for better performance.

We can buffer the metric and send them together. The common MTU is 1440, so we can use 1024 size buffer to cache metric and send these in one UDP package. see https://github.com/alexcesaro/statsd

@overvenus , could you help us do this benchmark and support it?

**Comment by overvenus** [comment]
Sure. I will start working on it three weeks later, as I have to prepare final examination. :sweat_smile:
