### ISSUE TITLE
A faster way to destroy region.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#677]
Currently, we scan the whole region to group keys into a write batch.  It wastes lots of cpu. Alse it blocks the raft thread. We need a new way to destroy region properly. 

RocksDB has a API called DeleteFilesInRange(It will be removed despite of existing snapshots). This api is fast and it saves cpu. Here is the way to do that. When we destroy a region. 
1. We first mark the region's state to deleting(in case we crashed, we can redo destroy step). 
2. Then call the api to delete files in region's raft log and data. 
3. Scan the raft log and data, remove them in a batch. 
4. Mark the state of region to tombstone.

We don't need a region tombstone key. And we add a new state field to value of region's meta key to describe the region state.

Ref: https://github.com/facebook/rocksdb/wiki/Delete-A-Range-Of-Keys

**Comment by siddontang** [comment]
Now this C API doesn't exist in newest release 4.6 (maybe next 4.7), we must use rocksdb master instead. And we should change the rocksdb building in CI and docker too.
/cc @BusyJay @iamxy

**Comment by siddontang** [comment]
Because we support static link rocksdb, so we can support this feature now. But for developers, we must upgrade rocksdb (4.9+) first. 

Should re-update https://github.com/ngaut/rust-rocksdb/pull/14.
