### ISSUE TITLE
Coprocessor Bug

### ISSUE THREAD

**Issue by shenli** [pingcap/tikv#713]
Run TiDB on TiKV:
drop table if exists t1, t2, t3;
create table t1 (c1 int, c2 int);
create table t2 (c1 int, c2 int);
create table t3 (c1 int, c2 int);
insert into t1 values (1,1), (2,2), (3,3);
insert into t2 values (1,1), (3,3), (5,5);
insert into t3 values (1,1), (5,5), (9,9);
select * from t1 left join t2 on t1.c1 = t2.c1 right join t3 on t2.c1 = t3.c1 order by t1.c1, t1.c2, t2.c1, t2.c2, t3.c1, t3.c2;

We will get: unknown error StringError("column meta of 5546 is missing")

**Comment by BusyJay** [comment]
fixed via #737
