### ISSUE TITLE
use sendfile to improve snapshot sending 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#720]
Now we use common way to send snapshot file 1, read file into a buffer, 2, send the buffer with socket, loop again until whole file sent ok. 

But in Linux, we can use `sendfile` to do this instead.

**Comment by xiang90** [comment]
Personally, i do not think it can bring us a lot of benefits. the snapshot sending is not a frequent event anyway. not sure if it worth the effort.

**Comment by ngaut** [comment]
I agree with @xiang90

**Comment by siddontang** [comment]
Now the origin flow is:

1. create a tcp socket
2. open the file
3. use io copy to send file
4. close file
5. close socket

And it is very easy to use lib::sendfile to replace io copy, so why not using it?

**Comment by ngaut** [comment]
Because it's not  a frequent event.

**Comment by ngaut** [comment]
Do you have any metrics that showing the improvement ?
