### ISSUE TITLE
Using Buffer/Batch to improve performance.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#771]

**Comment by ngaut** [comment]
1. Introduce a new way to buffer/batch RaftMessage to reduce network overhead
2. Buffer raft log to avoid scan rocksdb and decode it. So we can make "raft-log-apply" faster.

**Comment by siddontang** [comment]
@hhkbp2 you can fix case 2 first.

**Comment by hhkbp2** [comment]
About case 2:

The raft log cache has been added in branch https://github.com/pingcap/tikv/tree/hhkbp2/cache-raft-log, which add a one fly buffer for log entries in leader.

The performance profile:

deployment: pd in a server, tikv 1 node + tidb 1 instance in a server
test scenario: prepare data 5120000 rows, insert process 128 thread, 5120000 rows
flamegragh shows:
a) without cache, protobuf::parse_from_bytes is in range (1.65% - 2.02%)
b) with cache enabled, all callings of protobuf::parse_from_bytes are gone, the cache give high rate of hitting, which is about (0.22% - 0.29%)

It shows that enabling raft log cache would saving us about 1.4% running time.

A PR would be raised for this cache later.

**Comment by siddontang** [comment]
can you show us the benchmark with sysbench.
@zhangjinpeng1987 you can tell @hhkbp2 how to bench this.

**Comment by hhkbp2** [comment]
1. A new issue #958 is raised for point 1
2. The profiling after a attempt to add raft log cache shows that the performance is not sensibly  improved.

Would close this issue for now.
