### ISSUE TITLE
handle multiply region ready concurrently

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#784]
When we handle regions ready, we can move different regions to a thread pool and let it handle ready concurrently, and then wait all handling over and receive the ready result and do next.  

/cc @ngaut @disksing @zhangjinpeng1987

**Comment by siddontang** [comment]
@hhkbp2 

Seems that even after we use asynchronous scheduler, using multi thread for region ready still reduces the performance. We should dive into to find why performance reduction.

**Comment by hhkbp2** [comment]
@siddontang The very first term of the performance regression that comes to my head about this issue is the scheduling, since batch writing would improve the IO performance theoretically. I would track down the source code and get to know how to profile the performance. TO BE FOLLOWED UP.

**Comment by ngaut** [comment]
RocksDB has some options for concurrent writing, i guess we have not open it.

**Comment by siddontang** [comment]
@zhangjinpeng1987 
Seem that we can tune these options for concurrent writing https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L1280

**Comment by siddontang** [comment]
Seem that the RocksDB's options improves a little in our case, we should think another way to improve raft store performance.

**Comment by siddontang** [comment]
In our test, this can't improve too much improvement, and we will consider asynchronous apply later, so close this issue now.
