### ISSUE TITLE
raft: implemented read-only query when quorum check is on

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#813]
Port https://github.com/coreos/etcd/pull/5553

/cc @ngaut maybe we can use this feature

**Comment by ngaut** [comment]
Yes, we can get benefit for the PR.

**Comment by siddontang** [comment]
May consider https://github.com/coreos/etcd/pull/5997 too.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/916 implemented local read when in leader's lease
