### ISSUE TITLE
region leader report pd if a follower is unreachable for a long time.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#823]
Peers 1, 2, 3, 1 is leader and 3 is isolated. If 1 can send messages to 3 for a long time (like 10m), 1 will report this to pd. Pd can do balance for this region.

/cc @qiuyesuifeng @huachaohuang

**Comment by huachaohuang** [comment]
@BusyJay Have you been working on this yet? If not, you can assign this to me for [pd #189](https://github.com/pingcap/pd/issues/189).

**Comment by BusyJay** [comment]
Sure. :)
