### ISSUE TITLE
[Proposal] Revoke `pub` in raft.rs

### ISSUE THREAD

**Issue by overvenus** [pingcap/tikv#838]
I saw many private methods declared as `pub` in raft.rs. We can revoke pub by conditional compiling.

### How to?

For example, [Raft.tick_election()](https://github.com/pingcap/tikv/blob/master/src/raft/raft.rs#L536)

 1. Add a new feature in Cargo.toml

  ```toml
[features]
default = []
dev = ["clippy"]
internal_test = ["dev"]
```

 2. Add a stub method.

  original: 

   ```rust
    pub fn tick_election(&mut self) {
         // ...
    }
```

  stub: 

   ```rust
    #[cfg(feature = "internal_test")]
    pub fn test_tick_election(&mut self) {
        self.tick_election()
    }

    fn tick_election(&mut self) {
         // ...
    }
```

 3. Change `tick_election` to `test_tick_election` 

 [`r.tick_election();`](https://github.com/pingcap/tikv/blob/master/tests/test_raft_paper.rs#L819) -> `r.test_tick_election();`

 4.  run `cargo test --features internal_test`

I have tested in my machine, and it passed.

@BusyJay @ngaut @siddontang

**Comment by BusyJay** [comment]
I think using features to revoke pub is too complicated.

**Comment by siddontang** [comment]
using another mod can work? like 
```
#[cfg(tests)
impl raft {

}
```

Btw, I think public it is ok now, maintaining two functions is not easy.

**Comment by overvenus** [comment]
It works, but I think it is more complicated.

**Comment by ngaut** [comment]
It's ugly too.
