### ISSUE TITLE
Software clock: good things,  bad things, how to do it in another way

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#841]
Hi,

There is a `tick()` function in `src/raft/raft.rs`. It works as a software clock that periodically checks whether it have reached some timer and trigger these timers. The good thing of a software clock is that the programmers could assume they occupy a CPU and do whatever they want during this occupation, including checking some timer. It's much easier to code in this way. The bad thing is, it **does** take over the cpu. IMHO, it has a few drawbacks
1. inefficient
   
   Most of the times, the CPU wakes up and do no thing. This inefficience would be amplified if multiple raft groups are run in one node.
2. inaccurate
   
   Since it's a software clock, it's inaccurate considering the scheduling of OS processes/threads is inaccurate.
3. bad style
   
   Building a high level software abstraction is neccessary sometimes, it could simplify the code. But if the performance is the first priority, we should be able to get down to the low level mech, even hardware.

There are two styles of express something like a timer: the polling style VS. the event-driven style. IMHO, it's possible to write raft in the event-driven style(although doing that would make the impl more complex, like we usually do in the event-driven network programming). Even after it's done in event-driven style, the system clock is still needed to adjust the inaccuracy of event. Lucky that in raft a member node only needs the local relative time, and the cpu time is accurate enough since the crystal oscillator is always trustworthy.

**Comment by ngaut** [comment]
Right, as we discuess in our open meetup yesterday, we need  cpu clock to correct event timer. Then we can use the lease feature of raft to get consistent value from leader.

**Comment by ngaut** [comment]
Would you like to do something on it? @hhkbp2 
Something like:
Testing on how to simulate uncertain clock.
How to simulate slow/unstable disk ?

**Comment by hhkbp2** [comment]
@ngaut Currently I don't have a clear idea how to do these testing. Mock? Interface interception? There is a deep learning curve before I could actually write some code in the rust programming language. Maybe I could get a hand on it later when I have some more free time.

**Comment by siddontang** [comment]
In MIO, it uses clock_gettime with CLOCK_MONOTONIC to get the current time, this is the CPU clock but may still be affected by NTP, see http://man7.org/linux/man-pages/man2/clock_gettime.2.html, but using CLOCK_MONOTONIC_RAW has no problem. We should send an issue in MIO to discuss it. 

Btw, I don't think clock_gettime has a performance issue.
