### ISSUE TITLE
check requirement when `make install`

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#843]
Installing tikv needs some requirement, we should check this in install too.

E.g, we can check whether user installs rust or not, if not, we can install it automatically. The same for go and g++.

We must notice that user may have old low version go (< 1.5) or g++ (< 4.8), for this scenario, we may only raise error and let user upgrade these manually. 

Now we only care Ubuntu 14.04+, CentOS 7+, and Mac OS X. 

Hi @overvenus, could you help us to do it?

**Comment by overvenus** [comment]
Sure

**Comment by overvenus** [comment]
go needs GOPATH, I think user should install go manually instead of our script.

**Comment by siddontang** [comment]
no, we will use our own GOPATH, we don't need outer GOPATH.
