### ISSUE TITLE
Add a detecting module to monit system time

### ISSUE THREAD

**Issue by ngaut** [pingcap/tikv#859]
TiKV panic with the following log:

thread 'raftstore-3' panicked at 'other was less than the current instant', ../src/libstd/sys/unix/time.rs:274

I guess system time changed forward.

**Comment by siddontang** [comment]
Can we use CPU clock time directly ?

**Comment by ngaut** [comment]
No. We need to use ntpd. Also we can use ticker to detect system time issue.

**Comment by siddontang** [comment]
I think we can check this in raftstore event loop tick, if time jumps back, log an error.

**Comment by wuzhy** [comment]
HI, ngaut and siddontang

any solution to fix or workaround this issue? i also hit this issue

Regards,

wuzhy

**Comment by siddontang** [comment]
Hi @wuzhy 
Sorry that we don't have any solution yet.
It is very strange that we meet this error. (monotonic clock can't jump back). 

The newest version can output panic backtrace, and we have also filed an [issue](https://github.com/rust-lang/rust/issues/37137) for rust team.

**Comment by siddontang** [comment]
Hi @wuzhy 

We can ensure that this is the bug for the system, not for Rust and TiKV, so we can close it now.
