### ISSUE TITLE
support un-quorum read when leader still in lease.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#897]
After https://github.com/pingcap/tikv/issues/812, we can support un-quorum read now, with passing quorum-read field = false in command. 

If the leader is still in lease, the leader can directly generate the snapshot for read, not through raft. Note that this is not linearizability.

Any other things should we notice? /cc @ngaut  @xiang90 @swingbach

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/916 finished this issue
