### ISSUE TITLE
raft: handling of applying old snapshots

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#914]
https://github.com/coreos/etcd/pull/6099

Do we need to port it? @BusyJay

**Comment by BusyJay** [comment]
I don't think it's necessary. https://github.com/coreos/etcd/blob/master/raft/raft.go#L934 has check it before.

**Comment by siddontang** [comment]
@xiang90 
when do you need this check in ApplySnapshot?

**Comment by xiang90** [comment]
@siddontang It is not strictly necessary.
