### ISSUE TITLE
support output log to file and rotate file 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#919]

**Comment by siddontang** [comment]
refer https://github.com/pingcap/tidb/pull/1560
we should first support rotate by day.

**Comment by hhkbp2** [comment]
Hi @siddontang @BusyJay ,

I do some search on the internet about rust log library but couldnot find any practical one. I think it would be good to port a feature juicy log library to rust. I prefer to port the python `logging` library.

Only the file writing and rotating feature would be added as the very first version, as a short term effort for this PR. A new issue and the corresponding PR would be raised for the whole library porting stuff in the longer term future.

Please let me know if you have any idea on anything.

**Comment by siddontang** [comment]
You can refer https://github.com/ngaut/log/blob/master/log.go directly.
Now we only need to support rotate by day. 
You can implement a Logger like https://github.com/pingcap/tikv/blob/master/src/util/mod.rs#L57 and check when to rotate in `log` function.

**Comment by hhkbp2** [comment]
@siddontang 
Thanks for the info. And there is a piece of code which writes to file in
https://github.com/pingcap/tikv/blob/master/tests/util.rs#L69
Thank @BusyJay for pointing this out as well.

And the official doc of crate `log` gives a good docs on how to do a log impl.

I would add the rotating by day function as a short term effort.
As for the longer term, https://github.com/ngaut/log/ seems to be somewhat poor in feature. I perfer to port a full feature log library, as I did in the past: 
https://github.com/hhkbp2/go-logging

**Comment by siddontang** [comment]
no, we don't need a full feature log, now is enough.

**Comment by siddontang** [comment]
But you can do a rust practice in your spare time :-)
