### ISSUE TITLE
secondary index

### ISSUE THREAD

**Issue by doublex** [pingcap/tikv#920]
Does tikv support a secondary index?
If yes, which kind of index according to this table:
https://raw.githubusercontent.com/cockroachdb/cockroach/c3bc53a463f0a7036dcea06ac6d109d3ef2aa4fe/resources/doc/scan-efficiency.png

**Comment by ngaut** [comment]
Yes and no. TiKV does have any idea of secondary index. Secondary is support by TiDB which depends on TiKV. The kind of index should be the last one on right side. Actually supporting secondary index is easy, just add another key-value pair to point to origin key.
Let's say we want to add secondary index by using TiKV. If we have a simple table like: uid, email, and uid is primary key. And we want to build a
secondary index on email. we can simply store another key: email -> uid. So we have some key-value pairs like:
uid -> email
email -> uid

Hope that helps answer your question.

**Comment by doublex** [comment]
This sounds really great (like berkeley-db)
Thanks for your answer!

**Comment by doublex** [comment]
This database is really promising.

**Comment by jackxwu** [comment]
@ngaut a follow up question regarding your comment on 08/07/2016. does the server know that email->uid is an index? if client changes the email field in the uid->email table, does he also need to change the email->uid table by sending another request? how can we guarantee the "all or nothing" semantics.

**Comment by siddontang** [comment]
Hi @jackxwu 

You can use begin to start a transaction then commit or rollback it. 

```
txn := begin()
user = txn.get(uid)
user.email = "new email"
txn.set(uid, user)
txn.set(user.email, uid)
txn.commit()
```

The transaction can guarantee this.

**Comment by doublex** [comment]
@siddontang 
Excellent. Is there a chance to do this in C/C++ (to be used in node.js)?
