### ISSUE TITLE
run tikv-server on debian jessie release failed

### ISSUE THREAD

**Issue by terryzhao** [pingcap/tikv#928]
Hi Guys, 

I just want to run tikv-server on debian jessie release . But I just got the "Illegal Instruction" error. 
And then i used gdb to debug this error , the below is the trace dumped:

GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./tikv-server...done.
warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
of file /home/administrator/tidb/tikv-server
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) r
Starting program: /home/administrator/tidb/tikv-server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000555555c22b53 in _M_bkt_for_elements (this=0x5555562e8a00 <rocksdb::db_options_type_info+32>, __n=<optimized out>) at /usr/include/c++/5/bits/hashtable_policy.h:474
474	/usr/include/c++/5/bits/hashtable_policy.h: 没有那个文件或目录.
(gdb)

Do you guys have any suggestion for me ?  That will be very appreciated!

**Comment by siddontang** [comment]
Hi @terryzhao 

How do you build tikv?

**Comment by terryzhao** [comment]
I built it on Ubuntu16.04 as build guider.  And it runs well on Ubuntu16.04.

**Comment by terryzhao** [comment]
Should i install any prepared packages, when i want to run tidb on other linux release  or just copying pd-server, tike-server, tide-server is enough?

**Comment by siddontang** [comment]
Hi @terryzhao 
Do you build tikv in Ubuntu, and copy the binary to debian and use it directly? 
Do you follow the https://github.com/pingcap/docs/blob/master/op-guide/build.md to build the cluster?

**Comment by terryzhao** [comment]
Yes, i built tikv on Ubuntu , and copy the binary to debian and use it directly.  
I definitely built the binaries as the build guider. 
And just now, i tried it on my Aliyun cloud host (Ubuntu14.04), and got the same failure as debian. 

Below is my Aliyun cloud host : 

Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-32-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Welcome to aliyun Elastic Compute Service!

**Comment by siddontang** [comment]
em, seem that you should build portable tikv. can you enter tikv source and build it with 
```
ROCKSDB_SYS_STATIC=1 ROCSDB_SYS_PORTABLE=1 make 
```
again, maybe you should use `cargo clean` first.

**Comment by siddontang** [comment]
@queenypingcap 

I think we should add the PORTABLE notice in build guide. Currently, the build script only allows user using tikv in same platform.

**Comment by terryzhao** [comment]
OK, Let me try it quickly!

**Comment by siddontang** [comment]
I think we should use ROCSDB_SYS_PORTABLE=1 default, and add a tip for not portable build  if user want to more high performance for rocksdb.

**Comment by terryzhao** [comment]
Actually, TiDB is a distrubted DB. So in most case , people will use to build cluster :). 
So making  ROCSDB_SYS_PORTABLE=1   in default will be more reasonable.

**Comment by terryzhao** [comment]
Hi siddontang, 
The issue is not fixed.  I got the same "Illegal Instruction" error.

**Comment by siddontang** [comment]
@overvenus 

can you help me build the static and portable rocksdb in ubuntu 16.04 and then copy to debian jessie to check it.

@iamxy do you meet this scenario before?

**Comment by siddontang** [comment]
Hi @terryzhao 
What does `g++ --print-file-name libstdc++.a` output? 
Do you install static gcc library?

**Comment by terryzhao** [comment]
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a

**Comment by terryzhao** [comment]
Hi @siddontang ,

Do you have an IM communication channel ?   This github issue channel is not efficient for communication.

**Comment by ngaut** [comment]
Hi, @terryzhao 
Thanks for your report, we should keep using Github to track issues. So that other people can search it . It's very helpful for community to solve problems.

**Comment by siddontang** [comment]
@terryzhao 

`/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.a` is in your debain or building ubuntu?

**Comment by terryzhao** [comment]
in my debian

**Comment by siddontang** [comment]
what's the output in your ubuntu? @terryzhao

**Comment by terryzhao** [comment]
/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a

**Comment by terryzhao** [comment]
Hi @siddontang ,

I just compiled tiki-server on ubuntu 14.04 , and it works well now.  Thanks for you help very much!

**Comment by siddontang** [comment]
Hi @terryzhao 
@overvenus has being building tikv in ubuntu 16.04, and we must find why your case fails.
If we find anything, we will tell you later.

**Comment by terryzhao** [comment]
Hi @siddontang ,

I just compiled tiki-server on ubuntu 14.04 , and it works well now.  

But I will keep this issue open until you fix it on ubuntu16.04.  Thanks for your help continuously. 

And Hope you release the binaries,  it will be very helpful for deployment.

**Comment by overvenus** [comment]
Hi @terryzhao 

Sorry for late reply, I compiled a portable tikv in ubuntu 16 and copyed to ubuntu 14 and debian jessie, it works fine on both of them. I built tikv followd by: 

```sh
# gcc 
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# rocksdb
cd rocksdb-4.9
make shared_lib 
make install-shared 
make static_lib
make install-static

# tikv
ROCKSDB_SYS_STATIC=1 ROCSDB_SYS_PORTABLE=1 make
```

Did I miss something? Any information will be appreciated. Thanks!

**Comment by terryzhao** [comment]
Hi @overvenus ,

It's still not working for me.  I will not take more efforts on this issue. 

You can try to build tidb on Ubuntu16.04 and then copy the binaries to Aliyun ubuntu14.04 to verify this issue. 

I think this is a very common case.  If you cannot fix this issue , it will be very helpful for others.

**Comment by siddontang** [comment]
Thanks @terryzhao 

We will dive into this problem, if have any progress, we will tell you.

**Comment by overvenus** [comment]
Hi @terryzhao ,

It seems that I forgot setting `PORTABLE=1`. Without this flag I met the same problem, 'Illegal Instruction'.

The correct command of building static rocksdb should be `PORTABLE=1 make static_lib`.

Did you build a static rocksdb manually without `PORTABLE=1` before building tikv?

**Comment by siddontang** [comment]
Hi @terryzhao 

Sorry for my foolish typo mistake, we have already fixed this https://github.com/pingcap/docs/pull/27. You can use `ROCKSDB_SYS_STATIC=1 ROCKSDB_SYS_PORTABLE=1 make` to build tikv again, make sure `cargo clean` first.

**Comment by terryzhao** [comment]
Hi @overvenus ,

Thanks for you deep digging on this issue. I will try it later!
