### ISSUE TITLE
Support rocksdb's `SingleDelete`.

### ISSUE THREAD

**Issue by disksing** [pingcap/tikv#931]
https://github.com/facebook/rocksdb/wiki/Single-Delete

Differs from `Delete`, when `SingleDelete` entry meets an older entry during compaction, both will be removed. `SingleDelete` has a limit: the _key_ must exist and be put only once.

Seems suitable for TiKV -- almost all keys are put only once because of the key encoding of MVCC layer.

**Comment by ngaut** [comment]
Good idea.
