### ISSUE TITLE
Panics and their handling

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#934]
Hi,

In the raft impl, there are a few panics laying in the source code, which will cause the whole thread to abort. It would be better to categorize these panics and add handling for them. Generally they could be categorized as:

1. software bug  
    e.g. a mis-caculated index range, an unexpect case(invalid index) occurs.  
2. hardware error  
    e.g. disk reading error, data corruption. It is assumed to be unrecoverable

Both are fatal. And detailed info should be recorded for further analysis. Usually these two kinds of errors are treated differently: we could try to recover from a software exception but not the hardware error. And there could some cleanup work which needs to be done before that raft node abort, such as closing the corresponding network/db resource.

**Comment by ngaut** [comment]
software bugs in raft are unrecoverable, there are too many states of raft and peers. It's hard to handle them correctly. Also we should be able to recover from any network/db crashes without graceful close operation.
