### ISSUE TITLE
Missing feature for logging to file

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#937]
Hi there,

The PR #936 add the feature of logging to file, which rotates by day. But it does not maintain a max size of a single log file or a max total size of all log files. Without these features, the log files would expand without bound and eat up all capacity of the harddisks eventually. They are needed before TiKV goes into production.

It's better to implement a logging library in rust with full features which are ready for production.

**Comment by siddontang** [comment]
I suggest keeping log simple, maybe we will only add max file size support later at most.
