### ISSUE TITLE
use fast delete (delete_file_in_range) for DDL drop table.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#938]
Now the DDL for drop big table is slow, we fetch 1024 rows and delete them cyclically. This is slow, and in our test, the tikv scheduler thread will be very busy even we do nothing else. 

We can introduce a new API to let TiDB tell TiKV destroy quickly. If the dropping table state is "delete", we can destroy all table data with `delete_file_in_range` safely. 

/cc @ngaut @shenli @BusyJay  @zhangjinpeng1987

**Comment by ngaut** [comment]
Not now. We may reconsider this issue.
