### ISSUE TITLE
how to improve raft store performance

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#940]
After we use asynchronous scheduler, the performance bottleneck is in raft store thread now. 
We first tried #784 but found little improvement, so we should find another way.
1. Use asynchronous apply like etcd, this may change current code a lot ( @BusyJay )
2. Don't do anything but use multi-process directly.
3. Use multi-thread raftstore, @BusyJay tried before but met some problems, and it may be not easy to support merge later. 
4. others......

/cc @ngaut @BusyJay @hhkbp2 @zhangjinpeng1987

**Comment by hhkbp2** [comment]
Region number is far beyond the max thread number on a server. It's hard to dispatch and schedule region's raft state machine, or apply logic in a thread pool (efficiently and fairly). Would it be good enough to do simple scheduling on a thread pool? Or any other possible choice?
