### ISSUE TITLE
improve tikv-dump for MVCC inspect or another tool?

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#946]
Now tikv-dump is not good for inspecting MVCC, we should improve it so that we can dump these data easily for debug. 
Maybe we can support a tikv-ctl like etcd-ctl, like:

```
tikv-ctl mvcc ...
tikv-ctl raft ...
tikv-ctl kv ...
```

/cc @BusyJay @disksing @hhkbp2 @zhangjinpeng1987

**Comment by disksing** [comment]
We can support call mvcc command through cli:
```
tikv-ctl mvcc get 'key' 'ts'
tikv-ctl mvcc scan 'key' 'limit' 'ts'
tikv-ctl mvcc scan_lock 'max_ts'
```
Also some table encoding utility would be helpful:
```
tikv-ctl table encode_rowkey 'tableid' 'rowid'
tikv-ctl table decode_rowkey 'key'
tikv-ctl table decode_value 'value'
```

**Comment by BusyJay** [comment]
And maybe support use byte array as a key.

**Comment by siddontang** [comment]
we may use https://github.com/kbknapp/clap-rs to support subcommand.

**Comment by siddontang** [comment]
Hi @mrmiywj

Could you help us improve the tool first. You can ask @disksing for help when supporting MVCC first.

**Comment by mrmiywj** [comment]
Of course. I'll take a look at it.
