### ISSUE TITLE
Set a proper value for rocksdb option max_manifest_file_size

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tikv#947]
Refer to https://github.com/facebook/rocksdb/issues/54

**Comment by BusyJay** [comment]
Original thread is too long, can you summaries why a proper max_manifest_file_size is needed?

**Comment by hhkbp2** [comment]
@BusyJay The manifest file is where rocksdb put all compaction history and meta data. If an exit with exception causes data corruption, rocksdb will rescan the whole manifest file to construct the database. Set a size limit for the manifest file would avoid the rocksdb re-opening time being to long.

**Comment by BusyJay** [comment]
Get it, thx.
