### ISSUE TITLE
Placement Driver

### ISSUE THREAD

**Issue by doublex** [pingcap/tikv#948]
Wouldn't it be worthwhile to integrate the 'Placement Driver' into tikv?

**Comment by siddontang** [comment]
no @doublex 
+ PD is written with Go, tikv is Rust, it is hard to combine them together. 
+ PD is the control center, and scheduler TiKVs, they are two different levels in TiDB cluster.

**Comment by reinventions** [comment]
Can we use TiKV without PD? If not, why isn't PD part of TiKV?

Different languages shouldn't be a problem.

**Comment by siddontang** [comment]
yes @reinventions  you can start a single standalone TiKV without PD, but cluster must use. 

In our design, we should keep PD -> TiKV -> TiDB separately and won't combine them into one binary. Of course, this may cause deployment not easily, but the architecture is elasticized and resilient and the service hierarchy is clear.

**Comment by doublex** [comment]
@siddontang 
Thanks for your answer.

**Comment by mysunnyshine** [comment]
Do you have any example for  a single standalone TiKV without PD?   I just want to run some tests and needn't PD .
