### ISSUE TITLE
use circle file to store raft log

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tikv#953]
We store raft log in rocksdb along with other normal data now, this has some disadvantages:
1) we shared rocksdb instance, this will increase rocksdb's size and will reduce the normal data's cache hit rate.
2) when raft log has applied, we have to gc it use rocksdb's delete api, this cause write to rocksdb.
3) when apply raft log, we need read it from rocksdb at first, rocksdb's read may travel many levels.

If we use circle file to store raft log, we will walk through these issues. When raft log has applied we just need to advance meta data.

**Comment by siddontang** [comment]
what's circle file?

**Comment by xiang90** [comment]
rotating on created wal files. it can help with block allocation, especially for cloud virtual disks.

**Comment by siddontang** [comment]
Hi @xiang90, the circle confuses me, I guess the circle is 1, 2, 3, ... n, then loops again with 1, 2, 3...
I preferring using WAL (like etcd) here directly.  
BTW, it is not easy to support multi raft in WAL, we should think carefully.

@zhangjinpeng1987

**Comment by ngaut** [comment]
Let's just using a single RocksDB column family to store raft log for simplicity. And see if there are any performance issue. It' easy to tune single RocksDB column family.

**Comment by xiang90** [comment]
@siddontang @ngaut Agree with trying out rocks first. if there is a performance issue, try other options.

**Comment by siddontang** [comment]
can we close it now? @zhangjinpeng1987
