### ISSUE TITLE
add reconnection mechanism 

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/tikv#956]
Now setting up a TiDB cluster, the start-up sequence must be PD -> TiKV -> TiDB, otherwise it will fail to build，up to 99% probability. This is not friendly for setting up a cluster, please add a simple reconnection mechanism in TiKV to make world better.

**Comment by ngaut** [comment]
Thanks for your advice. I will add a TODO label for this issue.

**Comment by siddontang** [comment]
TiKV has supported re-connection for PD, but it only try 100 times with 50ms every time, so if the PD doesn't start ok in 5s, TiKV may fail.

We can check more times and wait longer when checking is_cluster_bootstrapped in node.rs. @huachaohuang

**Comment by siddontang** [comment]
In TiDB, this may panic when opening the storage, we may handle here. @shenli
