### ISSUE TITLE
improve test coverage 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#966]
Now the test coverage is 82%, I think we should improve to at lease 90%+ or even higher. 

This is a long-term continuous work.

See https://coveralls.io/github/pingcap/tikv 
Or see http://sunjay.ca/2016/07/25/rust-code-coverage to cover in own machine. 

@hhkbp2 I think we can first find some very low coverage packages and re-add tests.

**Comment by Hoverbear** [comment]
I'm going to close this issue since it's two years old and does not represent a task that can be "completed", instead it represents ongoing work. Feel free to re-open it if you have a differing opinion. :)
