### ISSUE TITLE
benchmark performance reduces when meeting split

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#974]
Running with 30 concurrences with 3 TiKV. the output:

```
2016/08/25 16:11:23 total: 1300000 speed: 3715.42
2016/08/25 16:11:29 total: 1310000 speed: 1704.95
2016/08/25 16:11:32 total: 1320000 speed: 3617.88
```

we can see that the performance reduces sometimes, the logs show that TiKV was doing `split` at that time. 

Issue https://github.com/pingcap/tikv/issues/816 may improve this, and any other way? 

Test case https://gist.github.com/siddontang/e1f447af9bafd03bfb380aff4f3ee912

**Comment by disksing** [comment]
I have investigated this issue. The performance reduces significantly when a region splits and new region's metas are not synced to PD in time. In this case, TiDB will retry many times using the expired meta.
A workaround: When TiKV reports a StaleEpoch error to TiDB, it can also send related newer region meta. Then TiDB can update its cache without loading meta from PD.

**Comment by ngaut** [comment]
Good idea.

**Comment by BusyJay** [comment]
If [a, d) is split into [a, c) and [c, d), [a, c) is split into [a, b) and [b, c). When request come to [a, b), which meta should be return? [a, b), [b, c) or [c, d)?

**Comment by disksing** [comment]
The metas TiKV sends along with StaleEpoch depends on request's context.
When request contains _[a, d)_, it returns _[a, c)_ and _[c, d)_. When request contains _[a, c)_, it returns _[a, b)_ and _[b, c)_.
If the request's context contains the range _[a, b)_, the client's cache should be already updated, no need to return a StaleEpoch error.

**Comment by BusyJay** [comment]
What if [a, b) (or [b, c)) is moved to another store?

**Comment by disksing** [comment]
In that case, RegionNotFound will be returned before check epoch.

**Comment by BusyJay** [comment]
When [b, c) is moved to another store, it will hit StaleEpoch.

**Comment by disksing** [comment]
Fixed.
