### ISSUE TITLE
a tool to benchmark raw KV 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#980]
Now some users want to use raw TiKV (no SQL, or even no transaction API). We need a tool to bench tikv cluster. 

We can use many codes here https://github.com/pingcap/tidb/tree/master/store/tikv.

**Comment by BusyJay** [comment]
Can the code in https://github.com/pingcap/tikv/blob/master/benches/bin/bench-tikv.rs be reused?

**Comment by siddontang** [comment]
We will bench servers in different machines, may 3 PD + 3 TiKV. 
The bench-tikv.rs is not enough.
