### ISSUE TITLE
use `delete_in_range_cf` to compact log 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#993]

**Comment by zhangjinpeng1987** [comment]
I don't think `delete_in_range_cf` can increase performance for compact log, but the opposite effect. If we don't compact raft log until there are a lot of log entries can be compacted, `delete_in_range_cf` may take effects, but this will cause the used disk space expand a lot.

**Comment by siddontang** [comment]
yes, I will close it now.
